"""Agent Registry -- declarative catalog of every specialized agent already
running in the LDCN OS, plus the ones named in the architecture proposal that
have no engine yet ("planned").

This module executes nothing and changes no behavior. It is a read-only
catalog over infrastructure that already exists (factory_pipeline's
AGENT_PROMPTS/PIPELINE_ORDER/_ROLE_EFFORT, the recovery triad, the quality
gate engines) so a caller can answer "which agents exist, what can each one
touch, and where is it implemented" from one place instead of grepping five
files. Phase 0 of the LDCN Multi-Agent Runtime proposal.

See docs/07-agent-runtime-conventions.md for how to add an entry. Every
`implementation` string below is `module:attribute` and is exercised by
test_agent_registry.py, which fails loudly if an entry drifts from the real
module (renamed function, deleted engine, etc.) -- this catalog is checked
against the code, never a second source of truth that can silently rot."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

AgentCategory = Literal[
    "planning", "architecture", "implementation", "quality", "security", "recovery", "experience",
]

AgentStatus = Literal["active", "planned"]


@dataclass(frozen=True)
class AgentDefinition:
    id: str
    category: AgentCategory
    title: str
    objective: str
    responsibilities: tuple[str, ...]
    limitations: tuple[str, ...]
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    allowed_context: tuple[str, ...]
    allowed_paths: tuple[str, ...]
    forbidden_paths: tuple[str, ...]
    success_criteria: tuple[str, ...]
    failure_criteria: tuple[str, ...]
    implementation: str
    uses_llm: bool
    status: AgentStatus = "active"


_AGENTS: tuple[AgentDefinition, ...] = (
    # ---------------------------------------------------------------- planning
    AgentDefinition(
        id="context_agent",
        category="planning",
        title="Context Agent",
        objective="Turn a raw user intent into a validated ProjectSpec through a guided conversation.",
        responsibilities=("Ask clarifying questions", "Fill assumptions with a stated reason", "Enforce the user's preferred language/stack"),
        limitations=("Never writes code or files", "Never picks the final architecture -- that is architecture_agent's job"),
        inputs=("raw_intent", "prior_answers", "preferred_language"),
        outputs=("ProjectSpec", "open_questions"),
        allowed_context=("conversation history for this Project Room",),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("ProjectSpec validates against schema", "every assumption has a `reason`"),
        failure_criteria=("LLM output fails schema validation twice in a row",),
        implementation="app.engines.orchestrator_engine:run_orchestrator",
        uses_llm=True,
    ),
    AgentDefinition(
        id="decision_agent",
        category="planning",
        title="Decision Agent",
        objective="Record which model/agent made each generation decision, and why.",
        responsibilities=("Persist provider/model/role/alternatives-considered/cost/latency per LLM call",),
        limitations=("Read-only after the fact -- never influences the decision it records",),
        inputs=("provider", "model", "agent_role", "model_strategy", "selection_policy", "alternatives", "usage"),
        outputs=("LlmDecisionTrace row",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("trace is queryable via GET /observability/decisions before the caller's response returns",),
        failure_criteria=("recording raises and is not caught (must be fault-isolated, see record_decision_safely)",),
        implementation="app.repositories.llm_decision_trace_repository:LlmDecisionTraceRepository.record",
        uses_llm=False,
    ),
    # ------------------------------------------------------------- architecture
    AgentDefinition(
        id="architecture_agent",
        category="architecture",
        title="Architecture / Contract Agent",
        objective="Resolve competing files for the same logical artifact into one canonical, non-ambiguous set before it is ever written to disk.",
        responsibilities=("Deduplicate competing paths for one logical file", "Detect competing backend source roots / multiple entrypoints", "Block (never guess) when a conflict is genuinely ambiguous"),
        limitations=("Only reasons about paths already emitted by other agents -- never generates new content",),
        inputs=("emitted files for the current job",),
        outputs=("ArchitectureManifest artifact", "blocked + blockReason when ambiguous"),
        allowed_context=("the current job's own emitted-files set",),
        allowed_paths=(".ldcn/architecture-manifest.json",),
        forbidden_paths=("source files it did not itself canonicalize",),
        success_criteria=("exactly one canonical path per logical file, or an explicit block",),
        failure_criteria=("two files claim the same canonical path with no resolution",),
        implementation="app.engines.architecture_consolidation_gate:architecture_consolidation_gate",
        uses_llm=False,
    ),
    AgentDefinition(
        id="dependency_agent",
        category="architecture",
        title="Dependency Agent",
        objective="Audit the emitted dependency manifest for known-bad or incompatible versions before build.",
        responsibilities=("Resolve real package versions", "Flag CVEs (OSV.dev-backed) across all supported ecosystems",),
        limitations=("Advisory only inside the automated pipeline -- does not block generation on its own",),
        inputs=("dependency manifest",),
        outputs=("DependencyAuditReport",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("every declared dependency has a resolved real version",),
        failure_criteria=("manifest references a package/version that does not exist",),
        implementation="app.services.dependency_research_service:DependencyResearchService.audit_manifest",
        uses_llm=False,
    ),
    # ------------------------------------------------------------ implementation
    AgentDefinition(
        id="contracts_agent",
        category="implementation",
        title="Contracts Agent",
        objective="Emit the OpenAPI contract every other implementation agent then builds against.",
        responsibilities=("Emit a valid OpenAPI 3.1 document from the approved ProjectSpec + blueprint",),
        limitations=("Runs first, before any other implementation agent -- cannot reference files that don't exist yet",),
        inputs=("ProjectSpec", "blueprint", "mega prompt"),
        outputs=("openapi.yaml",),
        allowed_context=("Project Memory", "Shared Context (context_pack_builder)", "Stack Lock"),
        allowed_paths=("openapi.yaml", "contracts/**"),
        forbidden_paths=("src/**",),
        success_criteria=("OpenAPI document parses and validates",),
        failure_criteria=("invalid YAML/JSON, or missing required paths from the spec",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['contracts']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="backend_agent",
        category="implementation",
        title="Backend Agent",
        objective="Implement the backend against the already-emitted contract.",
        responsibilities=("Emit backend source files honoring the OpenAPI contract and chosen stack",),
        limitations=("Never redefines the contract -- treats contracts_agent's output as fixed input",),
        inputs=("openapi.yaml", "ProjectSpec", "blueprint", "Project Memory"),
        outputs=("backend source files",),
        allowed_context=("Project Memory", "Shared Context", "Stack Lock", "Evolution insight"),
        allowed_paths=("backend/**", "src/backend/**"),
        forbidden_paths=("openapi.yaml", "frontend/**"),
        success_criteria=("emitted files parse for the target language, no unresolved contract endpoints",),
        failure_criteria=("stage timeout, or a security-blocked secret in emitted content",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['backend']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="frontend_agent",
        category="implementation",
        title="Frontend Agent",
        objective="Implement the frontend against the contract and the backend's real emitted routes.",
        responsibilities=("Emit frontend source files consuming the real contract",),
        limitations=("Runs after backend -- cannot invent endpoints the contract does not declare",),
        inputs=("openapi.yaml", "backend emitted files", "ProjectSpec"),
        outputs=("frontend source files",),
        allowed_context=("Project Memory", "Shared Context", "Stack Lock"),
        allowed_paths=("frontend/**", "src/frontend/**", "app/**", "components/**"),
        forbidden_paths=("backend/**",),
        success_criteria=("no orphan API calls to non-existent endpoints",),
        failure_criteria=("stage timeout, or a security-blocked secret in emitted content",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['frontend']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="mobile_agent",
        category="implementation",
        title="Mobile Agent",
        objective="Implement the mobile client, conditional on delivery_type requiring one.",
        responsibilities=("Emit React Native + Expo source files consuming the real contract",),
        limitations=("Only runs for delivery types that include mobile -- Flutter is not available (Mobile Factory Phase 5 gate)",),
        inputs=("openapi.yaml", "ProjectSpec"),
        outputs=("mobile source files",),
        allowed_context=("Project Memory", "Shared Context", "Stack Lock"),
        allowed_paths=("mobile/**",),
        forbidden_paths=("backend/**", "frontend/**"),
        success_criteria=("no orphan API calls to non-existent endpoints",),
        failure_criteria=("stage timeout, or a security-blocked secret in emitted content",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['mobile']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="test_writer_agent",
        category="implementation",
        title="Test Agent (writer)",
        objective="Emit automated tests against the real backend/frontend already implemented.",
        responsibilities=("Emit unit/integration tests covering the emitted implementation",),
        limitations=("Does not run the tests it writes -- that is build_agent's job, post-write",),
        inputs=("backend + frontend emitted files",),
        outputs=("test source files",),
        allowed_context=("Project Memory", "Shared Context"),
        allowed_paths=("tests/**", "**/*.test.*", "**/*.spec.*"),
        forbidden_paths=("non-test source files",),
        success_criteria=("emitted tests parse for the target language",),
        failure_criteria=("stage timeout",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['qa']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="devops_agent",
        category="implementation",
        title="Infrastructure Agent",
        objective="Emit build/deploy configuration for the chosen stack.",
        responsibilities=("Emit Dockerfiles, CI config, env templates consistent with the real emitted stack",),
        limitations=("Never invents infrastructure the ProjectSpec/blueprint did not select",),
        inputs=("blueprint", "Stack Lock"),
        outputs=("infra config files",),
        allowed_context=("Project Memory", "Shared Context", "Stack Lock"),
        allowed_paths=("Dockerfile*", "docker-compose*", ".github/**", "infra/**"),
        forbidden_paths=("source files",),
        success_criteria=("config references only dependencies the stack actually emitted",),
        failure_criteria=("stage timeout",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['devops']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="docs_agent",
        category="implementation",
        title="Documentation Agent",
        objective="Generate project documentation from the real generated files, not a template.",
        responsibilities=("Emit README/API docs describing what was actually built",),
        limitations=("Describes the real output -- never documents planned-but-unbuilt features",),
        inputs=("all emitted files", "openapi.yaml"),
        outputs=("documentation files",),
        allowed_context=("Project Memory", "Shared Context"),
        allowed_paths=("docs/**", "README.md"),
        forbidden_paths=("source files",),
        success_criteria=("every documented endpoint/entity exists in the real emitted files",),
        failure_criteria=("stage timeout",),
        implementation="app.engines.factory_pipeline:PIPELINE_ORDER['docs']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="change_request_agent",
        category="implementation",
        title="Change Request Agent",
        objective="Apply a scoped, user-requested patch to an already-generated project.",
        responsibilities=("Emit a minimal diff satisfying the change request, not a regeneration",),
        limitations=("Never touches files outside the change request's declared scope",),
        inputs=("ChangeRequest", "existing project files"),
        outputs=("patch files",),
        allowed_context=("Project Memory", "the change request's own scope"),
        allowed_paths=("files explicitly named or implied by the change request",),
        forbidden_paths=("everything outside the change request's scope",),
        success_criteria=("patch applies cleanly and the existing test suite still passes",),
        failure_criteria=("patch touches a file outside declared scope",),
        implementation="app.engines.agent_prompts:AGENT_PROMPTS['change_request']",
        uses_llm=True,
    ),
    # ----------------------------------------------------------------- quality
    AgentDefinition(
        id="build_agent",
        category="quality",
        title="Build Agent",
        objective="Actually install, build and test the generated project -- never assume it works.",
        responsibilities=("Run real install/build/test", "Compute a pass/fail verdict and score"),
        limitations=("Runs once per write attempt -- repeated failures escalate to the repair chain, not infinite retries",),
        inputs=("written project root",),
        outputs=("GenerationValidationReport", "job.buildStatus"),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("install + build + test all pass",),
        failure_criteria=("any of install/build/test fails",),
        implementation="app.engines.generation_validation_engine:generation_validation_engine",
        uses_llm=False,
    ),
    AgentDefinition(
        id="functional_completeness_agent",
        category="quality",
        title="Functional Completeness Agent",
        objective="Score real endpoint/UI coverage against the resources the spec declared.",
        responsibilities=("Evaluate per-resource CRUD/UI wiring completeness",),
        limitations=("Advisory -- does not block READY on its own",),
        inputs=("written project root", "ProjectSpec resources"),
        outputs=("product-completion-report.json",),
        allowed_context=(),
        allowed_paths=("product-completion-report.json",),
        forbidden_paths=("*",),
        success_criteria=("report reflects real wiring, never an invented percentage",),
        failure_criteria=("evaluation raises (must be fault-isolated)",),
        implementation="app.engines.functional_completeness_engine:functional_completeness_engine",
        uses_llm=False,
    ),
    AgentDefinition(
        id="functional_coverage_agent",
        category="quality",
        title="Functional Coverage Agent",
        objective="Score frontend/mobile coverage of the backend surface.",
        responsibilities=("Detect wired vs. dead buttons/forms/nav/data",),
        limitations=("Advisory -- runs independently downstream of functional_completeness_agent",),
        inputs=("written project root", "resources"),
        outputs=("coverage report",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("every claim is backed by a real static-analysis match",),
        failure_criteria=("evaluation raises (must be fault-isolated)",),
        implementation="app.engines.functional_coverage_engine:functional_coverage_engine",
        uses_llm=False,
    ),
    AgentDefinition(
        id="certification_agent",
        category="quality",
        title="Product Certification Agent",
        objective="Consolidate build + completeness + coverage + a fresh quality-gate pass into one of six certification states.",
        responsibilities=("Pure decision function over already-computed reports -- detects nothing new itself",),
        limitations=("Never runs before the reports it consolidates",),
        inputs=("GenerationValidationReport", "completeness report", "coverage report", "QualityGateReport"),
        outputs=("ProductCertificationStatus",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("status matches the worst input signal, never optimistic rounding",),
        failure_criteria=("a required input report is missing",),
        implementation="app.engines.product_certification_engine:product_certification_engine",
        uses_llm=False,
    ),
    AgentDefinition(
        id="deep_verification_gate_agent",
        category="quality",
        title="Validation Agent (deep-verification chain)",
        objective="Turn raw quality/build/dependency/security signals into typed, severity-ranked QualityIssues on demand (the 'sala de teste' flow).",
        responsibilities=("Classify each issue's severity, root cause, suggested fix, and whether it is auto-fixable",),
        limitations=("Not in the automated pipeline -- only reachable from the deep-verification routes",),
        inputs=("project quality/build/dependency/security signals",),
        outputs=("QualityGateReport (list of QualityIssue)",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("every BLOCKER issue has a suggested_fix or is explicitly unfixable",),
        failure_criteria=("evaluation raises",),
        implementation="app.engines.quality_gate_engine:quality_gate_engine",
        uses_llm=False,
    ),
    AgentDefinition(
        id="auto_repair_agent",
        category="quality",
        title="Repair Agent (deterministic tier)",
        objective="Fix QualityIssues that have a known deterministic fix, before ever calling an LLM.",
        responsibilities=("Apply a fixer keyed by QualityIssue.id",),
        limitations=("Only touches issues explicitly marked auto_fixable",),
        inputs=("QualityGateReport",),
        outputs=("patched project",),
        allowed_context=(),
        allowed_paths=("files named by the issue being fixed",),
        forbidden_paths=("issues not marked auto_fixable",),
        success_criteria=("issue no longer reproduces on re-evaluation",),
        failure_criteria=("fixer raises, or issue still reproduces",),
        implementation="app.engines.auto_repair_engine:AutoRepairEngine.repair",
        uses_llm=False,
    ),
    AgentDefinition(
        id="llm_repair_agent",
        category="quality",
        title="Repair Agent (LLM escalation tier)",
        objective="Fix QualityIssues the deterministic tier could not, as the last resort -- never the first attempt.",
        responsibilities=("Repair only issues auto_repair_agent left unresolved",),
        limitations=("Only reachable after auto_repair_agent has already run and failed on an issue",),
        inputs=("QualityIssues unresolved by auto_repair_agent",),
        outputs=("patched project"),
        allowed_context=("the specific failing file(s) and issue diagnostic",),
        allowed_paths=("files named by the issue being fixed",),
        forbidden_paths=("issues auto_repair_agent already resolved",),
        success_criteria=("issue no longer reproduces on re-evaluation",),
        failure_criteria=("repair raises, or issue still reproduces after MAX attempts",),
        implementation="app.engines.llm_repair_engine:LlmRepairEngine.repairable_issues",
        uses_llm=True,
    ),
    AgentDefinition(
        id="visual_qa_agent",
        category="quality",
        title="Visual QA Agent",
        objective="Verify generated UI screenshots match the intended design, not just that the app builds.",
        responsibilities=(),
        limitations=("No engine exists yet -- named only as a checklist item in docs/05-quality-gates.md",),
        inputs=(),
        outputs=(),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=(),
        failure_criteria=(),
        implementation="",
        uses_llm=True,
        status="planned",
    ),
    AgentDefinition(
        id="accessibility_agent",
        category="quality",
        title="Accessibility Agent",
        objective="Verify generated UI meets baseline accessibility requirements.",
        responsibilities=(),
        limitations=(
            "No dedicated engine yet -- accessibility questions are currently folded into "
            "frontend_qa_review_agent's holistic review (PARTE 7), not a standalone deterministic check",
        ),
        inputs=(),
        outputs=(),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=(),
        failure_criteria=(),
        implementation="",
        uses_llm=False,
        status="planned",
    ),
    # ---------------------------------------------------------------- security
    AgentDefinition(
        id="secret_scan_agent",
        category="security",
        title="Secret Scan Agent",
        objective="Classify emitted content as a real secret, a safe placeholder, or a safe reference before it can ever be written to disk.",
        responsibilities=("Entropy + pattern classification of literal values in emitted files",),
        limitations=("Classifies content it is given -- does not scan files it was not asked to check",),
        inputs=("relative_path", "file content"),
        outputs=("list[SecretFinding]",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("a real secret is never classified as safe",),
        failure_criteria=("a placeholder is blocked as a real secret (false positive) often enough to break generation",),
        implementation="app.services.artifact_security:classify_secret_findings",
        uses_llm=False,
    ),
    AgentDefinition(
        id="dependency_scan_agent",
        category="security",
        title="Dependency / Integration Scan Agent",
        objective="Audit third-party provider integrations and dependency CVEs for resilience and real test coverage.",
        responsibilities=("Check Stripe/SendGrid-class integrations for retry/error handling and test coverage",),
        limitations=("Pure file inspection -- never calls the real third-party provider",),
        inputs=("written project root", "selected_infrastructure_ids"),
        outputs=("integration audit findings",),
        allowed_context=(),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("every opted-in provider has a corresponding resilience check",),
        failure_criteria=("evaluation raises",),
        implementation="app.engines.external_integration_audit_engine:external_integration_audit_engine",
        uses_llm=False,
    ),
    # --------------------------------------------------------------- recovery
    AgentDefinition(
        id="root_cause_agent",
        category="recovery",
        title="Root Cause Agent",
        objective="Produce an evidence-backed hypothesis for why a pipeline write failed -- never a guess without evidence.",
        responsibilities=("Pattern-match the real error message and job state into a ranked list of Hypothesis, each with `evidence`",),
        limitations=("Strictly read-only -- never mutates the job or any file",),
        inputs=("job dict",),
        outputs=("RootCauseAnalysis",),
        allowed_context=("the failing job's own error/events",),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("leading hypothesis carries at least one concrete evidence string",),
        failure_criteria=("no hypothesis matches -- falls back to a low-confidence generic one, never silently empty",),
        implementation="app.engines.root_cause_investigator:root_cause_investigator",
        uses_llm=False,
    ),
    AgentDefinition(
        id="cause_validation_agent",
        category="recovery",
        title="Validation Agent (recovery tier)",
        objective="Confirm or reject the Root Cause Agent's leading hypothesis using direct, independent evidence.",
        responsibilities=("Re-read the actual flagged file content", "Re-run secret classification against it independently"),
        limitations=("Never trusts the Root Cause Agent's hypothesis without re-checking it directly",),
        inputs=("RootCauseAnalysis", "job dict", "read_artifact callback"),
        outputs=("CauseValidation (REAL_SECRET | FALSE_POSITIVE | UNSAFE_TEMPLATE | GENERATION_CONFLICT | UNKNOWN)",),
        allowed_context=("the specific flagged artifact's real content",),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("classification matches a second independent check, not just the first pass",),
        failure_criteria=("classification stays UNKNOWN with no path to resolution",),
        implementation="app.engines.cause_validator:cause_validator",
        uses_llm=False,
    ),
    AgentDefinition(
        id="repair_engineer_agent",
        category="recovery",
        title="Repair Agent (recovery tier)",
        objective="Apply the one authorized repair for a validated, confirmed cause -- and refuse to act on anything else.",
        responsibilities=("Redact the exact offending line to a self-evidently-placeholder value", "Re-run the same check as its own regression test"),
        limitations=("Raises RepairNotAuthorized unless the cause is `confirmed` and (not requiresApproval or explicitly approved)",),
        inputs=("CauseValidation", "files", "approved: bool"),
        outputs=("patched files", "RepairReport"),
        allowed_context=(),
        allowed_paths=("only the file(s) named by the validated cause",),
        forbidden_paths=("any file not named by the validated cause",),
        success_criteria=("the same check that flagged the cause no longer flags it after repair",),
        failure_criteria=("repair not authorized, or the regression check still fails after repair",),
        implementation="app.engines.repair_engineer:repair_engineer",
        uses_llm=False,
    ),
    AgentDefinition(
        id="resume_agent",
        category="recovery",
        title="Resume Agent",
        objective="Resume a paused or interrupted job from its last real checkpoint -- never restart from zero.",
        responsibilities=("Locate the last valid checkpoint", "Restart execution at that stage, same mode as originally started"),
        limitations=("Never switches a deterministic-mode job to real LLM calls on resume, or vice versa",),
        inputs=("job_id", "existing checkpoints"),
        outputs=("job resumed at the correct stage",),
        allowed_context=("the job's own checkpoints",),
        allowed_paths=(),
        forbidden_paths=("*",),
        success_criteria=("no already-completed stage re-runs",),
        failure_criteria=("no valid checkpoint exists to resume from",),
        implementation="app.engines.generation_job_engine:GenerationJobEngine.resume",
        uses_llm=False,
    ),
    # -------------------------------------------------------------- experience
    AgentDefinition(
        id="ux_agent", category="experience", title="Product UX Strategist",
        objective="Turn the ProjectSpec into a real UX strategy (personas, journeys, information hierarchy, empty states, feedback patterns) before any UI is designed or built.",
        responsibilities=("Map one journey per core_workflow", "Define domain-specific empty states (never a generic 'No data')", "Define feedback/error/success patterns"),
        limitations=("Never writes code -- output is ux-strategy.json, consumed by frontend_agent and design_agent"),
        inputs=("ProjectSpec",), outputs=("ux-strategy.json",),
        allowed_context=("ProjectSpec",), allowed_paths=("ux-strategy.json",), forbidden_paths=("*",),
        success_criteria=("ux-strategy.json parses and covers every core_workflow",),
        failure_criteria=("stage timeout, or no valid JSON emitted",),
        implementation="app.engines.agent_prompts:AGENT_PROMPTS['frontend_ux_strategy']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="design_agent", category="experience", title="Visual Design Director",
        objective="Define a visual direction specific to this product's domain (typography, palette, spacing, motion) that frontend_agent implements -- not a generic default theme.",
        responsibilities=("Justify color/typography choices against the real domain", "Explicitly name and avoid generic/template visual patterns unless a domain reason is stated"),
        limitations=("Never writes code -- output is visual-direction.json, consumed by frontend_agent"),
        inputs=("ProjectSpec", "ux-strategy.json"), outputs=("visual-direction.json",),
        allowed_context=("ProjectSpec", "ux-strategy.json"), allowed_paths=("visual-direction.json",), forbidden_paths=("*",),
        success_criteria=("visual-direction.json parses and states a rationale for any normally-forbidden generic pattern used",),
        failure_criteria=("stage timeout, or no valid JSON emitted",),
        implementation="app.engines.agent_prompts:AGENT_PROMPTS['frontend_visual_direction']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="interaction_agent", category="experience", title="Interaction Designer",
        objective="Define loading/empty/error/confirmation/optimistic-update patterns with a stated functional purpose each -- no purely decorative animation.",
        responsibilities=("Define state-by-state interaction patterns", "Require a functional purpose for every proposed transition"),
        limitations=("Never writes code -- output is interaction-spec.json, consumed by frontend_agent"),
        inputs=("ProjectSpec", "ux-strategy.json"), outputs=("interaction-spec.json",),
        allowed_context=("ProjectSpec", "ux-strategy.json"), allowed_paths=("interaction-spec.json",), forbidden_paths=("*",),
        success_criteria=("interaction-spec.json parses and every microinteraction states its purpose",),
        failure_criteria=("stage timeout, or no valid JSON emitted",),
        implementation="app.engines.agent_prompts:AGENT_PROMPTS['frontend_interaction_design']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="frontend_architecture_agent", category="architecture", title="Frontend Architect",
        objective="Define routes, layouts, state/data-fetching strategy and component organization that frontend_agent implements.",
        responsibilities=("Derive routes from core_workflows and openapi.yaml", "Define state/cache/error-handling strategy"),
        limitations=("Never writes code -- output is frontend-architecture.json, consumed by frontend_agent"),
        inputs=("ProjectSpec", "openapi.yaml"), outputs=("frontend-architecture.json",),
        allowed_context=("ProjectSpec", "openapi.yaml"), allowed_paths=("frontend-architecture.json",), forbidden_paths=("*",),
        success_criteria=("frontend-architecture.json parses and covers every route implied by openapi.yaml",),
        failure_criteria=("stage timeout, or no valid JSON emitted",),
        implementation="app.engines.agent_prompts:AGENT_PROMPTS['frontend_architecture_role']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="frontend_qa_review_agent", category="quality", title="Frontend QA Reviewer",
        objective="Answer the ten Authenticity Review questions against the REAL generated frontend output (not the spec), and list specific required fixes.",
        responsibilities=("Review real generated files, never assume from intent", "Cite file + problem for every required fix, never a vague verdict"),
        limitations=("Never rewrites code -- reports issues; repair is a separate step", "Reviews a bounded sample of generated files, not the full app (token budget)"),
        inputs=("ux-strategy.json", "visual-direction.json", "frontend-architecture.json", "interaction-spec.json", "a sample of real generated frontend files"),
        outputs=("frontend-qa-review.json",),
        allowed_context=("all four Frontend Team planning artifacts", "generated frontend file sample"),
        allowed_paths=("frontend-qa-review.json",), forbidden_paths=("*",),
        success_criteria=("frontend-qa-review.json parses with an explicit approved boolean and a specific issue list",),
        failure_criteria=("stage timeout, or no valid JSON emitted",),
        implementation="app.engines.agent_prompts:AGENT_PROMPTS['frontend_qa_review']",
        uses_llm=True,
    ),
    AgentDefinition(
        id="responsiveness_agent", category="experience", title="Responsiveness Agent",
        objective="Verify generated UI behaves correctly across real breakpoints.",
        responsibilities=(),
        limitations=(
            "No dedicated engine yet -- responsiveness is currently folded into "
            "frontend_qa_review_agent's holistic review (PARTE 7), not a standalone deterministic check",
        ),
        inputs=(), outputs=(), allowed_context=(), allowed_paths=(), forbidden_paths=("*",),
        success_criteria=(), failure_criteria=(), implementation="", uses_llm=False, status="planned",
    ),
)

_BY_ID: dict[str, AgentDefinition] = {agent.id: agent for agent in _AGENTS}


def get(agent_id: str) -> AgentDefinition | None:
    return _BY_ID.get(agent_id)


def all_agents() -> tuple[AgentDefinition, ...]:
    return _AGENTS


def by_category(category: AgentCategory) -> tuple[AgentDefinition, ...]:
    return tuple(agent for agent in _AGENTS if agent.category == category)


def active_agents() -> tuple[AgentDefinition, ...]:
    return tuple(agent for agent in _AGENTS if agent.status == "active")


def planned_agents() -> tuple[AgentDefinition, ...]:
    return tuple(agent for agent in _AGENTS if agent.status == "planned")
