import type { ArtifactType, ExecutionMode, InputType, MissionCategory, MissionGenome, MissionTypeId, SpecialistRole } from '../types';

interface CompactConfig {
  id: MissionTypeId; category: MissionCategory; title: string; description: string; complexity: number;
  steps: readonly string[]; specialists: readonly SpecialistRole[]; risks: readonly string[];
  inputs: readonly InputType[]; artifacts: readonly ArtifactType[]; modes: readonly ExecutionMode[]; action: string;
}

const titleCase = (value: string): string => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
function genome(c: CompactConfig): MissionGenome {
  return {
    id: c.id, category: c.category, title: c.title, description: c.description, icon: 'Blocks',
    estimatedTime: c.complexity >= 7 ? '45–90 min' : c.complexity >= 4 ? '20–45 min' : '10–25 min',
    complexity: c.complexity, specialists: c.specialists, executionModes: c.modes, inputTypes: c.inputs,
    steps: c.steps.map((title, index) => ({
      id: `step_${index + 1}`, title, description: `Defina e valide: ${title.toLowerCase()}.`, isRequired: index < 2,
      fields: index === 0 ? [{ id: 'objective', label: 'Objetivo', type: 'textarea', required: true, aiActions: [
        { id: 'improve', label: 'Melhorar', prompt: 'Melhore sem inventar informações: {{objective}}', insertMode: 'suggest' },
        { id: 'extract', label: 'Extrair requisitos', prompt: 'Extraia requisitos explícitos: {{objective}}', insertMode: 'suggest' },
      ] }] : [],
    })),
    conditionalSteps: [], validations: [],
    gapRules: [{ id: `${c.id}.objective`, check: (ctx) => !ctx.answers['step_1.objective'], title: 'Objetivo ainda não definido', severity: 'critical', suggestedAction: 'Defina o objetivo antes de iniciar.', relatedStepId: 'step_1' }],
    riskRules: c.risks.map((title, index) => ({ id: `${c.id}.risk_${index}`, check: () => true, severity: index ? 'medium' : 'high', category: c.category, title, description: `Risco inicial monitorado para “${c.title}”.`, suggestedAction: 'Revise as evidências e registre uma decisão.', affectedSteps: ['step_1'] })),
    artifacts: c.artifacts.map((type) => ({ type, title: titleCase(type), format: ['blueprint', 'data_model', 'api_contracts'].includes(type) ? 'json' : 'markdown' })),
    knowledgeTopics: [`${c.category}_playbook`, 'risk_checklist', 'quality_criteria'],
    primaryActionLabel: c.action, nextRoute: '/wizard/new',
  };
}

const configs: readonly CompactConfig[] = [
  { id:'agent.create', category:'create', title:'Criar agente de IA', description:'Defina objetivo, ferramentas, memória, limites e avaliação.', complexity:7, steps:['Objetivo','Contexto','Ferramentas','Memória','Guardrails','Avaliação','Entrega'], specialists:['software_architect','backend_engineer','security_engineer'], risks:['Ações autônomas sem limite','Contexto insuficiente'], inputs:['text','files','urls','schemas'], artifacts:['blueprint','prompt_md','test_plan'], modes:['guided','expert','collaborative'], action:'Iniciar criação do agente' },
  { id:'integration.create', category:'create', title:'Criar integração', description:'Modele contratos, autenticação, sincronização e falhas.', complexity:6, steps:['Sistemas','Contratos','Autenticação','Mapeamento','Falhas','Observabilidade','Entrega'], specialists:['integration_specialist','backend_engineer','security_engineer'], risks:['Contrato externo instável','Credenciais não definidas'], inputs:['text','files','urls','schemas','project_ref'], artifacts:['api_contracts','workflow','test_plan'], modes:['guided','quick','expert'], action:'Iniciar criação da integração' },
  { id:'security.audit', category:'analyze', title:'Auditar segurança', description:'Examine superfície de ataque, identidade, dados e dependências.', complexity:8, steps:['Escopo','Ativos','Identidade','Dados','Dependências','Ameaças','Evidências','Relatório'], specialists:['security_auditor','security_engineer','risk_analyst'], risks:['Escopo incompleto','Dados sem classificação'], inputs:['text','files','code','logs','urls','schemas','project_ref'], artifacts:['report','diagnosis','roadmap'], modes:['guided','analysis','expert'], action:'Iniciar auditoria de segurança' },
  { id:'data.analyze', category:'analyze', title:'Analisar dados ou documento', description:'Investigue estrutura, qualidade, padrões e evidências.', complexity:5, steps:['Pergunta','Fontes','Qualidade','Exploração','Evidências','Conclusões'], specialists:['data_analyst','risk_analyst'], risks:['Fonte sem proveniência','Amostra insuficiente'], inputs:['text','files','schemas','urls'], artifacts:['report','comparison','documentation'], modes:['guided','analysis','quick'], action:'Iniciar análise dos dados' },
  { id:'performance.analyze', category:'analyze', title:'Analisar performance', description:'Localize gargalos em código, banco, rede e infraestrutura.', complexity:7, steps:['Sintomas','Métricas','Carga','Código','Dados','Infraestrutura','Diagnóstico'], specialists:['performance_analyst','backend_engineer','database_engineer','devops_engineer'], risks:['Métricas sem baseline','Carga não representativa'], inputs:['text','code','logs','files','project_ref'], artifacts:['diagnosis','report','roadmap'], modes:['guided','analysis','expert'], action:'Iniciar análise de performance' },
  { id:'build.fix', category:'fix', title:'Corrigir build ou deploy', description:'Diagnostique falhas de compilação, pipeline ou ambiente.', complexity:5, steps:['Falha','Ambiente','Reprodução','Dependências','Pipeline','Correção','Validação'], specialists:['devops_engineer','backend_engineer','qa_engineer'], risks:['Ambiente não reproduzível','Sem teste de regressão'], inputs:['text','code','logs','files','project_ref'], artifacts:['diagnosis','deploy_plan','test_plan'], modes:['guided','analysis','expert'], action:'Iniciar correção do build' },
  { id:'security.fix', category:'fix', title:'Corrigir vulnerabilidade', description:'Planeje e valide a remediação de uma falha de segurança.', complexity:8, steps:['Vulnerabilidade','Exploração','Impacto','Contenção','Correção','Testes','Evidência'], specialists:['security_engineer','security_auditor','qa_engineer'], risks:['Quebra de compatibilidade','Exploração ainda ativa'], inputs:['text','code','logs','files','project_ref'], artifacts:['diagnosis','test_plan','report'], modes:['guided','analysis','expert'], action:'Iniciar correção de segurança' },
  { id:'performance.fix', category:'fix', title:'Corrigir performance', description:'Aplique melhoria mensurável a um gargalo confirmado.', complexity:7, steps:['Baseline','Gargalo','Hipótese','Mudança','Benchmark','Regressão'], specialists:['performance_analyst','backend_engineer','database_engineer'], risks:['Otimização sem baseline','Consistência comprometida'], inputs:['text','code','logs','project_ref'], artifacts:['diagnosis','test_plan','report'], modes:['guided','expert','collaborative'], action:'Iniciar correção de performance' },
  { id:'tech.migrate', category:'evolve', title:'Migrar tecnologia', description:'Planeje a troca de linguagem, framework, banco ou plataforma.', complexity:8, steps:['Origem','Destino','Compatibilidade','Dados','Incrementos','Rollback','Validação'], specialists:['software_architect','backend_engineer','devops_engineer','risk_analyst'], risks:['Dependências incompatíveis','Rollback não validado'], inputs:['text','files','code','schemas','project_ref'], artifacts:['migration_plan','roadmap','test_plan'], modes:['guided','expert','collaborative'], action:'Iniciar migração tecnológica' },
  { id:'code.refactor', category:'evolve', title:'Refatorar código', description:'Melhore estrutura sem alterar o comportamento.', complexity:6, steps:['Escopo','Smells','Contratos','Estratégia','Refatoração','Regressão'], specialists:['software_architect','backend_engineer','qa_engineer'], risks:['Comportamento alterado','Cobertura insuficiente'], inputs:['text','code','files','project_ref'], artifacts:['roadmap','test_plan','documentation'], modes:['guided','expert','collaborative'], action:'Iniciar refatoração' },
  { id:'system.scale', category:'evolve', title:'Escalar sistema', description:'Prepare capacidade, disponibilidade, dados e operação.', complexity:9, steps:['Demanda','Baseline','Arquitetura','Dados','Capacidade','Resiliência','Operação','Plano'], specialists:['software_architect','performance_analyst','database_engineer','devops_engineer'], risks:['Demanda sem evidência','Complexidade excessiva'], inputs:['text','logs','schemas','files','project_ref'], artifacts:['architecture','roadmap','deploy_plan'], modes:['guided','analysis','expert'], action:'Iniciar planejamento de escala' },
  { id:'sprint.plan', category:'plan', title:'Planejar sprint ou roadmap', description:'Organize objetivos, prioridades, capacidade e dependências.', complexity:4, steps:['Objetivo','Backlog','Prioridades','Capacidade','Dependências','Compromisso'], specialists:['product_strategist','risk_analyst'], risks:['Capacidade não informada','Dependência sem responsável'], inputs:['text','files','project_ref'], artifacts:['roadmap','backlog'], modes:['guided','quick','collaborative'], action:'Iniciar planejamento do roadmap' },
  { id:'infrastructure.plan', category:'plan', title:'Planejar infraestrutura', description:'Defina ambientes, capacidade, segurança e custos.', complexity:7, steps:['Requisitos','Ambientes','Topologia','Segurança','Capacidade','Observabilidade','Custos','Plano'], specialists:['devops_engineer','security_engineer','software_architect'], risks:['Carga não informada','Recuperação ausente'], inputs:['text','files','schemas','project_ref'], artifacts:['architecture','deploy_plan','roadmap'], modes:['guided','expert','collaborative'], action:'Iniciar planejamento de infraestrutura' },
  { id:'tech.research', category:'research', title:'Pesquisar tecnologia', description:'Investigue alternativas com critérios e fontes explícitas.', complexity:4, steps:['Pergunta','Critérios','Fontes','Alternativas','Evidências','Conclusão'], specialists:['software_architect','risk_analyst'], risks:['Critérios vagos','Fontes desatualizadas'], inputs:['text','urls','files'], artifacts:['report','comparison'], modes:['guided','analysis','quick'], action:'Iniciar pesquisa tecnológica' },
  { id:'solutions.compare', category:'research', title:'Comparar soluções', description:'Compare opções, trade-offs, custos e riscos.', complexity:5, steps:['Decisão','Critérios','Opções','Evidências','Trade-offs','Recomendação'], specialists:['software_architect','risk_analyst','product_strategist'], risks:['Critérios inconsistentes','Custo total ignorado'], inputs:['text','urls','files'], artifacts:['comparison','report'], modes:['guided','analysis','collaborative'], action:'Iniciar comparação de soluções' },
  { id:'feasibility.study', category:'research', title:'Estudar viabilidade', description:'Avalie viabilidade técnica, operacional e econômica.', complexity:6, steps:['Hipótese','Restrições','Técnica','Operação','Custos','Riscos','Parecer'], specialists:['software_architect','product_strategist','risk_analyst'], risks:['Premissas sem evidência','Restrição crítica ausente'], inputs:['text','files','urls','project_ref'], artifacts:['report','comparison','roadmap'], modes:['guided','analysis','collaborative'], action:'Iniciar estudo de viabilidade' },
];

export const EXPANDED_MISSION_REGISTRY: Readonly<Record<string, MissionGenome>> = Object.fromEntries(configs.map((config) => [config.id, genome(config)]));
