from __future__ import annotations

import shutil
from pathlib import Path

from app.routes import meta_factory
from app.schemas.generated_export import GeneratedProjectExportRequest
from app.services.file_protocol import EmittedFile
from app.services.project_writer import ProjectWriter


class _GitService:
    def __init__(self) -> None:
        self.pushed = False

    def status(self, user_id, provider):
        return {"status": "connected", "username": "octo", "namespaces": []}

    def create_repository(self, user_id, provider, *, namespace, repo_name, visibility, branch):
        return {
            "status": "created",
            "repo_url": f"https://example.com/{namespace}/{repo_name}",
        }

    def push_initial_commit(self, user_id, provider, *, namespace, repo_name, branch, commit_message, files):
        self.pushed = True
        assert files
        return {
            "status": "ready",
            "repo_url": f"https://example.com/{namespace}/{repo_name}",
        }


def test_generated_export_pushes_generated_folder(monkeypatch):
    writer = ProjectWriter()
    result = writer.write(
        [EmittedFile(path="README.md", content="# Test\nGenerated by LDCN OS\n")],
        project_name="export-test",
    )
    root = Path(result.root_path)
    fake_git = _GitService()
    try:
        monkeypatch.setattr(meta_factory, "git_provider_service", fake_git)
        monkeypatch.setattr(
            meta_factory._quality_engine,
            "quality_check",
            lambda project: {"security_findings": [], "passed": True, "score": 100},
        )

        response = meta_factory._export_generated_project(
            "user-1",
            {"project_id": result.project_id, "generated_project_path": result.root_path},
            "github",
            GeneratedProjectExportRequest(namespace="octo", repo_name="generated", branch="main", force=True),
        )

        assert response.status == "ready"
        assert response.file_count >= 1
        assert fake_git.pushed is True
    finally:
        shutil.rmtree(root, ignore_errors=True)
