from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

from app.engines.generated_project_quality_engine import GeneratedProjectQualityEngine
from app.services.file_protocol import EmittedFile
from app.services.project_writer import ProjectWriter
from test_backend_generation import _create_backend_project, _request


def test_env_template_in_subdir_is_not_flagged_as_real_secret_file():
    # Regression: generated projects place .env.example in subdirs (backend/, frontend/).
    # Those are mandatory templates, not real secret files, so they must NOT trip the
    # critical real_env_or_secret_file finding (which would block git export with 409).
    engine = GeneratedProjectQualityEngine()
    root = Path(tempfile.mkdtemp())
    try:
        (root / "backend").mkdir()
        (root / "backend" / ".env.example").write_text(
            "DB_PASSWORD=change-me\nJWT_SECRET=placeholder\n", encoding="utf-8"
        )
        findings: list[dict] = []
        engine._scan_secret_file(root, root / "backend" / ".env.example", findings)
        engine._scan_secret_content(root, root / "backend" / ".env.example", findings)
        assert findings == []

        # A REAL .env (not a template) in a subdir is still a critical finding.
        (root / "backend" / ".env").write_text("X=y", encoding="utf-8")
        real: list[dict] = []
        engine._scan_secret_file(root, root / "backend" / ".env", real)
        assert any(f["code"] == "real_env_or_secret_file" and f["severity"] == "critical" for f in real)
    finally:
        shutil.rmtree(root, ignore_errors=True)


def _expo_project() -> tuple[dict, Path]:
    manifest = '{"framework":"expo","deterministic":true,"no_ai":true,"no_agents":true,"no_shell_execution":true,"no_external_access":true}'
    files = [
        EmittedFile(".ldcn-backend-generation.json", manifest),
        EmittedFile("README.md", "# Mobile\n\nGenerated by LDCN OS. Run with npm run start."),
        EmittedFile("apps/mobile/app.json", '{"expo":{"name":"Mobile","slug":"mobile"}}'),
        EmittedFile("apps/mobile/package.json", '{"scripts":{"build":"tsc --noEmit"}}'),
        EmittedFile("apps/mobile/tsconfig.json", '{"compilerOptions":{"strict":true}}'),
        EmittedFile("apps/mobile/App.tsx", "export default function App() { return null; }"),
        EmittedFile("apps/mobile/src/api/client.ts", "export const api = {};"),
        EmittedFile("apps/mobile/src/screens/Home.tsx", "export const Home = () => null;"),
        EmittedFile("apps/mobile/src/navigation/index.ts", "export const navigation = {};"),
        EmittedFile("apps/mobile/tests/app.test.ts", "export {};"),
        EmittedFile("apps/mobile/README.md", "# Mobile\n\nRun with npm run start."),
        EmittedFile("apps/mobile/.env.example", "EXPO_PUBLIC_API_URL=http://localhost:8000"),
        EmittedFile("apps/mobile/.gitignore", "node_modules/\nios/\nandroid/\n"),
    ]
    result = ProjectWriter().write(files, project_name="expo-quality")
    return {"project_id": result.project_id, "generated_project_path": result.root_path}, Path(result.root_path)


def test_expo_quality_gate_accepts_complete_mobile_structure():
    project, root = _expo_project()
    try:
        payload = GeneratedProjectQualityEngine().quality_check(project)
        assert payload["passed"] is True
        assert payload["framework"] == "expo"
        assert any(check["id"] == "expo_api_client" and check["status"] == "passed" for check in payload["checks"])
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_expo_quality_gate_blocks_incomplete_scaffold():
    project, root = _expo_project()
    try:
        (root / "apps/mobile/app.json").unlink()
        payload = GeneratedProjectQualityEngine().quality_check(project)
        assert payload["passed"] is False
        assert "apps/mobile/app.json" in payload["missing_files"]
    finally:
        shutil.rmtree(root, ignore_errors=True)


def _generate_backend(client, framework_id: str, *, profile_id: str | None = None) -> tuple[dict, Path]:
    project = _create_backend_project(client, framework_id)
    output = Path("generated-projects") / "active" / f"quality-{framework_id}-{project['project_id']}"
    response = client.post("/api/backend-generation/run", json=_request(project, framework_id, output, profile_id=profile_id))
    assert response.status_code == 200
    manifest = response.json()
    assert manifest["status"] == "generated"
    return project, Path(manifest["output_path"])


def test_fastapi_quality_pass(client):
    project, _ = _generate_backend(client, "fastapi", profile_id="crud_api")

    response = client.post(f"/api/generated-projects/{project['project_id']}/quality-check")

    assert response.status_code == 200
    payload = response.json()
    assert payload["passed"] is True
    assert payload["failed"] is False
    assert payload["framework"] == "fastapi"
    assert payload["score"] >= 90
    assert payload["missing_files"] == []
    assert payload["security_findings"] == []
    assert any(item["id"] == "fastapi_crud_schemas" and item["status"] == "passed" for item in payload["checks"])


def test_spring_boot_quality_pass(client):
    project, _ = _generate_backend(client, "spring_boot", profile_id="basic_rest_api")

    response = client.post(f"/api/generated-projects/{project['project_id']}/quality-check")

    assert response.status_code == 200
    payload = response.json()
    assert payload["passed"] is True
    assert payload["framework"] == "spring_boot"
    assert payload["missing_files"] == []
    assert any(item["id"] == "spring_pom" and item["status"] == "passed" for item in payload["checks"])


def test_nestjs_quality_pass(client):
    project, _ = _generate_backend(client, "nestjs", profile_id="basic_api")

    response = client.post(f"/api/generated-projects/{project['project_id']}/quality-check")

    assert response.status_code == 200
    payload = response.json()
    assert payload["passed"] is True
    assert payload["framework"] == "nestjs"
    assert payload["missing_files"] == []
    assert any(item["id"] == "nestjs_package" and item["status"] == "passed" for item in payload["checks"])


def test_missing_file_fails_quality_gate(client):
    project, root = _generate_backend(client, "fastapi", profile_id="crud_api")
    (root / "requirements.txt").unlink()

    response = client.post(f"/api/generated-projects/{project['project_id']}/quality-check")

    assert response.status_code == 200
    payload = response.json()
    assert payload["passed"] is False
    assert payload["failed"] is True
    assert "requirements.txt" in payload["missing_files"]
    assert any(item["id"] == "fastapi_requirements" and item["status"] == "failed" for item in payload["checks"])


def test_secret_detection_fails_quality_gate(client):
    project, root = _generate_backend(client, "fastapi", profile_id="crud_api")
    secret_path = root / "app" / "core" / "secrets.py"
    secret_path.write_text('API_KEY = "sk_live_real_secret_value_12345"\n', encoding="utf-8")

    response = client.post(f"/api/generated-projects/{project['project_id']}/quality-check")

    assert response.status_code == 200
    payload = response.json()
    assert payload["passed"] is False
    assert payload["failed"] is True
    assert any(item["code"] == "hardcoded_secret" for item in payload["security_findings"])
