from __future__ import annotations

from app.services.localization_service import LocalizationService
from app.services.template_render_service import TemplateRenderService

def test_locales_list(client):
    response = client.get("/api/localization/locales")
    assert response.status_code == 200
    assert {item["code"] for item in response.json()} == {"pt-BR", "en-US", "es-ES", "fr-FR"}


def test_dictionary_by_locale(client):
    response = client.get("/api/localization/dictionary/pt-BR")
    assert response.status_code == 200
    assert response.json()["entries"]["ldcn.observing"] == "LDCN observando"


def test_preview_uses_fallback(client):
    response = client.post(
        "/api/localization/preview",
        json={"locale": "pt-BR", "key": "generation.summary", "values": {"project": "Atlas"}},
    )
    assert response.status_code == 200
    assert "Atlas" in response.json()["text"]


def test_validate_missing_keys(client):
    response = client.post(
        "/api/localization/validate",
        json={"locale": "fr-FR", "required_keys": ["ldcn.observing", "missing.key"]},
    )
    assert response.status_code == 200
    assert response.json()["valid"] is False
    assert response.json()["missing_keys"] == ["missing.key"]


def test_blueprint_contains_generated_project_locale_profile(client):
    response = client.post(
        "/api/blueprints/preview",
        json={
            "project_name": "localized-project",
            "language_id": "typescript",
            "runtime_id": "nodejs",
            "framework_id": "nextjs",
            "architecture_id": "modular_monolith",
            "archetype_id": "landing_page",
            "capability_ids": ["i18n"],
            "business_module_ids": [],
            "endpoint_ids": [],
            "infrastructure_component_ids": [],
            "locale": "fr-FR",
            "generation_mode": "local_build_90",
        },
    )
    assert response.status_code == 200
    assert response.json()["locale_profile"]["generated_readme_locale"] == "fr-FR"


def test_readme_template_changes_language_and_falls_back_safely():
    localization = LocalizationService()
    renderer = TemplateRenderService()
    base = {
        "project": {"name": "Atlas"},
        "scope": {"capability_list": "- seo", "module_list": "- content", "endpoint_list": "- none"},
    }
    pt_files = renderer.render_template("landing-page", {**base, "i18n": localization.dictionary("pt-BR")["entries"]})
    en_files = renderer.render_template("landing-page", {**base, "i18n": localization.dictionary("en-US")["entries"]})
    pt_readme = next(item["content"] for item in pt_files if item["relative_path"] == "README.md")
    en_readme = next(item["content"] for item in en_files if item["relative_path"] == "README.md")
    assert "Gerado pelo Motor" in pt_readme
    assert "Generated by LDCN OS" in en_readme
    assert pt_readme != en_readme
