from __future__ import annotations

import shutil
from pathlib import Path
from uuid import uuid4

import pytest

from app.core.config import BASE_DIR
from app.engines.documentation_engine import DocumentationEngine
from test_backend_generation import _create_backend_project, _request

WORKSPACE_ROOT = BASE_DIR.parents[1]
ACTIVE_DIR = WORKSPACE_ROOT / "generated-projects" / "active"

GOOD_DOCS = {
    "README.md": "# Service\n\nGenerated by LDCN OS. This service exposes a governed REST API for operators and consumers with clear setup steps.",
    "ARCHITECTURE.md": "# Architecture\n\nA modular monolith with an application layer, domain services, and a persistence boundary. Requests flow through routers into services.",
    "API.md": "# API\n\nThe API exposes resource endpoints with request and response examples, authentication notes, and standard error envelopes.",
    "DATABASE.md": "# Database\n\nThe data model stores accounts and records with constraints and indexes. Migrations are applied before the service starts.",
    "SECURITY.md": "# Security\n\nInput is validated, secrets stay in environment variables, and access is scoped per role. No credentials are stored in source.",
    "TESTING.md": "# Testing\n\nUnit and integration tests cover the service and persistence layers. Run the suite before every release to keep coverage high.",
    "DEPLOYMENT.md": "# Deployment\n\nThe service ships as a process behind a reverse proxy. Environment variables configure runtime; rollback restores the prior release.",
}


def _make_project_dir(docs: dict[str, str], extra: dict[str, str] | None = None) -> Path:
    root = ACTIVE_DIR / f"doctest-{uuid4().hex}"
    root.mkdir(parents=True, exist_ok=True)
    (root / ".ldcn-generation.json").write_text("{}", encoding="utf-8")
    for name, content in docs.items():
        target = root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    for name, content in (extra or {}).items():
        target = root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return root


def _project(root: Path) -> dict:
    return {
        "project_id": f"doc-{root.name}",
        "project_name": "Documentation Demo",
        "generated_project_path": str(root),
    }


@pytest.fixture
def engine() -> DocumentationEngine:
    return DocumentationEngine()


def test_analyze_scores_complete_documentation(engine):
    root = _make_project_dir(GOOD_DOCS)
    try:
        result = engine.analyze(_project(root))
        assert result["safe"] is True
        assert result["missing_required"] == []
        assert result["score"] >= 90
        completeness = next(c for c in result["checks"] if c["id"] == "completeness")
        assert completeness["status"] == "passed"
        readme = next(d for d in result["docs"] if d["id"] == "readme")
        assert readme["present"] is True
        assert readme["status"] == "validated"
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_missing_required_doc_is_detected(engine):
    docs = dict(GOOD_DOCS)
    del docs["ARCHITECTURE.md"]
    root = _make_project_dir(docs)
    try:
        result = engine.analyze(_project(root))
        assert "ARCHITECTURE.md" in result["missing_required"]
        architecture = next(d for d in result["docs"] if d["id"] == "architecture")
        assert architecture["status"] == "missing"
        assert result["score"] < 90
        completeness = next(c for c in result["checks"] if c["id"] == "completeness")
        assert completeness["status"] == "warning"
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_secret_in_doc_is_flagged_unsafe(engine):
    docs = dict(GOOD_DOCS)
    docs["SECURITY.md"] = "# Security\n\nUse this in production: api_key = 'sk_test_0000000000000000000000' for the gateway."
    root = _make_project_dir(docs)
    try:
        result = engine.analyze(_project(root))
        assert result["safe"] is False
        security = next(d for d in result["docs"] if d["id"] == "security")
        assert security["status"] == "unsafe"
        assert any(f["code"] == "exposed_secret" for f in result["findings"])
        security_check = next(c for c in result["checks"] if c["id"] == "security")
        assert security_check["status"] == "failed"
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_inconsistency_between_doc_and_project(engine):
    docs = dict(GOOD_DOCS)
    docs["DATABASE.md"] = "# Database\n\nThe service stores all records in a managed PostgreSQL cluster with read replicas and automated backups enabled."
    root = _make_project_dir(docs)  # no postgres anywhere in the project
    try:
        result = engine.analyze(_project(root))
        database = next(d for d in result["docs"] if d["id"] == "database")
        assert database["status"] == "inconsistent"
        consistency = next(c for c in result["checks"] if c["id"] == "consistency")
        assert consistency["status"] == "warning"
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_postgres_mention_is_consistent_when_project_uses_postgres(engine):
    docs = dict(GOOD_DOCS)
    docs["DATABASE.md"] = "# Database\n\nThe service stores all records in a managed PostgreSQL cluster with constraints, indexes, and backups."
    root = _make_project_dir(docs, extra={"requirements.txt": "fastapi\npsycopg[binary]\npostgres\n"})
    try:
        result = engine.analyze(_project(root))
        database = next(d for d in result["docs"] if d["id"] == "database")
        assert database["status"] == "validated"
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_postgres_mention_is_consistent_for_go_and_dotnet_manifests(engine):
    for extra in [
        {"go.mod": "module example.com/app\n\nrequire github.com/jackc/pgx/v5 v5.5.0\n"},
        {"Api.csproj": '<Project><ItemGroup><PackageReference Include="Npgsql" Version="8.0.0" /></ItemGroup></Project>'},
    ]:
        docs = dict(GOOD_DOCS)
        docs["DATABASE.md"] = "# Database\n\nThe service persists its entities in PostgreSQL with migrations applied at startup."
        root = _make_project_dir(docs, extra=extra)
        try:
            result = engine.analyze(_project(root))
            database = next(doc for doc in result["docs"] if doc["id"] == "database")
            assert database["status"] == "validated", (extra, database["issues"])
        finally:
            shutil.rmtree(root, ignore_errors=True)


def test_placeholder_marks_doc_as_draft(engine):
    docs = dict(GOOD_DOCS)
    docs["TESTING.md"] = "# Testing\n\nTODO: describe the unit and integration test strategy for the service before the next release ships."
    root = _make_project_dir(docs)
    try:
        result = engine.analyze(_project(root))
        testing = next(d for d in result["docs"] if d["id"] == "testing")
        assert testing["status"] == "draft"
        quality = next(c for c in result["checks"] if c["id"] == "quality")
        assert quality["status"] == "warning"
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_export_copies_to_docs_by_default_without_moving(engine):
    root = _make_project_dir(GOOD_DOCS)
    try:
        result = engine.export(_project(root))
        assert result["exported"] is True
        assert result["blocked"] is False
        assert result["organized"] is False
        assert (root / "README.md").is_file()  # README stays at the root
        assert (root / "docs" / "ARCHITECTURE.md").is_file()
        assert (root / "docs" / "INDEX.md").is_file()
        assert (root / "ARCHITECTURE.md").exists()  # original kept (copy, not move)
        assert "docs/INDEX.md" in result["exported_paths"]
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_export_organize_moves_originals(engine):
    root = _make_project_dir(GOOD_DOCS)
    try:
        result = engine.export(_project(root), organize=True)
        assert result["exported"] is True
        assert result["organized"] is True
        assert (root / "README.md").is_file()  # README still stays at the root
        assert (root / "docs" / "ARCHITECTURE.md").is_file()
        assert not (root / "ARCHITECTURE.md").exists()  # moved when organizing
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_export_blocked_when_documentation_unsafe(engine):
    docs = dict(GOOD_DOCS)
    docs["SECURITY.md"] = "# Security\n\npassword = 'SuperSecretValue12345' is required for the admin console to start."
    root = _make_project_dir(docs)
    try:
        result = engine.export(_project(root))
        assert result["exported"] is False
        assert result["blocked"] is True
        assert "secret" in (result["reason"] or "").lower()
        assert not (root / "docs").exists()
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_export_blocked_when_required_doc_missing(engine):
    docs = dict(GOOD_DOCS)
    del docs["API.md"]
    root = _make_project_dir(docs)
    try:
        result = engine.export(_project(root))
        assert result["exported"] is False
        assert result["blocked"] is True
        assert "API.md" in (result["reason"] or "")
    finally:
        shutil.rmtree(root, ignore_errors=True)


def test_documentation_endpoint_returns_real_library(client):
    project = _create_backend_project(client, "fastapi")
    output = Path("generated-projects") / "active" / f"doc-fastapi-{project['project_id']}"
    run = client.post("/api/backend-generation/run", json=_request(project, "fastapi", output, profile_id="crud_api"))
    assert run.status_code == 200

    response = client.get(f"/api/projects/{project['project_id']}/documentation")
    assert response.status_code == 200
    payload = response.json()
    assert payload["project_id"] == project["project_id"]
    assert isinstance(payload["score"], int)
    assert payload["required_count"] == 7
    readme = next(d for d in payload["docs"] if d["id"] == "readme")
    assert readme["present"] is True
