import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, CheckCircle2, Loader2, X } from 'lucide-react';
import { useActiveLlm } from '@/hooks/use-active-llm';
import type { InputType, MissionGenome, SpecialistRole } from '../../types';
import { artifactStatus, stepsForMode, useWorkspaceDraftStore } from '../../stores/workspaceDraftStore';
import { inputMeta, specialistMeta } from './config';
import styles from '../MissionSelector.module.css';

export function MissionDetailsDrawer({ genome }: { genome: MissionGenome }) {
  const detail=useWorkspaceDraftStore((s)=>s.detail); const close=useWorkspaceDraftStore((s)=>s.closeDetail); const objective=useWorkspaceDraftStore((s)=>s.objective); const setObjective=useWorkspaceDraftStore((s)=>s.setObjective); const inputValues=useWorkspaceDraftStore((s)=>s.inputValues); const setInput=useWorkspaceDraftStore((s)=>s.setInputValue); const addFiles=useWorkspaceDraftStore((s)=>s.addFiles); const files=useWorkspaceDraftStore((s)=>s.files); const currentStepId=useWorkspaceDraftStore((s)=>s.currentStepId); const mode=useWorkspaceDraftStore((s)=>s.executionMode); const go=useWorkspaceDraftStore((s)=>s.goToStep); const active=useWorkspaceDraftStore((s)=>s.activeSpecialists); const pendingRemoval=useWorkspaceDraftStore((s)=>s.pendingSpecialistRemoval); const confirmRemoval=useWorkspaceDraftStore((s)=>s.confirmSpecialistRemoval); const resolveRisk=useWorkspaceDraftStore((s)=>s.resolveRisk); const viewed=useWorkspaceDraftStore((s)=>s.viewedArtifacts); const assistant=useWorkspaceDraftStore((s)=>s.assistantDraft); const acceptAssistant=useWorkspaceDraftStore((s)=>s.acceptAssistant); const rejectAssistant=useWorkspaceDraftStore((s)=>s.rejectAssistant); const llm=useActiveLlm();
  const closeRef=useRef<HTMLButtonElement>(null); const drawerRef=useRef<HTMLElement>(null); const priorFocus=useRef<HTMLElement|null>(null); const [draftObjective,setDraftObjective]=useState(objective); const [inputError,setInputError]=useState<string|null>(null);
  useEffect(()=>{if(!detail)return;priorFocus.current=document.activeElement as HTMLElement;setDraftObjective(objective);closeRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){close();return;}if(event.key!=='Tab'||!drawerRef.current)return;const focusable=Array.from(drawerRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [href]'));if(!focusable.length)return;const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);priorFocus.current?.focus();};},[close,detail,objective]);
  if(!detail)return null;
  const title=detail.kind==='objective'?'Definir objetivo':detail.kind==='step'?'Detalhes da etapa':detail.kind==='specialist'?'Especialista':detail.kind==='risk'?'Detalhes do risco':detail.kind==='input'?'Entrada de contexto':detail.kind==='artifact'?'Entregável':detail.kind==='assistant'?'Sugestão da IA':'Conectar IA';
  function saveObjective(){if(!draftObjective.trim()){setInputError('Descreva o resultado esperado.');return;}setObjective(draftObjective);close();}
  return <div className={styles.drawerScrim} onMouseDown={(e)=>{if(e.target===e.currentTarget)close();}}><aside ref={drawerRef} className={styles.drawer} role="dialog" aria-modal="true" aria-labelledby="mission-detail-title"><header><div><p>MISSION WORKSPACE</p><h2 id="mission-detail-title">{title}</h2></div><button ref={closeRef} type="button" onClick={close} aria-label="Fechar painel"><X aria-hidden="true"/></button></header><div className={styles.drawerBody}>
    {detail.kind==='objective'?<><label htmlFor="mission-objective">Objetivo da missão</label><textarea id="mission-objective" value={draftObjective} onChange={(e)=>{setDraftObjective(e.target.value);setInputError(null);}} rows={8} placeholder="Descreva o resultado, o contexto e os limites conhecidos." autoFocus/><p className={styles.helper}>Não inventaremos informações ausentes; elas serão marcadas como pendentes.</p>{inputError?<p role="alert" className={styles.drawerError}>{inputError}</p>:null}<button type="button" className={styles.drawerPrimary} onClick={saveObjective}>Salvar objetivo</button></>:null}
    {detail.kind==='input'?<InputEditor source={detail.id as InputType} value={inputValues[detail.id as InputType]??''} files={files} onChange={(value)=>setInput(detail.id as InputType,value)} onFiles={addFiles} onClose={close}/>:null}
    {detail.kind==='step'?<StepDetail genome={genome} id={detail.id} mode={mode} current={currentStepId} onGo={go}/>:null}
    {detail.kind==='specialist'?<SpecialistDetail role={detail.id as SpecialistRole} active={active.includes(detail.id as SpecialistRole)} required={genome.specialists[0]===detail.id} pending={pendingRemoval===detail.id} onConfirm={confirmRemoval}/>:null}
    {detail.kind==='risk'?<RiskDetail genome={genome} id={detail.id} onResolve={resolveRisk}/>:null}
    {detail.kind==='artifact'?<ArtifactDetail genome={genome} type={detail.id} status={artifactStatus(detail.id??'',viewed)}/>:null}
    {detail.kind==='assistant'?<AssistantDetail draft={assistant} onAccept={acceptAssistant} onReject={rejectAssistant}/>:null}
    {detail.kind==='ai-required'?<div className={styles.detailStack}><AlertTriangle/><h3>Provider de IA necessário</h3><p>Este modo usa assistência de IA. Conecte e valide sua própria API key; nenhuma chave global será usada.</p><button type="button" className={styles.drawerPrimary} onClick={()=>llm.openProviderSettings()}>Conectar IA</button></div>:null}
  </div></aside></div>;
}

function InputEditor({source,value,files,onChange,onFiles,onClose}:{source:InputType;value:string;files:readonly {name:string;size:number}[];onChange:(value:string)=>void;onFiles:(files:FileList)=>void;onClose:()=>void}) { const meta=inputMeta[source]; const isUrl=source==='urls'; if(source==='files')return <><label htmlFor="context-files">Arquivos do contexto</label><input id="context-files" type="file" multiple accept=".txt,.md,.json,.yaml,.yml,.sql,.prisma,.log,.pdf" onChange={(e)=>e.target.files&&onFiles(e.target.files)}/><p className={styles.helper}>TXT, Markdown, JSON, YAML, SQL, Prisma, logs e PDF.</p><ul className={styles.fileList}>{files.map((file)=><li key={`${file.name}-${file.size}`}>{file.name} <small>{Math.ceil(file.size/1024)} KB</small></li>)}</ul><button type="button" className={styles.drawerPrimary} onClick={onClose}>Concluir</button></>; return <><label htmlFor={`context-${source}`}>{meta.label}</label>{source==='project_ref'||isUrl?<input id={`context-${source}`} type={isUrl?'url':'text'} value={value} onChange={(e)=>onChange(e.target.value)} placeholder={isUrl?'https://github.com/organização/repositório':'ID ou nome do projeto'}/>:<textarea id={`context-${source}`} value={value} onChange={(e)=>onChange(e.target.value)} rows={10} placeholder={source==='schemas'?'Cole SQL, JSON ou schema Prisma.':meta.description}/>}<p className={styles.helper}>{meta.description}</p><button type="button" className={styles.drawerPrimary} onClick={onClose}>Salvar entrada</button></>; }
function StepDetail({genome,id,mode,current,onGo}:{genome:MissionGenome;id?:string;mode:string;current:string;onGo:(id:string)=>unknown}) { const steps=stepsForMode(genome.id,mode as never);const index=steps.findIndex((s)=>s.id===id);const step=steps[index];const currentIndex=steps.findIndex((s)=>s.id===current);const blocked=index>currentIndex+1;if(!step)return <p>Etapa não encontrada.</p>;return <div className={styles.detailStack}>{blocked?<AlertTriangle/>:<CheckCircle2/>}<h3>{step.title}</h3><p>{step.description}</p><dl><div><dt>Status</dt><dd>{blocked?'Bloqueada':id===current?'Ativa':index<currentIndex?'Concluída':'Disponível'}</dd></div><div><dt>Dependências</dt><dd>{step.dependsOn?.join(', ')||steps[index-1]?.title||'Nenhuma'}</dd></div></dl>{blocked?<p>Conclua “{steps[currentIndex]?.title}” para liberar esta etapa.</p>:<button type="button" className={styles.drawerPrimary} onClick={()=>onGo(step.id)}>Abrir etapa</button>}</div>; }
function SpecialistDetail({role,active,required,pending,onConfirm}:{role:SpecialistRole;active:boolean;required:boolean;pending:boolean;onConfirm:()=>void}) { const meta=specialistMeta[role]??{label:role,tone:'slate',responsibilities:[]};return <div className={styles.detailStack}><h3>{meta.label}</h3><p>{active?'Ativo nesta missão.':'Inativo nesta missão.'} {required?'É o especialista líder e sua remoção afeta validações.':''}</p><h4>Responsável por</h4><ul>{meta.responsibilities.map((item)=><li key={item}>{item}</li>)}</ul>{pending?<button type="button" className={styles.dangerAction} onClick={onConfirm}>Confirmar remoção e assumir impacto</button>:null}</div>; }
function RiskDetail({genome,id,onResolve}:{genome:MissionGenome;id?:string;onResolve:(id:string,value:'reviewed'|'accepted')=>void}) { const rule=[...genome.riskRules,...genome.gapRules].find((item)=>item.id===id);if(!rule)return <p>Risco não encontrado.</p>;const affectedStep='relatedStepId'in rule?rule.relatedStepId:('affectedSteps'in rule?rule.affectedSteps?.join(', '):undefined);return <div className={styles.detailStack}><AlertTriangle/><h3>{rule.title}</h3><dl><div><dt>Severidade</dt><dd>{rule.severity}</dd></div><div><dt>Missão</dt><dd>{genome.title}</dd></div><div><dt>Etapa afetada</dt><dd>{affectedStep||'Análise contínua'}</dd></div></dl><p>{rule.description}</p><h4>Recomendação</h4><p>{rule.suggestedAction}</p><div className={styles.drawerActions}><button type="button" onClick={()=>id&&onResolve(id,'reviewed')}>Revisar etapa relacionada</button><button type="button" onClick={()=>id&&onResolve(id,'accepted')}>Manter com justificativa</button></div></div>; }
function ArtifactDetail({genome,type,status}:{genome:MissionGenome;type?:string;status:string}) { const artifact=genome.artifacts.find((item)=>item.type===type);if(!artifact)return <p>Entregável não encontrado.</p>;return <div className={styles.detailStack}><h3>{artifact.title}</h3><dl><div><dt>Status</dt><dd>{status==='not_started'?'Ainda não iniciado':'Prévia consultada'}</dd></div><div><dt>Formato</dt><dd>{artifact.format}</dd></div><div><dt>Quando será gerado</dt><dd>Após validação da jornada</dd></div><div><dt>Dependências</dt><dd>{genome.steps.filter((step)=>step.isRequired).map((step)=>step.title).join(', ')||genome.steps.slice(0,2).map((step)=>step.title).join(', ')}</dd></div></dl><p>Este artefato será construído somente com decisões aceitas e contexto persistido.</p></div>; }
function AssistantDetail({draft,onAccept,onReject}:{draft:ReturnType<typeof useWorkspaceDraftStore.getState>['assistantDraft'];onAccept:()=>void;onReject:()=>void}) { if(!draft)return <p>Selecione uma ação de assistência.</p>;if(draft.loading)return <div className={styles.detailStack}><Loader2 className={styles.spinner}/><h3>Executando {draft.actionLabel}</h3><p>A chamada usa exclusivamente sua API key validada.</p></div>;if(draft.error)return <div className={styles.detailStack}><AlertTriangle/><h3>A ação não foi concluída</h3><p role="alert">{draft.error}</p><button type="button" onClick={onReject}>Fechar</button></div>;return <div className={styles.detailStack}><h3>{draft.actionLabel}</h3><div className={styles.comparison}><section><h4>Atual</h4><pre>{draft.current||'Vazio'}</pre></section><section><h4>Sugestão</h4><pre>{draft.proposed}</pre></section></div><h4>Por quê</h4><p>{draft.reason}</p><h4>Impacto</h4><p>Aceitar registra uma decisão e atualiza os painéis dependentes.</p><div className={styles.drawerActions}><button type="button" onClick={onReject}>Rejeitar</button><button type="button" onClick={onAccept}>Aceitar</button></div></div>; }
