import type { Guide } from '../types';

/* Areas “Verify & ship”, “Library & studios” and “Your work & account”. */
export const GUIDES_B: readonly Guide[] = [
  {
    id: 'runtime', area: 'ship', title: 'Preview and staging',
    summary: 'Run the generated system, look inside it, and put it on staging with a way back.',
    screens: [{ id: 'P-RUN', label: 'Runtime Control Room', current: '/projects' }],
    what: 'The Runtime Control Room starts a live preview of the generated project, shows the console and errors of what is running, and deploys a version to staging with a health check and rollback.',
    why: 'A project you cannot run is a project you cannot judge. Seeing it run — errors included — before delivery is part of the proof.',
    how: ['Start the preview: the project’s frontend and backend start in isolation.', 'Use the app in the preview and watch the console and errors panel.', 'Take a screenshot, or restart one side, when needed.', 'Deploy to staging; its health check shows whether the version answers, and rollback returns to the previous one.'],
    give: 'A generated project on a supported stack.',
    get: 'A running preview, console output, screenshots, and a staged version with its health.',
    limits: ['Preview and staging support Python/FastAPI with Next.js/React and PostgreSQL today.', 'An idle preview is stopped automatically.', 'The screen shows only the parts the backend reports — never an invented database, latency or restart count.'],
    good: ['Preview after every mission that ends READY, before delivering.', 'Keep the console panel open while you try the main flow.'],
    trouble: [['The preview stopped by itself', 'Previews stop after a period without activity. Start it again.'], ['Staging failed its health check', 'Open the staging logs to see which service did not answer, and roll back if a previous version exists.']],
    api: ['GET /api/live-preview/{session_id}/console', 'POST /api/live-preview/{session_id}/screenshot'],
    terms: ['Preview', 'Runtime', 'Deploy'],
  },
  {
    id: 'evidence', area: 'ship', title: 'Evidence: why is it READY?',
    summary: 'Follow any verdict back to the facts that produced it.',
    screens: [{ id: 'P-EVD', label: 'Evidence Graph', current: '/meta-factory' }, { id: 'P-GOV', label: 'Governance', current: '/meta-factory' }],
    what: 'Every verdict on a project — kernel phase, product certification, quality gate, chief verification, delivery eligibility — is linked to the records behind it. The evidence graph walks from a requirement to the command that proved it.',
    why: 'A READY without its proof is a claim. The platform’s promise is that you can check every claim yourself.',
    how: ['Pick a verdict and ask why.', 'Follow the path: the requirement, the job that implemented it, the agent execution, the files written, the gates and the test session.', 'Open any node to read its record — who, when, result, exit code.', 'Governance shows whether the run stayed within scope, the prompt lock and the approved stack.'],
    give: 'A project with at least one mission.',
    get: 'The chain of evidence behind each verdict, and the audit of the orchestration.',
    limits: ['Verdicts are never averaged into one score; each keeps its own source.', 'A job’s mandatory gates arrive with its live stream (gap G2).'],
    good: ['Before delivering, follow one requirement end to end once.', 'When a verdict surprises you, read its evidence before anything else.'],
    trouble: [['A node has no evidence', 'The step recorded no proof. It shows as Unknown or Not executed — never as proven.']],
    api: ['GET /api/test-room/{project_id}/proof', 'GET /api/companies/by-job/{job_id}/chief', 'GET /api/chief-orchestrator/{project_id}/audit-log'],
    terms: ['Evidence', 'Gate', 'READY'],
  },
  {
    id: 'delivery', area: 'ship', title: 'Delivering a project',
    summary: 'When a project may ship, how you receive it, and what exactly you get.',
    screens: [{ id: 'P-DLV', label: 'Delivery Center', current: '/meta-factory' }, { id: 'A-GIT', label: 'Integrations', current: '/settings' }],
    what: 'The Delivery Center says whether a project is eligible to ship and offers only the options the backend allows: download a ZIP, export to a Git repository, or keep it in LDCN OS.',
    why: 'Delivery is when a project leaves the platform. A person decides it, and only after the gates allow it.',
    how: ['Check eligibility: anything that blocks delivery is listed first, with its reason.', 'Choose the delivery mode.', 'For Git, pick a connected provider and repository; the export reports its progress.', 'The delivery is recorded with its mode and time.'],
    give: 'A mission that ended READY, and your decision on how to receive it.',
    get: 'A ZIP, a Git export or a project kept in the platform — with the evidence that allowed it.',
    limits: ['Eligibility fails closed: what cannot be verified keeps delivery blocked.', 'Git export needs a connected provider in Integrations.', 'Only real options are offered; there is no managed cloud hosting option.'],
    good: ['Read the eligibility reasons even when delivery is allowed.', 'Connect your Git provider before the mission ends.'],
    trouble: [['Delivery is blocked', 'Open the listed reason: it names the gate or check that failed, with its evidence.'], ['The Git export failed', 'Check the provider connection and the repository permission in Integrations, then export again.']],
    api: ['GET /api/meta-factory/{project_id}/delivery', 'POST /api/git/export/github', 'GET /api/git/export/status/{export_id}'],
    terms: ['Deploy', 'Gate'],
  },
  {
    id: 'memory', area: 'ship', from: 'documentation', title: 'Project memory and documentation',
    summary: 'What the platform believes about your project, and documentation that matches what was built.',
    screens: [{ id: 'P-MEM', label: 'Project Memory & Docs', current: '/documentation' }],
    what: 'Project memory holds the facts the platform recorded about a project and reads in later steps. The documentation library scores the documents against what was actually built, and an AI writer drafts the sections that are missing.',
    why: 'Documentation that does not match the code is worse than none, and a memory that is no longer true misleads every step that reads it.',
    how: ['Read what the platform remembers about the project.', 'Correct a memory that is wrong, or delete one that no longer applies.', 'Check the documentation score and the sections marked missing.', 'Ask the AI writer for what is missing, then export the documentation.'],
    give: 'A project with generated files.',
    get: 'Corrected memories, and scored documentation you can export.',
    who: ['AI Writer — writes from the project’s real files'],
    files: ['Exportable documents'],
    limits: ['The score reflects what exists in the project; nothing that was not built gets documented.', 'Memories belong to their project; what teams learn lives in the Library.'],
    good: ['Ask the writer only for what is missing instead of regenerating everything.', 'Review the memories after a large change.'],
    trouble: [['The documentation score is low', 'Open the sections marked missing and ask the AI writer to fill them.']],
    faq: [['Does the AI writer invent content?', 'No. It writes from the project’s real generated files.']],
    api: ['GET /api/project-rooms/{room_id}/memories', 'GET /api/projects/{project_id}/documentation', 'POST /api/projects/{project_id}/documentation/generate', 'POST /api/projects/{project_id}/documentation/export'],
    terms: ['Memória', 'Contexto'],
  },
  {
    id: 'templates', area: 'library', from: 'skills · library · marketplace', title: 'Templates, skills and the marketplace',
    summary: 'Start from something already solved, and see which specialists exist before you ask.',
    screens: [{ id: 'L-TPL', label: 'Templates & Skills', current: '/templates' }, { id: 'L-MKT', label: 'Marketplace', current: '/marketplace' }],
    what: 'Templates are reusable starting points, checked for compatibility with your blueprint. Skills are the specialist capabilities the platform can call. The marketplace offers automation templates published for reuse.',
    why: 'Many patterns were solved before. Reusing a validated one is faster and safer than rewriting it.',
    how: ['Browse the templates and open one to see what it covers.', 'Run the compatibility check against your project’s blueprint.', 'Preview a skill to see what it would produce.', 'Install a marketplace automation, then configure it in Automations.'],
    give: 'A project blueprint to check against, or a task to automate.',
    get: 'A compatible starting point, a previewed skill, or an installed automation.',
    limits: ['Not every template fits every stack — the compatibility check lists what is missing.', 'The marketplace holds automation templates only.'],
    good: ['Check compatibility before applying a template.', 'Treat a template as a starting point, not a finished solution.'],
    trouble: [['A template is not compatible with the project', 'Read the compatibility result: it lists what matched, what is missing and its warnings.']],
    api: ['GET /api/templates/catalog', 'GET /api/templates/{template_id}/compatibility', 'GET /api/skills', 'POST /api/skills/preview', 'GET /api/marketplace/items', 'POST /api/marketplace/items/{item_id}/install'],
    terms: ['Skill', 'Capability'],
  },
  {
    id: 'certification', area: 'library', title: 'Certification and the workforce',
    summary: 'What has actually been proven, by which executed suite, and which roles can be staffed.',
    screens: [{ id: 'W-DIR', label: 'Workforce', current: '/workforce' }],
    what: 'Certification records what an executed suite proved for a stack, an agent or a composition of apps. The workforce shows the role taxonomy and which roles can be staffed today, and the planner composes the company a stack and risk profile would need.',
    why: 'Trusting a generated project starts with trusting who built it and with what. A certification you can open beats a promise.',
    how: ['Open a record to see its checks, when it ran and its verdict.', 'Compare stacks, agents and compositions — each keeps its own result.', 'In the workforce, see which roles have certified agents.', 'Use the planner to compose a company for a stack and find the gaps before a mission does.'],
    give: 'Nothing to read the records; a stack and a risk profile to plan.',
    get: 'Verdicts with their checks, and a company plan with its gaps.',
    limits: ['Results are never averaged into one score.', 'Some certification runs can be started only through the API today.'],
    good: ['Check when a certification ran: an old run proves an old version.', 'Plan the workforce before a mission on an unusual stack.'],
    trouble: [['A role has no certified agent', 'A mission may fill it another way and record a CERTIFICATION_GAP refusal; the planner shows that gap in advance.']],
    api: ['GET /api/registry/stack-certifications', 'GET /api/workforce/cognitive-certifications', 'GET /api/workforce/compositions', 'POST /api/workforce/plan'],
    terms: ['Certification', 'Routing refusal'],
  },
  {
    id: 'data', area: 'library', from: 'data-intelligence', title: 'Data Studio',
    summary: 'Bring a dataset and a question; get treated data, analysis and a report, one approved step at a time.',
    screens: [{ id: 'S-DATA', label: 'Data Studio', current: '/data-intelligence' }],
    what: 'A data session takes your own dataset through ingestion, profiling, cleaning, analysis, reporting and monitoring. Each step is run by an agent and says whether it completed with AI or deterministically.',
    why: 'Business data has to be understood and cleaned before any conclusion can be trusted — and the cleaning must be something you approve.',
    how: ['Describe the objective and confirm how the session understood it.', 'Upload the data source.', 'Review the profile and approve the cleaning plan.', 'Follow the analysis and the report, then set up monitoring.'],
    give: 'A CSV, TSV or JSON file and an analysis objective.',
    get: 'A treated dataset, insights with their confidence, dashboards and exportable reports.',
    who: ['An agent per step — classification, quality, governance, analysis'],
    limits: ['Steps that need a model run on your AI key.', 'Long steps run as background jobs; the session shows their progress.'],
    good: ['Write the objective as a business question.', 'Read the cleaning plan before approving it — it changes the data.'],
    trouble: [['A step shows BLOCKED', 'It is waiting for an approval or for an earlier step; the session names what it waits for.']],
    api: ['POST /api/data-intelligence/sessions'],
    terms: ['Execution'],
  },
  {
    id: 'automations', area: 'library', title: 'Automations',
    summary: 'A trigger and one HTTP request that run on your behalf, with a history of every run.',
    screens: [{ id: 'S-AUTO', label: 'Automations', current: '/automations' }, { id: 'L-MKT', label: 'Marketplace', current: '/marketplace' }],
    what: 'An automation is a manual or scheduled trigger followed by one HTTP request. Every run is recorded with its status, and credentials are write-only.',
    why: 'Small recurring tasks should not need a whole project — and anything that runs on your behalf must leave a trace.',
    how: ['Create the automation, or install a template from the marketplace.', 'Choose the trigger: manual, or a cron schedule with its time zone.', 'Configure the request; credentials are stored and never shown again.', 'Run it now or activate it, and read the run history.'],
    give: 'An endpoint to call, and when to call it.',
    get: 'Runs on schedule or on demand, each recorded with its result.',
    limits: ['One trigger and one HTTP request per automation.', 'Credentials cannot be read back — replace them instead.'],
    good: ['Run it manually once before activating the schedule.', 'Pause an automation you may need again instead of archiving it.'],
    trouble: [['A run failed', 'Open the run history: each run keeps its status and when it ran.']],
    api: ['POST /api/automations'],
    terms: ['Execution', 'Evento'],
  },
  {
    id: 'projects', area: 'account', from: 'projects · jobs', title: 'Projects and their history',
    summary: 'Find any project, see where it is in its lifecycle, and reopen what was already generated.',
    screens: [{ id: 'G-PRJ', label: 'Projects', current: '/projects' }, { id: 'P-MSL', label: 'Missions', current: '/jobs' }],
    what: 'Projects lists everything you are building — rooms still in definition, projects generating, READY or failed — with the state of each. Inside a project, Missions keeps every generation run, including failed and archived ones; Activity keeps the events of the whole account.',
    why: 'Work started weeks ago must be easy to find, and a finished generation should never have to be rebuilt to be seen again.',
    how: ['Filter projects by lifecycle, or search by name.', 'Open a project to land on its cockpit and its current step.', 'In Missions, open any past run with its evidence; archived runs stay available.', 'Use Activity to see what happened, when, and what caused it.'],
    give: 'Nothing — every project created on the platform appears here.',
    get: 'A searchable register with the real state of each project and its runs.',
    limits: ['It is a register: it starts nothing by itself.', 'Archived projects stay hidden until you filter for them.'],
    good: ['Search by name instead of scrolling.', 'Archive runs you no longer need instead of deleting them.'],
    trouble: [['A project you created is missing', 'Check the lifecycle filter — archived projects are hidden by default.'], ['An old run disappeared from the list', 'It was archived. Show archived runs in Missions.']],
    api: ['GET /api/projects', 'GET /api/meta-factory/jobs', 'PATCH /api/meta-factory/jobs/{job_id}/archive', 'GET /api/activity-feed'],
    terms: ['Project', 'Mission', 'Evento'],
  },
  {
    id: 'plan', area: 'account', from: 'pricing', title: 'Plans, trial and usage',
    summary: 'What your plan allows, how close you are to its limits, and how the trial works.',
    screens: [{ id: 'A-PLAN', label: 'Plan & Usage', current: '/settings' }, { id: 'U-PRICE', label: 'Pricing', current: '/pricing' }],
    what: 'Your plan sets limits — active projects, workspaces, members, preview instances, storage — and the features you can use. Plan & Usage shows the subscription, the trial and the metered usage of the current period.',
    why: 'You should be able to decide about a plan knowing exactly what changes, without asking support.',
    how: ['See the current plan and its status.', 'Compare this period’s usage with each limit.', 'Compare plans side by side on Pricing.', 'Change the plan; students can verify an enrollment for the student plan.'],
    give: 'Nothing to read; a decision to change plans.',
    get: 'Clear limits, usage and subscription status.',
    limits: ['Plans include no AI credits; AI usage is billed by your provider.', 'The trial lasts 72 hours from account creation.', 'Where the catalog sets no price for a plan, the page says so instead of guessing.'],
    good: ['Check usage before starting a large mission.', 'Compare limits, not only prices.'],
    trouble: [['An action says the plan does not allow it', 'Plan & Usage shows which feature or limit blocked it.']],
    api: ['GET /api/billing/plans', 'GET /api/billing/subscription', 'GET /api/billing/trial', 'GET /api/billing/entitlements', 'GET /api/billing/usage'],
    terms: ['Plano Estudante', 'Elegibilidade estudantil'],
  },
  {
    id: 'account', area: 'account', from: 'settings', title: 'Account, security and workspaces',
    summary: 'Keep the account safe, see where it is signed in, and control who can do what.',
    screens: [{ id: 'A-ACC', label: 'Account & Security', current: '/settings' }, { id: 'A-WS', label: 'Workspace & Access', current: '/settings' }],
    what: 'Account & Security holds your profile, password, two-factor setup, active sessions, consent and data export. Workspace & Access holds members, roles and the permission matrix. Preferences hold language, interface and defaults.',
    why: 'An account that builds and delivers software deserves the same care as the software: known sessions, clear permissions and control over your data.',
    how: ['Review the active sessions and end the ones you do not recognize.', 'Set up two-factor authentication with an authenticator app.', 'Give each member the smallest role that fits, and read why a permission is allowed.', 'Choose language and interface preferences; they are saved to your account.'],
    give: 'Your decisions about security, people and preferences.',
    get: 'A safer account, clear permissions and preferences that persist.',
    limits: ['Two-factor authentication can be enabled, but sign-in does not ask for the code yet (gap G14).', 'There is no password reset by e-mail yet (gap G15).', 'Permission explanations arrive in Portuguese.'],
    good: ['Review sessions after signing in on a shared computer.', 'Export your data before closing the account.'],
    trouble: [['A member cannot perform an action', 'Open the permission explanation for that action and role: it says which rule applied.']],
    api: ['GET /api/auth/me/sessions', 'POST /api/auth/me/2fa/enroll', 'GET /api/workspaces', 'GET /api/permissions/explain', 'PUT /api/users/me/preferences/interface'],
    terms: ['Workspace'],
  },
  {
    id: 'platform', area: 'account', from: 'system-status · analytics · roadmap', title: 'Platform health and roadmap',
    summary: 'Whether the platform itself is healthy, why models were chosen, and what is planned.',
    screens: [{ id: 'X-HLT', label: 'Platform Health', current: '/system-status' }, { id: 'X-RMP', label: 'Roadmap', current: '/roadmap' }],
    what: 'Platform Health gathers system status, runtime telemetry and usage analytics. AI Decision Traces shows why the router picked each model and what it cost. The roadmap shows what is implemented, in progress and planned.',
    why: 'When something is slow or failing, you need to know whether the problem is your project or the platform.',
    how: ['Check each signal; a degraded one names what is affected.', 'Follow runtime telemetry live.', 'Open a decision trace to see the alternatives, the context, the tokens and the cost.', 'Read the roadmap to set expectations.'],
    give: 'Nothing — these are readings.',
    get: 'The real health of the platform and the reasons behind model choices.',
    limits: ['A telemetry component without a collector shows as unknown, never as healthy.', 'The roadmap is a governed plan, not a date commitment.', 'Runtime configuration is for administrators only.'],
    good: ['Check Platform Health before reporting a problem as your project’s.', 'Read the decision traces when costs surprise you.'],
    trouble: [['A signal is degraded', 'Open it: the status names the component and the message the backend returned.']],
    api: ['GET /api/system-status', 'GET /api/runtime/telemetry', 'GET /api/analytics/overview', 'GET /api/observability/decisions', 'GET /api/roadmap'],
    terms: ['Runtime', 'Evento'],
  },
];
