import type { Guide } from '../types';

/* Areas “Start here”, “Define” and “Build”. Screens not built in this app link to the current app (`current`). */
export const GUIDES_A: readonly Guide[] = [
  {
    id: 'how-it-works', area: 'start', title: 'How an idea becomes verified software',
    summary: 'The path every project follows, and where each step lives.',
    screens: [{ id: 'G-NEW', label: 'Start', current: '/wizard' }, { id: 'G-PRJ', label: 'Projects', current: '/projects' }, { id: 'P-EVD', label: 'Evidence', current: '/meta-factory' }],
    what: 'LDCN OS turns a description into a working project through a fixed sequence of steps. Each step ends in a state the backend records, and the next step starts only from that state.',
    why: 'Code generated without settled requirements, a reviewed architecture and proof of what was built is code nobody can trust. The sequence exists so every READY can be traced back.',
    how: [
      'Discovery: you describe the idea in a Project Room and answer a few questions.',
      'Requirements: the conversation becomes a PromptMaster, which you approve.',
      'Architecture: a blueprint with justified decisions is proposed, and you approve the stack.',
      'Engineering review: a readiness verdict — approved, approved with reservations, or blocked.',
      'Mission: the Meta-Factory staffs a virtual company and generates the project step by step.',
      'Verification: the project is built, started, health-checked and tested in a sandbox.',
      'Delivery: when the gates allow it, you choose how to receive it — ZIP, Git export or staging.',
    ],
    give: 'An idea in your own words — or a PromptMaster, a codebase, a dataset or a process to automate.',
    get: 'A generated project with its evidence: requirements, decisions, test sessions and gate results.',
    limits: ['Steps that write content run on your AI key (BYOK).', 'Live preview, staging and functional browser tests support Python/FastAPI with Next.js/React and PostgreSQL today.'],
    good: ['Follow the Evidence Line at the top of a project: it always shows which step you are on.', 'Approve only what you have read — each approval is the base of the next step.'],
    trouble: [['A step does not start', 'Open its station on the Evidence Line: the backend says which state it is waiting for and who can move it.']],
    terms: ['Project Room', 'Mission', 'Evidence Line', 'READY'],
  },
  {
    id: 'signals', area: 'start', title: 'Reading states, signals and the Evidence Line',
    summary: 'What the shapes, badges and live indicators mean — and what they never pretend.',
    screens: [{ id: 'G-TRM', label: 'Terms & signals', path: '/learn/terms' }, { id: 'P-MSN', label: 'Mission Command Center', current: '/meta-factory' }],
    what: 'Every state is shown as a signal shape next to the exact value the backend returned, with plain words beside it when the value is technical.',
    why: 'A color alone is easy to miss and invisible to some people. A shape plus the real value keeps the interface readable and honest.',
    how: [
      'Look at the shape first: a check means proven, a diamond means waiting on you, a square with a cross means failed.',
      'Read the badge: it carries the backend’s own value, such as PROMPT_APPROVED or META_FACTORY_RUNNING.',
      'Check the live indicator: “Live · last event 4 s ago” means a stream is connected; Snapshot means the data was read once.',
      'Select a station on the Evidence Line to open the proof behind its state.',
    ],
    give: 'Nothing — this is how every screen reads.',
    get: 'The ability to tell at a glance what is proven, running, failed or waiting on you.',
    limits: ['Only the diamond uses the decision color, so a screen without a diamond has nothing waiting on you.', 'Motion appears only while an event stream is connected; nothing spins for effect.'],
    good: ['When a badge value is unfamiliar, look it up in Terms & signals.', 'Treat Unknown as unknown: the interface never turns a failed read into healthy.'],
    trouble: [['A signal says Unknown', 'The interface could not read that source. Reload; if it stays Unknown, Platform health shows whether the backend is degraded.']],
    terms: ['Evidence Line', 'Live · Snapshot'],
  },
  {
    id: 'decisions', area: 'start', title: 'Decisions that wait for you',
    summary: 'Why some work stops until a person acts, and where those decisions gather.',
    screens: [{ id: 'G-INB', label: 'Action Center', current: '/platform' }],
    what: 'Some steps belong to a person by design: approving a PromptMaster or a stack, accepting a change, choosing how to deliver, curating team knowledge. The Action Center lists every one that is open.',
    why: 'The platform generates and verifies, but it does not decide what ships. One queue means nothing important waits unnoticed on a screen you did not open.',
    how: [
      'A backend state that needs a person appears as a card with a diamond.',
      'The card says what is waiting, why, and what happens when you decide.',
      'Only actions legal in the current state are offered; the others appear as not available, with the reason.',
      'The card leaves the queue when the backend state changes — never because it was dismissed.',
    ],
    give: 'Your decision, with the confirmation the backend asks for.',
    get: 'The next step unblocked, recorded with who decided and when.',
    limits: ['No backend endpoint lists pending decisions yet, so the queue is composed from several sources and each card names its own (gap G4).'],
    good: ['Start the day with the decisions waiting on you.', 'Read the “why” before deciding: it is the backend’s reason, not a summary.'],
    trouble: [['A decision button is disabled', 'The state changed or the action is not legal yet. Focus the button to read why.']],
    api: ['GET /api/meta-factory/{project_id}/delivery', 'GET /api/project-rooms/{room_id}', 'GET /api/team-memory/{team_id}/queue', 'GET /api/system/presence/decisions'],
    terms: ['Decision'],
  },
  {
    id: 'ai-key', area: 'start', title: 'Your AI key and what it costs',
    summary: 'Why the platform runs on your own provider key, and how to read the spend.',
    screens: [{ id: 'A-AI', label: 'AI Providers & Cost', current: '/settings' }],
    what: 'AI work in LDCN OS runs on a provider key you add (BYOK). The active provider, its model and the estimated spend are always visible.',
    why: 'You keep control of the provider, the model and the bill. Plans charge for the platform, never for AI credits.',
    how: [
      'Add a key in AI Providers & Cost; it is write-only and shown masked from then on.',
      'Test the key. A validation that grows old is marked STALE until you test again.',
      'Choose the execution profile that fits the work.',
      'Follow usage by model and by day; every figure is tokens times the provider’s public price.',
    ],
    give: 'A valid key from a supported provider.',
    get: 'Missions, reviews and writers that run on your account, with spend you can follow.',
    limits: ['Without a valid key, steps that need a model stop and say so — they never fall back silently.', 'Costs are estimates; the provider’s invoice is the real figure.'],
    good: ['Test the key before a long mission.', 'Compare usage by model before changing the default profile.'],
    trouble: [['The provider shows STALE', 'The last successful validation is old. Test the key again in AI Providers & Cost.']],
    api: ['GET /api/llm/settings/active', 'GET /api/user-ai-keys', 'GET /api/llm/usage/stats', 'GET /api/execution-profiles'],
    terms: ['BYOK', 'Estimated cost'],
  },
  {
    id: 'discovery', area: 'define', from: 'project-rooms', title: 'Discovery and the PromptMaster',
    summary: 'From a free conversation to an approved PromptMaster.md, ready for architecture.',
    screens: [{ id: 'P-DSC', label: 'Discovery', current: '/project-rooms' }, { id: 'P-REQ', label: 'Requirements', current: '/project-rooms' }],
    what: 'A Project Room is a continuous conversation in which a loose idea becomes, step by step, a statement of intent — the PromptMaster.md — ready to become software.',
    why: 'Most ideas start vague. Demanding a complete technical brief up front keeps away the people who most need the platform.',
    how: ['Describe what you want to build in plain language.', 'Answer the few questions discovery asks about what is still unclear.', 'The room organizes the conversation into a PromptMaster, which you read and edit.', 'Approve it, and the room moves on to architecture.'],
    give: 'A conversation in your own words about what you want to build.',
    get: 'An approved PromptMaster.md and a room ready for its architecture.',
    who: ['Conversation agent — organizes the intent', 'Intent coverage check — measures how much of your idea the PromptMaster covers and asks about what is missing'],
    files: ['PromptMaster.md'],
    limits: ['A room is one project, not a general chat.', 'Approval stays locked while intent coverage is below 90%.', 'Editing an approved PromptMaster returns it to PROMPT_READY.'],
    good: ['Explain it as you would to a person, not as a formal requirement.', 'Read the PromptMaster before approving — everything after it is built on it.'],
    trouble: [['The PromptMaster covers more than you wanted', 'Edit it before approving, or go back to the conversation and narrow the scope.']],
    faq: [['Do I need to write a technical brief?', 'No. The conversation is free; the room organizes what you describe.'], ['Can I change my mind halfway?', 'Yes. The room keeps the conversation’s memories and lets you revise the PromptMaster before approving.']],
    api: ['POST /api/project-rooms', 'POST /api/project-rooms/{room_id}/message', 'POST /api/project-rooms/{room_id}/generate-prompt', 'PUT /api/project-rooms/{room_id}/prompt'],
    terms: ['Project Room', 'PromptMaster.md'],
  },
  {
    id: 'architecture', area: 'define', from: 'architect', title: 'Architecture and the stack',
    summary: 'An approved PromptMaster becomes a blueprint in which every decision says why.',
    screens: [{ id: 'P-ARC', label: 'Architecture', current: '/architect' }],
    what: 'The architect turns the approved intent into decisions — stack, modules, integrations, data — each with its justification, plus an effort estimate and the cost to run.',
    why: 'Generating code before deciding the architecture is building without a plan: it works until it stops working, and late decisions are expensive to undo.',
    how: ['The blueprint arrives with its decisions and the reason for each.', 'Compare the alternatives, dependencies and readiness views.', 'Approve the stack: it is locked in stack.lock.json for generation.', 'The project moves on to the engineering review.'],
    give: 'An approved PromptMaster.',
    get: 'A justified blueprint, an effort estimate and a locked stack.',
    who: ['Architect — proposes and justifies each decision'],
    files: ['Architecture blueprint', 'stack.lock.json'],
    limits: ['It needs an approved PromptMaster.', 'It decides the architecture; it does not write application code.', 'Once approved, the stack is locked; changing it takes a new architecture round.'],
    good: ['Read each decision’s justification before approving — that is where change costs nothing.', 'Question a stack that does not match your team’s experience.'],
    trouble: [['The proposed stack is not the one you wanted', 'Adjust it before approving. After approval it is locked for generation.']],
    faq: [['Can I change the stack after approving?', 'The stack is locked so generation stays consistent; a change needs a new architecture round.']],
    api: ['POST /api/blueprints/preview', 'GET /api/project-rooms/{room_id}'],
    terms: ['Blueprint'],
  },
  {
    id: 'review', area: 'define', from: 'engineering-review', title: 'Engineering review',
    summary: 'The last reading before the virtual company starts building.',
    screens: [{ id: 'P-REV', label: 'Engineering Review', current: '/engineering-review' }],
    what: 'The engineering review checks the blueprint’s risks and readiness against deterministic engineering policies and returns a verdict before any real code is generated.',
    why: 'Stopping a problem before the Meta-Factory is far cheaper than finding it in generated code.',
    how: ['The approved blueprint and the project state go to review.', 'Policies check risks and readiness; points that need judgment are read by AI.', 'The verdict: approved, approved with reservations, or blocked — with the exact list.', 'When approved, send the project to the Meta-Factory.'],
    give: 'The blueprint and the current state of the project.',
    get: 'A readiness verdict, an effort estimate and a recommended team profile.',
    who: ['Gatekeeper — deterministic policies', 'AI reading where a policy needs judgment'],
    files: ['Engineering readiness report', 'Effort estimate and team profile'],
    limits: ['It points out risks; it does not fix them.', 'It runs after the blueprint, never before.'],
    good: ['Treat a blocked verdict as a task list, not an obstacle.', 'Use the effort estimate to set expectations before the mission.'],
    trouble: [['Approved with reservations, and it is unclear what to do', 'Each reservation is specific: resolve it in the blueprint, or accept the risk knowingly before sending.']],
    faq: [['Is a block final?', 'No. Adjust the blueprint or the scope and send it for a new review.']],
    api: ['POST /api/gatekeeper/preview', 'POST /api/engineering/readiness', 'POST /api/engineering/delivery-estimate'],
    terms: ['Gate'],
  },
  {
    id: 'missions', area: 'build', title: 'Missions and the virtual company',
    summary: 'What happens after a project goes to the Meta-Factory, and how to follow it live.',
    screens: [{ id: 'P-MSL', label: 'Missions', current: '/jobs' }, { id: 'P-MSN', label: 'Mission Command Center', current: '/meta-factory' }],
    what: 'A mission is one generation run of the Meta-Factory for a project. A virtual company is staffed for it — teams, positions and specialists — and works through the pipeline steps until the mission ends READY or FAILED, or is paused.',
    why: 'Generating a whole project is long work with many hands. Seeing who did each step, why they were chosen and what they produced is what makes the result checkable.',
    how: ['Send an approved project to the Meta-Factory; the mission starts with its own id.', 'The company is staffed from the role taxonomy; every hire records its reason and every refusal its code.', 'Follow the steps live: the stream resumes where it stopped, and nothing moves when no event arrives.', 'When the mission ends, open its evidence: gates, test sessions and the delivery decision.'],
    give: 'A project with an approved engineering review and an approved stack.',
    get: 'Generated code, a record of every step, tokens and estimated cost, and the gates the mission passed or failed.',
    who: ['Chief orchestrator — plans and audits the company', 'Specialists staffed per position, each with its certification'],
    limits: ['A web project with backend and frontend runs 37 pipeline steps; other targets run their own set.', 'Resume is offered only from PAUSED or STALLED, and a stage cannot be retried while it runs.', 'The mandatory gates arrive with the live stream, not with the job read (gap G2).'],
    good: ['Read the company’s refusals: a CERTIFICATION_GAP explains why a position was filled differently.', 'Compare a failed mission with the next attempt instead of starting from zero.'],
    trouble: [['The mission stopped progressing', 'Open the Mission Command Center: the stream shows the last step, and Resume appears when the state allows it.'], ['A build step failed', 'Open the step to read the error and what the automatic repair tried before it stopped.']],
    api: ['GET /api/meta-factory/jobs', 'GET /api/meta-factory/jobs/{job_id}/events', 'GET /api/companies/by-job/{job_id}', 'GET /api/companies/by-job/{job_id}/assignments'],
    terms: ['Mission', 'Virtual company', 'Routing refusal', 'Gate'],
  },
  {
    id: 'guided', area: 'build', from: 'wizard', title: 'Guided missions',
    summary: 'Start from one of 24 mission types in a step-by-step workspace.',
    screens: [{ id: 'G-NEW', label: 'Start', current: '/wizard' }],
    what: 'A guided mission is one unit of technical work: you pick a mission type, describe the goal, and a workspace takes you through its steps with the right specialist for each.',
    why: 'Not every problem needs a whole project. Sometimes you need to diagnose one error, plan an infrastructure or compare solutions without setting up everything.',
    how: ['Choose a mission type — create, analyze, fix, evolve, plan or research.', 'Describe the goal; each step asks only for what it needs.', 'Accept, change or answer the AI’s proposals step by step; every decision is recorded with its origin.', 'Compile the deliverables; when code must be built, the mission hands off to a Project Room.'],
    give: 'A goal in text, and answers for each step.',
    get: 'A plan and the deliverables of that mission type — and a Project Room when engineering is needed.',
    who: ['Mission router — classifies the request', 'A specialist per step, for example security_engineer for Security'],
    files: ['Mission plan', 'Deliverables of the mission type'],
    limits: ['A mission covers one scope; it does not replace a full project.', 'Steps that write content need a configured AI key (BYOK).'],
    good: ['Describe the goal with context: what, and for whom.', 'Prefer one mission per problem.'],
    trouble: [['The plan came out generic', 'Go back and detail the goal — more context gives a more specific plan.']],
    faq: [['Do I need a project first?', 'No. A mission can start from a loose goal.']],
    api: ['GET /api/missions/registry', 'POST /api/missions', 'POST /api/missions/{mission_id}/ai-action', 'POST /api/missions/{mission_id}/decisions'],
    terms: ['Guided mission'],
  },
  {
    id: 'changes', area: 'build', title: 'Workbench and changes',
    summary: 'Read generated code with its provenance, and change it through requests you review.',
    screens: [{ id: 'P-WBN', label: 'Engineering Workbench', current: '/projects' }, { id: 'P-CHG', label: 'Changes', current: '/change-requests' }],
    what: 'The workbench shows every generated file with the role that wrote it, the requirement it serves and the gates that prove it. Changes to that code go through Change Requests: a versioned request, a diff you review, and an apply step.',
    why: 'Editing generated code by hand breaks the trail between a requirement and the file that implements it. A Change Request keeps the trail and makes every change reviewable.',
    how: ['Open a file to see its author role, its requirement and its gates.', 'Ask for a change; it becomes a Change Request with its own id.', 'Review the diff file by file.', 'Advance the request one legal step at a time until it is applied.'],
    give: 'A description of the change, on a generated project.',
    get: 'A reviewed diff applied to the project, with its history.',
    limits: ['Each action is legal from exactly one status; the others are shown as unavailable, with the reason.', 'Apply is refused when the files changed after the diff was produced, instead of overwriting them.'],
    good: ['Keep one intent per Change Request.', 'Read the whole diff before accepting.'],
    trouble: [['Apply was refused because the files changed', 'Someone or something changed those files after the diff. Review the current files before trying again.']],
    api: ['GET /api/change-requests/{change_request_id}/diff', 'GET /api/meta-factory/{project_id}/endpoints', 'POST /api/meta-factory/{project_id}/terminal/execute'],
    terms: ['Change Request', 'Patch'],
  },
  {
    id: 'verification', area: 'build', from: 'engineering-laboratory', title: 'Build & Test Room',
    summary: 'Prove that the generated project builds, starts and passes its tests — for real.',
    screens: [{ id: 'P-BLD', label: 'Build & Test Room', current: '/test-room' }, { id: 'LAB', label: 'Engineering Laboratory', current: '/engineering-laboratory' }],
    what: 'The Build & Test Room runs the generated project in an isolated sandbox: it builds it, starts it, checks its health and runs its tests, and records each result as evidence.',
    why: '“It compiles” is not “it works”. Only real execution proves that a generated system works.',
    how: ['Run the Test Room for the project.', 'Follow the build, start, health and test stages as they run.', 'Read the real output of each command, not a summary.', 'A passing session becomes the proof the delivery gates rely on.'],
    give: 'A generated project.',
    get: 'Test sessions with their gates, commands and output — and the proof delivery relies on.',
    who: ['Deterministic tools — build, tests, dependency audit', 'AI repair only for failures without a known fix'],
    files: ['Test Room session', 'Runtime API audit report', 'Functional browser test report'],
    limits: ['It needs a generated project.', 'Real execution takes real time.', 'The runtime API audit covers Python/FastAPI projects only.'],
    good: ['Run the tests before trusting any delivery, even one that looks ready.', 'Use the terminal’s allowlisted commands — they run inside the project’s sandbox.'],
    trouble: [['A test failed and the reason is unclear', 'Open the session: it shows the exact command and its output.']],
    faq: [['Is the terminal simulated?', 'No. Commands run for real against the generated workspace, inside an isolated sandbox.']],
    api: ['GET /api/test-room/{project_id}/proof', 'POST /api/meta-factory/{project_id}/terminal/execute', 'POST /api/meta-factory/{project_id}/runtime-functional-test'],
    terms: ['Evidence', 'Build'],
  },
  {
    id: 'modernize', area: 'build', from: 'modernize · auto-fix', title: 'Modernize an existing codebase',
    summary: 'Import code you already have, understand it, and apply an approved plan with controlled risk.',
    screens: [{ id: 'P-MOD', label: 'Modernization', current: '/modernize' }, { id: 'FIX', label: 'Auto-Fix', current: '/auto-fix' }],
    what: 'Modernization analyzes a real project sent as a ZIP or a Git URL, proposes a plan, and applies fixes only after your approval — revalidating everything at the end.',
    why: 'Most software already exists and needs to evolve; starting over is rarely the right answer.',
    how: ['Import the codebase as a ZIP or from Git.', 'Read the analysis: dependencies, vulnerabilities, quality and risk.', 'Approve the plan, leaving out any fix you do not want.', 'The fixes are applied, and the project is revalidated and ready to export.'],
    give: 'An existing project, as a ZIP upload or a Git URL.',
    get: 'The same system, modernized and revalidated, with a report and a diff per change.',
    who: ['Refactoring AI', 'Deterministic fixes by template; AI repair where no template exists'],
    files: ['Modernization report', 'A diff per proposed change', 'The revalidated project, ready to export'],
    limits: ['An imported codebase never becomes a mission: its lifecycle is the modernization pipeline.', 'How deep the analysis goes depends on the stack being one the engine supports.'],
    good: ['Send the whole repository, not a part — the analysis needs the context.', 'Read the analysis before approving the plan.'],
    trouble: [['The analysis did not recognize the stack', 'Check the supported stacks before importing again.']],
    faq: [['Does it rewrite the whole project?', 'No. The plan is incremental and each change can be reviewed before it is applied.'], ['Can I ask questions about the code?', 'Yes. The modernization screen answers questions grounded on the analysis.']],
    api: ['POST /api/modernize/projects/upload', 'POST /api/modernize/projects/git', 'POST /api/modernize/{project_id}/analyze', 'POST /api/modernize/{project_id}/approve-plan', 'POST /api/modernize/{project_id}/apply-fixes', 'POST /api/modernize/ask'],
    terms: ['Patch'],
  },
];
