import type { Guide } from '../types';

/* Áreas “Comece aqui”, “Definir” e “Construir”. Telas que ainda não existem neste app levam ao app atual (`current`). */
export const GUIDES_A: readonly Guide[] = [
  {
    id: 'how-it-works', area: 'start', title: 'Como uma ideia vira software verificado',
    summary: 'O caminho que todo projeto percorre, e onde fica cada passo.',
    screens: [{ id: 'G-NEW', label: 'Começar', current: '/wizard' }, { id: 'G-PRJ', label: 'Projetos', current: '/projects' }, { id: 'P-EVD', label: 'Evidência', current: '/meta-factory' }],
    what: 'O LDCN OS transforma uma descrição num projeto que funciona por uma sequência fixa de passos. Cada passo termina num estado que o backend registra, e o passo seguinte só começa a partir desse estado.',
    why: 'Código gerado sem requisitos definidos, sem arquitetura revisada e sem prova do que foi construído é código em que ninguém pode confiar. A sequência existe para que todo READY possa ser rastreado até a origem.',
    how: [
      'Descoberta: você descreve a ideia numa Project Room e responde a algumas perguntas.',
      'Requisitos: a conversa vira um PromptMaster, que você aprova.',
      'Arquitetura: um blueprint com decisões justificadas é proposto, e você aprova a stack.',
      'Revisão de engenharia: um veredito de prontidão — aprovado, aprovado com ressalvas ou bloqueado.',
      'Missão: a Meta-Fábrica monta uma empresa virtual e gera o projeto passo a passo.',
      'Verificação: o projeto é compilado, iniciado, checado e testado num sandbox.',
      'Entrega: quando os gates permitem, você escolhe como receber — ZIP, exportação para Git ou staging.',
    ],
    give: 'Uma ideia com suas palavras — ou um PromptMaster, um código existente, um conjunto de dados ou um processo para automatizar.',
    get: 'Um projeto gerado com a sua evidência: requisitos, decisões, sessões de teste e resultados de gates.',
    limits: ['Os passos que escrevem conteúdo usam a sua chave de IA (BYOK).', 'Preview ao vivo, staging e testes funcionais no navegador suportam hoje Python/FastAPI com Next.js/React e PostgreSQL.'],
    good: ['Siga a Evidence Line no topo do projeto: ela sempre mostra em que passo você está.', 'Aprove só o que você leu — cada aprovação é a base do passo seguinte.'],
    trouble: [['Um passo não começa', 'Abra a estação dele na Evidence Line: o backend diz por qual estado está esperando e quem pode fazê-lo avançar.']],
    terms: ['Project Room', 'Missão', 'Evidence Line', 'READY'],
  },
  {
    id: 'signals', area: 'start', title: 'Como ler estados, sinais e a Evidence Line',
    summary: 'O que as formas, os badges e os indicadores ao vivo querem dizer — e o que nunca fingem.',
    screens: [{ id: 'G-TRM', label: 'Termos e sinais', path: '/learn/terms' }, { id: 'P-MSN', label: 'Mission Command Center', current: '/meta-factory' }],
    what: 'Todo estado aparece como uma forma de sinal ao lado do valor exato que o backend devolveu, com palavras simples ao lado quando o valor é técnico.',
    why: 'Uma cor sozinha passa despercebida e é invisível para algumas pessoas. Forma mais valor real deixam a interface legível e honesta.',
    how: [
      'Olhe primeiro a forma: um visto quer dizer provado, um losango quer dizer esperando você, um quadrado com X quer dizer que falhou.',
      'Leia o badge: ele traz o valor do próprio backend, como PROMPT_APPROVED ou META_FACTORY_RUNNING.',
      'Confira o indicador ao vivo: “Ao vivo · último evento há 4 s” quer dizer que há um stream conectado; Retrato quer dizer que os dados foram lidos uma vez.',
      'Escolha uma estação na Evidence Line para abrir a prova por trás do estado.',
    ],
    give: 'Nada — é assim que toda tela se lê.',
    get: 'Saber de relance o que está provado, em execução, falhou ou espera você.',
    limits: ['Só o losango usa a cor de decisão; uma tela sem losango não tem nada esperando você.', 'Só há movimento enquanto um stream de eventos está conectado; nada gira por efeito.'],
    good: ['Quando um valor de badge for estranho, procure em Termos e sinais.', 'Trate desconhecido como desconhecido: a interface nunca transforma uma leitura que falhou em saudável.'],
    trouble: [['Um sinal diz Desconhecido', 'A interface não conseguiu ler essa fonte. Recarregue; se continuar desconhecido, a saúde da plataforma mostra se o backend está degradado.']],
    terms: ['Evidence Line', 'Ao vivo · Retrato'],
  },
  {
    id: 'decisions', area: 'start', title: 'Decisões que esperam por você',
    summary: 'Por que parte do trabalho para até uma pessoa agir, e onde essas decisões se reúnem.',
    screens: [{ id: 'G-INB', label: 'Action Center', current: '/platform' }],
    what: 'Alguns passos pertencem a uma pessoa por definição: aprovar um PromptMaster ou uma stack, aceitar uma mudança, escolher como entregar, curar o conhecimento da equipe. O Action Center lista todos os que estão abertos.',
    why: 'A plataforma gera e verifica, mas não decide o que é entregue. Uma fila única garante que nada importante espere esquecido numa tela que você não abriu.',
    how: [
      'Um estado do backend que precisa de uma pessoa aparece como um cartão com losango.',
      'O cartão diz o que está esperando, por quê, e o que acontece quando você decide.',
      'Só as ações permitidas no estado atual são oferecidas; as outras aparecem como indisponíveis, com o motivo.',
      'O cartão sai da fila quando o estado do backend muda — nunca porque foi dispensado.',
    ],
    give: 'A sua decisão, com a confirmação que o backend pede.',
    get: 'O passo seguinte liberado, registrado com quem decidiu e quando.',
    limits: ['Ainda não existe endpoint que liste as decisões pendentes; a fila é montada a partir de várias fontes e cada cartão diz a sua (lacuna G4).'],
    good: ['Comece o dia pelas decisões que esperam por você.', 'Leia o “porquê” antes de decidir: é o motivo do backend, não um resumo.'],
    trouble: [['Um botão de decisão está desabilitado', 'O estado mudou ou a ação ainda não é permitida. Coloque o foco no botão para ler o motivo.']],
    api: ['GET /api/meta-factory/{project_id}/delivery', 'GET /api/project-rooms/{room_id}', 'GET /api/team-memory/{team_id}/queue', 'GET /api/system/presence/decisions'],
    terms: ['Decisão'],
  },
  {
    id: 'ai-key', area: 'start', title: 'Sua chave de IA e quanto ela custa',
    summary: 'Por que a plataforma usa a chave do seu provedor, e como ler o gasto.',
    screens: [{ id: 'A-AI', label: 'Provedores de IA e custo', current: '/settings' }],
    what: 'O trabalho de IA no LDCN OS roda com uma chave de provedor que você cadastra (BYOK). O provedor ativo, o modelo e o gasto estimado ficam sempre à vista.',
    why: 'Você mantém o controle do provedor, do modelo e da fatura. Os planos cobram pela plataforma, nunca por créditos de IA.',
    how: [
      'Cadastre uma chave em Provedores de IA e custo; ela é só de escrita e aparece mascarada daí em diante.',
      'Teste a chave. Uma validação antiga aparece como STALE até você testar de novo.',
      'Escolha o perfil de execução que combina com o trabalho.',
      'Acompanhe o uso por modelo e por dia; todo valor é tokens vezes o preço público do provedor.',
    ],
    give: 'Uma chave válida de um provedor suportado.',
    get: 'Missões, revisões e redatores rodando na sua conta, com um gasto que você acompanha.',
    limits: ['Sem chave válida, os passos que precisam de modelo param e dizem isso — nunca caem para outra coisa em silêncio.', 'Os custos são estimativas; a fatura do provedor é o valor real.'],
    good: ['Teste a chave antes de uma missão longa.', 'Compare o uso por modelo antes de mudar o perfil padrão.'],
    trouble: [['O provedor aparece como STALE', 'A última validação bem-sucedida é antiga. Teste a chave de novo em Provedores de IA e custo.']],
    api: ['GET /api/llm/settings/active', 'GET /api/user-ai-keys', 'GET /api/llm/usage/stats', 'GET /api/execution-profiles'],
    terms: ['BYOK', 'Custo estimado'],
  },
  {
    id: 'discovery', area: 'define', from: 'project-rooms', title: 'Descoberta e o PromptMaster',
    summary: 'Da conversa livre a um PromptMaster.md aprovado, pronto para a arquitetura.',
    screens: [{ id: 'P-DSC', label: 'Descoberta', current: '/project-rooms' }, { id: 'P-REQ', label: 'Requisitos', current: '/project-rooms' }],
    what: 'Uma Project Room é uma conversa contínua em que uma ideia solta vira, passo a passo, um documento de intenção — o PromptMaster.md — pronto para virar software.',
    why: 'A maioria das ideias começa vaga. Exigir um brief técnico completo logo de início afasta quem mais precisaria da plataforma.',
    how: ['Descreva em linguagem comum o que você quer construir.', 'Responda às poucas perguntas que a descoberta faz sobre o que ainda não está claro.', 'A sala organiza a conversa num PromptMaster, que você lê e edita.', 'Aprove, e a sala segue para a arquitetura.'],
    give: 'Uma conversa com suas palavras sobre o que você quer construir.',
    get: 'Um PromptMaster.md aprovado e a sala pronta para a arquitetura.',
    who: ['Agente de conversa — organiza a intenção', 'Checagem de cobertura da intenção — mede quanto da sua ideia o PromptMaster cobre e pergunta o que falta'],
    files: ['PromptMaster.md'],
    limits: ['Uma sala é um projeto, não um chat genérico.', 'A aprovação fica travada enquanto a cobertura da intenção estiver abaixo de 90%.', 'Editar um PromptMaster aprovado o devolve para PROMPT_READY.'],
    good: ['Converse como se estivesse explicando para uma pessoa, não escrevendo um requisito formal.', 'Leia o PromptMaster antes de aprovar — tudo o que vem depois se apoia nele.'],
    trouble: [['O PromptMaster ficou maior do que você queria', 'Edite antes de aprovar, ou volte à conversa para restringir o escopo.']],
    faq: [['Preciso saber escrever um brief técnico?', 'Não. A conversa é livre; a sala organiza o que você descreve.'], ['Posso mudar de ideia no meio?', 'Sim. A sala guarda as memórias da conversa e deixa você revisar o PromptMaster antes de aprovar.']],
    api: ['POST /api/project-rooms', 'POST /api/project-rooms/{room_id}/message', 'POST /api/project-rooms/{room_id}/generate-prompt', 'PUT /api/project-rooms/{room_id}/prompt'],
    terms: ['Project Room', 'PromptMaster.md'],
  },
  {
    id: 'architecture', area: 'define', from: 'architect', title: 'Arquitetura e a stack',
    summary: 'Um PromptMaster aprovado vira um blueprint em que cada decisão diz o porquê.',
    screens: [{ id: 'P-ARC', label: 'Arquitetura', current: '/architect' }],
    what: 'O arquiteto transforma a intenção aprovada em decisões — stack, módulos, integrações, dados — cada uma com a sua justificativa, além de uma estimativa de esforço e do custo para rodar.',
    why: 'Gerar código antes de decidir a arquitetura é construir sem planta: funciona até deixar de funcionar, e decisões tardias custam caro para desfazer.',
    how: ['O blueprint chega com as decisões e o motivo de cada uma.', 'Compare as alternativas, as dependências e a prontidão.', 'Aprove a stack: ela fica travada no stack.lock.json para a geração.', 'O projeto segue para a revisão de engenharia.'],
    give: 'Um PromptMaster aprovado.',
    get: 'Um blueprint justificado, uma estimativa de esforço e a stack travada.',
    who: ['Architect — propõe e justifica cada decisão'],
    files: ['Blueprint de arquitetura', 'stack.lock.json'],
    limits: ['Precisa de um PromptMaster aprovado.', 'Decide a arquitetura; não escreve código de aplicação.', 'Depois de aprovada, a stack fica travada; mudá-la exige uma nova rodada de arquitetura.'],
    good: ['Leia a justificativa de cada decisão antes de aprovar — é ali que mudar não custa nada.', 'Questione uma stack que não combina com a experiência do seu time.'],
    trouble: [['A stack proposta não é a que você queria', 'Ajuste antes de aprovar. Depois da aprovação ela fica travada para a geração.']],
    faq: [['Posso mudar a stack depois de aprovar?', 'A stack fica travada para a geração continuar consistente; mudar exige uma nova rodada de arquitetura.']],
    api: ['POST /api/blueprints/preview', 'GET /api/project-rooms/{room_id}'],
    terms: ['Blueprint'],
  },
  {
    id: 'review', area: 'define', from: 'engineering-review', title: 'Revisão de engenharia',
    summary: 'A última leitura antes de a empresa virtual começar a construir.',
    screens: [{ id: 'P-REV', label: 'Revisão de engenharia', current: '/engineering-review' }],
    what: 'A revisão de engenharia confere riscos e prontidão do blueprint com políticas determinísticas de engenharia e devolve um veredito antes de qualquer código real ser gerado.',
    why: 'Barrar um problema antes da Meta-Fábrica é muito mais barato do que descobri-lo no código gerado.',
    how: ['O blueprint aprovado e o estado do projeto vão para revisão.', 'As políticas conferem riscos e prontidão; os pontos que pedem julgamento são lidos por IA.', 'O veredito: aprovado, aprovado com ressalvas ou bloqueado — com a lista exata.', 'Aprovado, envie o projeto para a Meta-Fábrica.'],
    give: 'O blueprint e o estado atual do projeto.',
    get: 'Um veredito de prontidão, uma estimativa de esforço e um perfil de equipe recomendado.',
    who: ['Gatekeeper — políticas determinísticas', 'Leitura por IA onde a política pede julgamento'],
    files: ['Relatório de prontidão de engenharia', 'Estimativa de esforço e perfil de equipe'],
    limits: ['Aponta riscos; não os corrige.', 'Roda depois do blueprint, nunca antes.'],
    good: ['Trate um veredito bloqueado como lista de tarefas, não como obstáculo.', 'Use a estimativa de esforço para calibrar a expectativa antes da missão.'],
    trouble: [['Aprovado com ressalvas, e não está claro o que fazer', 'Cada ressalva é específica: resolva no blueprint, ou aceite o risco conscientemente antes de enviar.']],
    faq: [['Um bloqueio é definitivo?', 'Não. Ajuste o blueprint ou o escopo e envie para uma nova revisão.']],
    api: ['POST /api/gatekeeper/preview', 'POST /api/engineering/readiness', 'POST /api/engineering/delivery-estimate'],
    terms: ['Gate'],
  },
  {
    id: 'missions', area: 'build', title: 'Missões e a empresa virtual',
    summary: 'O que acontece depois que um projeto vai para a Meta-Fábrica, e como acompanhar ao vivo.',
    screens: [{ id: 'P-MSL', label: 'Missões', current: '/jobs' }, { id: 'P-MSN', label: 'Mission Command Center', current: '/meta-factory' }],
    what: 'Uma missão é uma execução de geração da Meta-Fábrica para um projeto. Uma empresa virtual é montada para ela — equipes, posições e especialistas — e percorre as etapas do pipeline até a missão terminar READY ou FAILED, ou ser pausada.',
    why: 'Gerar um projeto inteiro é um trabalho longo, com muitas mãos. Ver quem fez cada etapa, por que foi escolhido e o que produziu é o que torna o resultado verificável.',
    how: ['Envie um projeto aprovado para a Meta-Fábrica; a missão começa com um id próprio.', 'A empresa é montada a partir da taxonomia de papéis; cada contratação registra o motivo e cada recusa, o código.', 'Acompanhe as etapas ao vivo: o stream retoma de onde parou, e nada se mexe quando nenhum evento chega.', 'Quando a missão termina, abra a evidência: gates, sessões de teste e a decisão de entrega.'],
    give: 'Um projeto com revisão de engenharia e stack aprovadas.',
    get: 'Código gerado, o registro de cada etapa, tokens e custo estimado, e os gates que a missão passou ou não.',
    who: ['Chief orchestrator — planeja e audita a empresa', 'Especialistas por posição, cada um com a sua certificação'],
    limits: ['Um projeto web com backend e frontend roda 37 etapas; outros alvos têm o seu próprio conjunto.', 'Retomar só é oferecido a partir de PAUSED ou STALLED, e uma etapa não pode ser repetida enquanto roda.', 'Os gates obrigatórios chegam pelo stream ao vivo, não pela leitura do job (lacuna G2).'],
    good: ['Leia as recusas da empresa: um CERTIFICATION_GAP explica por que uma posição foi preenchida de outro jeito.', 'Compare uma missão que falhou com a tentativa seguinte, em vez de começar do zero.'],
    trouble: [['A missão parou de avançar', 'Abra o Mission Command Center: o stream mostra a última etapa, e Retomar aparece quando o estado permite.'], ['Uma etapa de build falhou', 'Abra a etapa para ler o erro e o que o reparo automático tentou antes de parar.']],
    api: ['GET /api/meta-factory/jobs', 'GET /api/meta-factory/jobs/{job_id}/events', 'GET /api/companies/by-job/{job_id}', 'GET /api/companies/by-job/{job_id}/assignments'],
    terms: ['Missão', 'Empresa virtual', 'Recusa de roteamento', 'Gate'],
  },
  {
    id: 'guided', area: 'build', from: 'wizard', title: 'Missões guiadas',
    summary: 'Comece por um dos 24 tipos de missão, num espaço passo a passo.',
    screens: [{ id: 'G-NEW', label: 'Começar', current: '/wizard' }],
    what: 'Uma missão guiada é uma unidade de trabalho técnico: você escolhe o tipo de missão, descreve o objetivo, e um espaço conduz você pelas etapas com o especialista certo em cada uma.',
    why: 'Nem todo problema precisa de um projeto inteiro. Às vezes você só precisa diagnosticar um erro, planejar uma infraestrutura ou comparar soluções sem montar tudo.',
    how: ['Escolha um tipo de missão — criar, analisar, corrigir, evoluir, planejar ou pesquisar.', 'Descreva o objetivo; cada etapa pede só o que precisa.', 'Aceite, altere ou responda às propostas da IA etapa por etapa; cada decisão fica registrada com a origem.', 'Compile os entregáveis; quando for preciso construir código, a missão passa para uma Project Room.'],
    give: 'Um objetivo em texto e respostas para cada etapa.',
    get: 'Um plano e os entregáveis do tipo de missão — e uma Project Room quando houver engenharia.',
    who: ['Roteador de missões — classifica o pedido', 'Um especialista por etapa, por exemplo security_engineer em Segurança'],
    files: ['Plano da missão', 'Entregáveis do tipo de missão'],
    limits: ['Uma missão cobre um escopo; não substitui um projeto completo.', 'Etapas que escrevem conteúdo precisam de uma chave de IA configurada (BYOK).'],
    good: ['Descreva o objetivo com contexto: o quê e para quem.', 'Prefira uma missão por problema.'],
    trouble: [['O plano saiu genérico', 'Volte e detalhe o objetivo — mais contexto gera um plano mais específico.']],
    faq: [['Preciso ter um projeto antes?', 'Não. Uma missão pode nascer de um objetivo solto.']],
    api: ['GET /api/missions/registry', 'POST /api/missions', 'POST /api/missions/{mission_id}/ai-action', 'POST /api/missions/{mission_id}/decisions'],
    terms: ['Missão guiada'],
  },
  {
    id: 'changes', area: 'build', title: 'Workbench e mudanças',
    summary: 'Leia o código gerado com a sua procedência, e mude-o por pedidos que você revisa.',
    screens: [{ id: 'P-WBN', label: 'Engineering Workbench', current: '/projects' }, { id: 'P-CHG', label: 'Mudanças', current: '/change-requests' }],
    what: 'O workbench mostra cada arquivo gerado com o papel que o escreveu, o requisito que atende e os gates que o provam. Mudanças nesse código passam por Change Requests: um pedido versionado, um diff que você revisa e uma etapa de aplicação.',
    why: 'Editar código gerado à mão quebra a ligação entre um requisito e o arquivo que o implementa. Um Change Request mantém essa ligação e torna cada mudança revisável.',
    how: ['Abra um arquivo para ver o papel autor, o requisito e os gates.', 'Peça uma mudança; ela vira um Change Request com id próprio.', 'Revise o diff arquivo por arquivo.', 'Avance o pedido um passo permitido de cada vez até ele ser aplicado.'],
    give: 'A descrição da mudança, num projeto gerado.',
    get: 'Um diff revisado e aplicado ao projeto, com histórico.',
    limits: ['Cada ação só é permitida a partir de um status; as outras aparecem como indisponíveis, com o motivo.', 'A aplicação é recusada quando os arquivos mudaram depois de o diff ser gerado, em vez de sobrescrevê-los.'],
    good: ['Um objetivo por Change Request.', 'Leia o diff inteiro antes de aceitar.'],
    trouble: [['A aplicação foi recusada porque os arquivos mudaram', 'Alguém ou algo mudou esses arquivos depois do diff. Revise os arquivos atuais antes de tentar de novo.']],
    api: ['GET /api/change-requests/{change_request_id}/diff', 'GET /api/meta-factory/{project_id}/endpoints', 'POST /api/meta-factory/{project_id}/terminal/execute'],
    terms: ['Change Request', 'Patch'],
  },
  {
    id: 'verification', area: 'build', from: 'engineering-laboratory', title: 'Build & Test Room',
    summary: 'Prove que o projeto gerado compila, sobe e passa nos testes — de verdade.',
    screens: [{ id: 'P-BLD', label: 'Build & Test Room', current: '/test-room' }, { id: 'LAB', label: 'Engineering Laboratory', current: '/engineering-laboratory' }],
    what: 'A Build & Test Room roda o projeto gerado num sandbox isolado: compila, inicia, confere a saúde e executa os testes, registrando cada resultado como evidência.',
    why: '“Compila” não é o mesmo que “funciona”. Só a execução real prova que um sistema gerado funciona.',
    how: ['Rode a Test Room para o projeto.', 'Acompanhe as fases de build, inicialização, saúde e testes enquanto rodam.', 'Leia a saída real de cada comando, não um resumo.', 'Uma sessão aprovada vira a prova em que os gates de entrega se apoiam.'],
    give: 'Um projeto gerado.',
    get: 'Sessões de teste com gates, comandos e saída — e a prova que a entrega usa.',
    who: ['Ferramentas determinísticas — build, testes, auditoria de dependências', 'Reparo por IA só para falhas sem correção conhecida'],
    files: ['Sessão da Test Room', 'Relatório de auditoria de API em runtime', 'Relatório de teste funcional no navegador'],
    limits: ['Precisa de um projeto gerado.', 'Execução real leva tempo real.', 'A auditoria de API em runtime cobre só projetos Python/FastAPI.'],
    good: ['Rode os testes antes de confiar em qualquer entrega, mesmo uma que pareça pronta.', 'Use os comandos permitidos do terminal — eles rodam dentro do sandbox do projeto.'],
    trouble: [['Um teste falhou e o motivo não está claro', 'Abra a sessão: ela mostra o comando exato e a saída.']],
    faq: [['O terminal é simulado?', 'Não. Os comandos rodam de verdade no workspace gerado, dentro de um sandbox isolado.']],
    api: ['GET /api/test-room/{project_id}/proof', 'POST /api/meta-factory/{project_id}/terminal/execute', 'POST /api/meta-factory/{project_id}/runtime-functional-test'],
    terms: ['Evidência', 'Build'],
  },
  {
    id: 'modernize', area: 'build', from: 'modernize · auto-fix', title: 'Modernizar um código existente',
    summary: 'Importe o código que você já tem, entenda-o e aplique um plano aprovado com risco controlado.',
    screens: [{ id: 'P-MOD', label: 'Modernização', current: '/modernize' }, { id: 'FIX', label: 'Auto-Fix', current: '/auto-fix' }],
    what: 'A modernização analisa um projeto real enviado por ZIP ou URL de Git, propõe um plano e só aplica as correções depois da sua aprovação — revalidando tudo no fim.',
    why: 'A maior parte do software do mundo já existe e precisa evoluir; recomeçar do zero raramente é a resposta certa.',
    how: ['Importe o código por ZIP ou pelo Git.', 'Leia a análise: dependências, vulnerabilidades, qualidade e risco.', 'Aprove o plano, deixando de fora qualquer correção que você não queira.', 'As correções são aplicadas, e o projeto é revalidado e fica pronto para exportar.'],
    give: 'Um projeto existente, por upload de ZIP ou URL de Git.',
    get: 'O mesmo sistema, modernizado e revalidado, com um relatório e um diff por mudança.',
    who: ['IA de refatoração', 'Correções determinísticas por modelo; reparo por IA onde não há modelo'],
    files: ['Relatório de modernização', 'Um diff por mudança proposta', 'O projeto revalidado, pronto para exportar'],
    limits: ['Um código importado nunca vira missão: o ciclo de vida dele é o pipeline de modernização.', 'A profundidade da análise depende de a stack ser uma das suportadas pelo motor.'],
    good: ['Envie o repositório inteiro, não uma parte — a análise precisa do contexto.', 'Leia a análise antes de aprovar o plano.'],
    trouble: [['A análise não reconheceu a stack', 'Confira as stacks suportadas antes de importar de novo.']],
    faq: [['Isso reescreve o projeto inteiro?', 'Não. O plano é incremental e cada mudança pode ser revisada antes de ser aplicada.'], ['Posso fazer perguntas sobre o código?', 'Sim. A tela de modernização responde com base na análise.']],
    api: ['POST /api/modernize/projects/upload', 'POST /api/modernize/projects/git', 'POST /api/modernize/{project_id}/analyze', 'POST /api/modernize/{project_id}/approve-plan', 'POST /api/modernize/{project_id}/apply-fixes', 'POST /api/modernize/ask'],
    terms: ['Patch'],
  },
];
