import type { Guide } from '../types';

/* Áreas “Verificar e entregar”, “Biblioteca e estúdios” e “Seu trabalho e sua conta”. */
export const GUIDES_B: readonly Guide[] = [
  {
    id: 'runtime', area: 'ship', title: 'Preview e staging',
    summary: 'Rode o sistema gerado, olhe dentro dele e coloque-o em staging com caminho de volta.',
    screens: [{ id: 'P-RUN', label: 'Runtime Control Room', current: '/projects' }],
    what: 'A Runtime Control Room inicia um preview ao vivo do projeto gerado, mostra o console e os erros do que está rodando e publica uma versão em staging com verificação de saúde e rollback.',
    why: 'Um projeto que você não consegue rodar é um projeto que você não consegue julgar. Vê-lo rodar — com os erros — antes da entrega faz parte da prova.',
    how: ['Inicie o preview: o frontend e o backend do projeto sobem isolados.', 'Use o app no preview e acompanhe o painel de console e erros.', 'Tire um screenshot, ou reinicie um dos lados, quando precisar.', 'Publique em staging; a verificação de saúde mostra se a versão responde, e o rollback volta para a anterior.'],
    give: 'Um projeto gerado numa stack suportada.',
    get: 'Um preview rodando, a saída do console, screenshots e uma versão em staging com a sua saúde.',
    limits: ['Preview e staging suportam hoje Python/FastAPI com Next.js/React e PostgreSQL.', 'Um preview parado é encerrado automaticamente.', 'A tela mostra só as partes que o backend informa — nunca um banco, uma latência ou uma contagem de reinícios inventados.'],
    good: ['Abra o preview depois de toda missão que termina READY, antes de entregar.', 'Deixe o painel de console aberto enquanto testa o fluxo principal.'],
    trouble: [['O preview parou sozinho', 'Previews param depois de um tempo sem atividade. Inicie de novo.'], ['O staging falhou na verificação de saúde', 'Abra os logs do staging para ver qual serviço não respondeu, e faça rollback se houver uma versão anterior.']],
    api: ['GET /api/live-preview/{session_id}/console', 'POST /api/live-preview/{session_id}/screenshot'],
    terms: ['Preview', 'Runtime', 'Deploy'],
  },
  {
    id: 'evidence', area: 'ship', title: 'Evidência: por que está READY?',
    summary: 'Siga qualquer veredito até os fatos que o produziram.',
    screens: [{ id: 'P-EVD', label: 'Evidence Graph', current: '/meta-factory' }, { id: 'P-GOV', label: 'Governança', current: '/meta-factory' }],
    what: 'Todo veredito sobre um projeto — fase do kernel, certificação do produto, gate de qualidade, verificação do chief, elegibilidade de entrega — está ligado aos registros por trás dele. O grafo de evidência vai de um requisito até o comando que o provou.',
    why: 'Um READY sem prova é só uma afirmação. A promessa da plataforma é que você mesmo pode conferir cada afirmação.',
    how: ['Escolha um veredito e pergunte por quê.', 'Siga o caminho: o requisito, o job que o implementou, a execução do agente, os arquivos escritos, os gates e a sessão de teste.', 'Abra qualquer nó para ler o registro — quem, quando, resultado, código de saída.', 'A governança mostra se a execução ficou dentro do escopo, da trava do prompt e da stack aprovada.'],
    give: 'Um projeto com pelo menos uma missão.',
    get: 'A cadeia de evidência de cada veredito, e a auditoria da orquestração.',
    limits: ['Os vereditos nunca viram uma nota média; cada um mantém a sua fonte.', 'Os gates obrigatórios de um job chegam pelo stream ao vivo (lacuna G2).'],
    good: ['Antes de entregar, siga um requisito de ponta a ponta pelo menos uma vez.', 'Quando um veredito surpreender, leia a evidência antes de qualquer outra coisa.'],
    trouble: [['Um nó não tem evidência', 'A etapa não registrou prova. Aparece como Desconhecido ou Não executado — nunca como provado.']],
    api: ['GET /api/test-room/{project_id}/proof', 'GET /api/companies/by-job/{job_id}/chief', 'GET /api/chief-orchestrator/{project_id}/audit-log'],
    terms: ['Evidência', 'Gate', 'READY'],
  },
  {
    id: 'delivery', area: 'ship', title: 'Entregar um projeto',
    summary: 'Quando um projeto pode ser entregue, como você o recebe e o que exatamente recebe.',
    screens: [{ id: 'P-DLV', label: 'Delivery Center', current: '/meta-factory' }, { id: 'A-GIT', label: 'Integrações', current: '/settings' }],
    what: 'O Delivery Center diz se o projeto pode ser entregue e oferece só as opções que o backend permite: baixar um ZIP, exportar para um repositório Git ou mantê-lo no LDCN OS.',
    why: 'A entrega é quando o projeto sai da plataforma. Uma pessoa decide, e só depois que os gates permitem.',
    how: ['Confira a elegibilidade: tudo o que bloqueia a entrega aparece primeiro, com o motivo.', 'Escolha o modo de entrega.', 'Para Git, escolha um provedor conectado e o repositório; a exportação mostra o progresso.', 'A entrega fica registrada com o modo e o horário.'],
    give: 'Uma missão que terminou READY, e a sua decisão de como receber.',
    get: 'Um ZIP, uma exportação para Git ou o projeto mantido na plataforma — com a evidência que permitiu.',
    limits: ['A elegibilidade falha fechada: o que não pode ser verificado mantém a entrega bloqueada.', 'Exportar para Git exige um provedor conectado em Integrações.', 'Só opções reais são oferecidas; não há hospedagem gerenciada em nuvem.'],
    good: ['Leia os motivos de elegibilidade mesmo quando a entrega está liberada.', 'Conecte o provedor Git antes de a missão terminar.'],
    trouble: [['A entrega está bloqueada', 'Abra o motivo listado: ele diz qual gate ou verificação falhou, com a evidência.'], ['A exportação para Git falhou', 'Confira a conexão do provedor e a permissão no repositório em Integrações, e exporte de novo.']],
    api: ['GET /api/meta-factory/{project_id}/delivery', 'POST /api/git/export/github', 'GET /api/git/export/status/{export_id}'],
    terms: ['Deploy', 'Gate'],
  },
  {
    id: 'memory', area: 'ship', from: 'documentation', title: 'Memória do projeto e documentação',
    summary: 'O que a plataforma sabe sobre o seu projeto, e uma documentação que bate com o que foi construído.',
    screens: [{ id: 'P-MEM', label: 'Memória e documentação', current: '/documentation' }],
    what: 'A memória do projeto guarda os fatos que a plataforma registrou sobre ele e usa nas etapas seguintes. A biblioteca de documentação pontua os documentos contra o que foi realmente construído, e um redator de IA escreve as seções que faltam.',
    why: 'Documentação que não bate com o código é pior do que nenhuma, e uma memória que deixou de ser verdade engana todas as etapas que a leem.',
    how: ['Leia o que a plataforma lembra sobre o projeto.', 'Corrija uma memória errada, ou apague uma que não vale mais.', 'Confira a pontuação da documentação e as seções marcadas como ausentes.', 'Peça ao redator de IA o que falta, e exporte a documentação.'],
    give: 'Um projeto com arquivos gerados.',
    get: 'Memórias corrigidas, e uma documentação pontuada que você pode exportar.',
    who: ['AI Writer — escreve a partir dos arquivos reais do projeto'],
    files: ['Documentos exportáveis'],
    limits: ['A pontuação reflete o que existe no projeto; nada que não foi construído é documentado.', 'As memórias pertencem ao projeto; o que as equipes aprendem fica na Biblioteca.'],
    good: ['Peça ao redator só o que falta, em vez de regenerar tudo.', 'Revise as memórias depois de uma mudança grande.'],
    trouble: [['A pontuação da documentação está baixa', 'Abra as seções marcadas como ausentes e peça ao redator de IA para preenchê-las.']],
    faq: [['O redator de IA inventa conteúdo?', 'Não. Ele escreve a partir dos arquivos reais gerados do projeto.']],
    api: ['GET /api/project-rooms/{room_id}/memories', 'GET /api/projects/{project_id}/documentation', 'POST /api/projects/{project_id}/documentation/generate', 'POST /api/projects/{project_id}/documentation/export'],
    terms: ['Memória', 'Contexto'],
  },
  {
    id: 'templates', area: 'library', from: 'skills · library · marketplace', title: 'Templates, habilidades e marketplace',
    summary: 'Comece de algo já resolvido, e veja que especialistas existem antes de pedir.',
    screens: [{ id: 'L-TPL', label: 'Templates e habilidades', current: '/templates' }, { id: 'L-MKT', label: 'Marketplace', current: '/marketplace' }],
    what: 'Templates são pontos de partida reutilizáveis, conferidos quanto à compatibilidade com o seu blueprint. Habilidades são as capacidades de especialistas que a plataforma pode acionar. O marketplace oferece modelos de automação publicados para reúso.',
    why: 'Muitos padrões já foram resolvidos antes. Reaproveitar um padrão validado é mais rápido e mais seguro do que reescrever.',
    how: ['Explore os templates e abra um para ver o que ele cobre.', 'Rode a verificação de compatibilidade com o blueprint do seu projeto.', 'Pré-visualize uma habilidade para ver o que ela produziria.', 'Instale uma automação do marketplace e configure-a em Automações.'],
    give: 'Um blueprint de projeto para comparar, ou uma tarefa para automatizar.',
    get: 'Um ponto de partida compatível, uma habilidade pré-visualizada ou uma automação instalada.',
    limits: ['Nem todo template serve para toda stack — a verificação de compatibilidade lista o que falta.', 'O marketplace só tem modelos de automação.'],
    good: ['Confira a compatibilidade antes de aplicar um template.', 'Trate um template como ponto de partida, não como solução pronta.'],
    trouble: [['Um template não é compatível com o projeto', 'Leia o resultado da compatibilidade: ele lista o que bateu, o que falta e os avisos.']],
    api: ['GET /api/templates/catalog', 'GET /api/templates/{template_id}/compatibility', 'GET /api/skills', 'POST /api/skills/preview', 'GET /api/marketplace/items', 'POST /api/marketplace/items/{item_id}/install'],
    terms: ['Skill', 'Capability'],
  },
  {
    id: 'certification', area: 'library', title: 'Certificação e a workforce',
    summary: 'O que foi realmente provado, por qual suíte executada, e que papéis podem ser preenchidos.',
    screens: [{ id: 'W-DIR', label: 'Workforce', current: '/workforce' }],
    what: 'A certificação registra o que uma suíte executada provou para uma stack, um agente ou uma composição de apps. A workforce mostra a taxonomia de papéis e quais podem ser preenchidos hoje, e o planejador monta a empresa que uma stack e um perfil de risco exigiriam.',
    why: 'Confiar num projeto gerado começa por confiar em quem o construiu e com o quê. Uma certificação que você pode abrir vale mais do que uma promessa.',
    how: ['Abra um registro para ver as verificações, quando rodou e o veredito.', 'Compare stacks, agentes e composições — cada um mantém o seu resultado.', 'Na workforce, veja que papéis têm agentes certificados.', 'Use o planejador para montar uma empresa para uma stack e achar as lacunas antes que uma missão ache.'],
    give: 'Nada para ler os registros; uma stack e um perfil de risco para planejar.',
    get: 'Vereditos com as suas verificações, e um plano de empresa com as suas lacunas.',
    limits: ['Os resultados nunca viram uma média.', 'Algumas execuções de certificação só podem ser iniciadas pela API hoje.'],
    good: ['Confira quando uma certificação rodou: uma execução antiga prova uma versão antiga.', 'Planeje a workforce antes de uma missão numa stack incomum.'],
    trouble: [['Um papel não tem agente certificado', 'Uma missão pode preenchê-lo de outro jeito e registrar uma recusa CERTIFICATION_GAP; o planejador mostra essa lacuna antes.']],
    api: ['GET /api/registry/stack-certifications', 'GET /api/workforce/cognitive-certifications', 'GET /api/workforce/compositions', 'POST /api/workforce/plan'],
    terms: ['Certificação', 'Recusa de roteamento'],
  },
  {
    id: 'data', area: 'library', from: 'data-intelligence', title: 'Data Studio',
    summary: 'Traga um conjunto de dados e uma pergunta; receba dados tratados, análise e relatório, um passo aprovado de cada vez.',
    screens: [{ id: 'S-DATA', label: 'Data Studio', current: '/data-intelligence' }],
    what: 'Uma sessão de dados leva o seu próprio conjunto de dados pela ingestão, perfil, limpeza, análise, relatório e monitoramento. Cada etapa é executada por um agente e diz se terminou com IA ou de forma determinística.',
    why: 'Dados de negócio precisam ser entendidos e limpos antes de qualquer conclusão ser confiável — e a limpeza precisa ser algo que você aprova.',
    how: ['Descreva o objetivo e confirme como a sessão o entendeu.', 'Envie a fonte de dados.', 'Revise o perfil e aprove o plano de limpeza.', 'Acompanhe a análise e o relatório, e configure o monitoramento.'],
    give: 'Um arquivo CSV, TSV ou JSON e um objetivo de análise.',
    get: 'Um conjunto de dados tratado, insights com a sua confiança, dashboards e relatórios exportáveis.',
    who: ['Um agente por etapa — classificação, qualidade, governança, análise'],
    limits: ['Etapas que precisam de modelo usam a sua chave de IA.', 'Etapas longas rodam como jobs em segundo plano; a sessão mostra o progresso.'],
    good: ['Escreva o objetivo como uma pergunta de negócio.', 'Leia o plano de limpeza antes de aprovar — ele altera os dados.'],
    trouble: [['Uma etapa aparece como BLOCKED', 'Ela está esperando uma aprovação ou uma etapa anterior; a sessão diz o que está esperando.']],
    api: ['POST /api/data-intelligence/sessions'],
    terms: ['Execution'],
  },
  {
    id: 'automations', area: 'library', title: 'Automações',
    summary: 'Um gatilho e uma requisição HTTP que rodam por você, com o histórico de cada execução.',
    screens: [{ id: 'S-AUTO', label: 'Automações', current: '/automations' }, { id: 'L-MKT', label: 'Marketplace', current: '/marketplace' }],
    what: 'Uma automação é um gatilho manual ou agendado seguido de uma requisição HTTP. Cada execução fica registrada com o seu status, e as credenciais são só de escrita.',
    why: 'Pequenas tarefas recorrentes não deveriam precisar de um projeto inteiro — e tudo o que roda por você precisa deixar rastro.',
    how: ['Crie a automação, ou instale um modelo do marketplace.', 'Escolha o gatilho: manual, ou um agendamento cron com o fuso horário.', 'Configure a requisição; as credenciais são guardadas e nunca mais exibidas.', 'Rode agora ou ative, e leia o histórico de execuções.'],
    give: 'Um endpoint para chamar, e quando chamar.',
    get: 'Execuções agendadas ou sob demanda, cada uma registrada com o resultado.',
    limits: ['Um gatilho e uma requisição HTTP por automação.', 'As credenciais não podem ser lidas de volta — substitua-as.'],
    good: ['Rode manualmente uma vez antes de ativar o agendamento.', 'Pause uma automação que talvez volte a usar, em vez de arquivá-la.'],
    trouble: [['Uma execução falhou', 'Abra o histórico: cada execução guarda o status e quando rodou.']],
    api: ['POST /api/automations'],
    terms: ['Execution', 'Evento'],
  },
  {
    id: 'projects', area: 'account', from: 'projects · jobs', title: 'Projetos e o seu histórico',
    summary: 'Encontre qualquer projeto, veja em que fase está e reabra o que já foi gerado.',
    screens: [{ id: 'G-PRJ', label: 'Projetos', current: '/projects' }, { id: 'P-MSL', label: 'Missões', current: '/jobs' }],
    what: 'Projetos lista tudo o que você está construindo — salas ainda em definição, projetos gerando, READY ou com falha — com o estado de cada um. Dentro de um projeto, Missões guarda cada execução de geração, inclusive as que falharam e as arquivadas; Atividade guarda os eventos de toda a conta.',
    why: 'Um trabalho começado há semanas precisa ser fácil de achar, e uma geração concluída nunca deveria precisar ser refeita para ser vista de novo.',
    how: ['Filtre os projetos por fase, ou busque pelo nome.', 'Abra um projeto para cair no cockpit e no passo atual.', 'Em Missões, abra qualquer execução passada com a sua evidência; as arquivadas continuam disponíveis.', 'Use Atividade para ver o que aconteceu, quando e o que causou.'],
    give: 'Nada — todo projeto criado na plataforma aparece aqui.',
    get: 'Um registro pesquisável com o estado real de cada projeto e das suas execuções.',
    limits: ['É um registro: não inicia nada sozinho.', 'Projetos arquivados ficam ocultos até você filtrar por eles.'],
    good: ['Busque pelo nome em vez de rolar a lista.', 'Arquive execuções que não usa mais, em vez de excluí-las.'],
    trouble: [['Um projeto que você criou não aparece', 'Confira o filtro de fase — projetos arquivados ficam ocultos por padrão.'], ['Uma execução antiga sumiu da lista', 'Ela foi arquivada. Mostre as execuções arquivadas em Missões.']],
    api: ['GET /api/projects', 'GET /api/meta-factory/jobs', 'PATCH /api/meta-factory/jobs/{job_id}/archive', 'GET /api/activity-feed'],
    terms: ['Projeto', 'Missão', 'Evento'],
  },
  {
    id: 'plan', area: 'account', from: 'pricing', title: 'Planos, trial e uso',
    summary: 'O que o seu plano permite, quão perto você está dos limites e como funciona o trial.',
    screens: [{ id: 'A-PLAN', label: 'Plano e uso', current: '/settings' }, { id: 'U-PRICE', label: 'Preços', current: '/pricing' }],
    what: 'O seu plano define limites — projetos ativos, workspaces, membros, instâncias de preview, armazenamento — e os recursos que você pode usar. Plano e uso mostra a assinatura, o trial e o uso medido do período atual.',
    why: 'Você deveria poder decidir sobre um plano sabendo exatamente o que muda, sem precisar perguntar ao suporte.',
    how: ['Veja o plano atual e o seu status.', 'Compare o uso do período com cada limite.', 'Compare os planos lado a lado em Preços.', 'Troque de plano; estudantes podem comprovar a matrícula para o plano estudante.'],
    give: 'Nada para ler; uma decisão para trocar de plano.',
    get: 'Limites, uso e status da assinatura, claros.',
    limits: ['Os planos não incluem créditos de IA; o uso de IA é cobrado pelo seu provedor.', 'O trial dura 72 horas a partir da criação da conta.', 'Quando o catálogo não define preço para um plano, a página diz isso em vez de adivinhar.'],
    good: ['Confira o uso antes de começar uma missão grande.', 'Compare os limites, não só os preços.'],
    trouble: [['Uma ação diz que o plano não permite', 'Plano e uso mostra qual recurso ou limite bloqueou.']],
    api: ['GET /api/billing/plans', 'GET /api/billing/subscription', 'GET /api/billing/trial', 'GET /api/billing/entitlements', 'GET /api/billing/usage'],
    terms: ['Plano Estudante', 'Elegibilidade estudantil'],
  },
  {
    id: 'account', area: 'account', from: 'settings', title: 'Conta, segurança e workspaces',
    summary: 'Mantenha a conta segura, veja onde ela está conectada e controle quem pode fazer o quê.',
    screens: [{ id: 'A-ACC', label: 'Conta e segurança', current: '/settings' }, { id: 'A-WS', label: 'Workspace e acesso', current: '/settings' }],
    what: 'Conta e segurança reúne o seu perfil, a senha, a configuração de dois fatores, as sessões ativas, o consentimento e a exportação de dados. Workspace e acesso reúne membros, papéis e a matriz de permissões. Preferências guardam idioma, interface e padrões.',
    why: 'Uma conta que constrói e entrega software merece o mesmo cuidado que o software: sessões conhecidas, permissões claras e controle sobre os seus dados.',
    how: ['Revise as sessões ativas e encerre as que você não reconhece.', 'Configure a autenticação de dois fatores com um app autenticador.', 'Dê a cada membro o menor papel que resolve, e leia por que uma permissão foi concedida.', 'Escolha idioma e preferências de interface; elas ficam salvas na sua conta.'],
    give: 'As suas decisões sobre segurança, pessoas e preferências.',
    get: 'Uma conta mais segura, permissões claras e preferências que persistem.',
    limits: ['A autenticação de dois fatores pode ser ativada, mas a entrada ainda não pede o código (lacuna G14).', 'Ainda não existe redefinição de senha por e-mail (lacuna G15).', 'As explicações de permissão chegam em português.'],
    good: ['Revise as sessões depois de entrar num computador compartilhado.', 'Exporte os seus dados antes de encerrar a conta.'],
    trouble: [['Um membro não consegue fazer uma ação', 'Abra a explicação de permissão para essa ação e papel: ela diz qual regra valeu.']],
    api: ['GET /api/auth/me/sessions', 'POST /api/auth/me/2fa/enroll', 'GET /api/workspaces', 'GET /api/permissions/explain', 'PUT /api/users/me/preferences/interface'],
    terms: ['Workspace'],
  },
  {
    id: 'platform', area: 'account', from: 'system-status · analytics · roadmap', title: 'Saúde da plataforma e roadmap',
    summary: 'Se a própria plataforma está saudável, por que os modelos foram escolhidos e o que está planejado.',
    screens: [{ id: 'X-HLT', label: 'Saúde da plataforma', current: '/system-status' }, { id: 'X-RMP', label: 'Roadmap', current: '/roadmap' }],
    what: 'A saúde da plataforma reúne o status do sistema, a telemetria de runtime e as métricas de uso. Os rastros de decisão de IA mostram por que o roteador escolheu cada modelo e quanto custou. O roadmap mostra o que está implementado, em andamento e planejado.',
    why: 'Quando algo está lento ou falhando, você precisa saber se o problema é o seu projeto ou a plataforma.',
    how: ['Confira cada sinal; um degradado diz o que foi afetado.', 'Acompanhe a telemetria de runtime ao vivo.', 'Abra um rastro de decisão para ver as alternativas, o contexto, os tokens e o custo.', 'Leia o roadmap para calibrar expectativas.'],
    give: 'Nada — são leituras.',
    get: 'A saúde real da plataforma e os motivos por trás da escolha dos modelos.',
    limits: ['Um componente de telemetria sem coletor aparece como desconhecido, nunca como saudável.', 'O roadmap é um plano governado, não um compromisso de data.', 'A configuração de runtime é só para administradores.'],
    good: ['Confira a saúde da plataforma antes de dizer que um problema é do seu projeto.', 'Leia os rastros de decisão quando os custos surpreenderem.'],
    trouble: [['Um sinal está degradado', 'Abra-o: o status diz o componente e a mensagem que o backend devolveu.']],
    api: ['GET /api/system-status', 'GET /api/runtime/telemetry', 'GET /api/analytics/overview', 'GET /api/observability/decisions', 'GET /api/roadmap'],
    terms: ['Runtime', 'Evento'],
  },
];
