'use client';

import { Activity, Download, RefreshCw, Search, X } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import { useState } from 'react';

import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { useLocale } from '@/hooks/use-locale';
import { apiRequest } from '@/lib/api/client';
import { apiEndpoints } from '@/lib/api/endpoints';

type ActivityItem = { id: string; category: string; action: string; status: string; occurred_at: string; source: string; correlation_id: string; metadata: Record<string, unknown> };
type ActivityResponse = { items: ActivityItem[]; next_cursor: string | null; has_more: boolean };

function queryString(params: URLSearchParams) { return params.toString() ? `?${params.toString()}` : ''; }

const STATUS_LABEL_KEY: Record<string, string> = {
  success: 'settings.activityFeed.status.success',
  failure: 'settings.activityFeed.status.failure',
  requested: 'settings.activityFeed.status.requested',
};

export function ActivityFeed() {
  const { t, locale } = useLocale();
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [search, setSearch] = useState(searchParams.get('activity_q') ?? '');
  const category = searchParams.get('activity_category') ?? ''; const status = searchParams.get('activity_status') ?? ''; const cursor = searchParams.get('activity_cursor') ?? '';
  const selectedId = searchParams.get('activity_event') ?? '';
  const query = useQuery({ queryKey: ['settings', 'activity-feed', category, status, searchParams.get('activity_q') ?? '', cursor], queryFn: () => { const params = new URLSearchParams({ limit: '25' }); if (category) params.set('category', category); if (status) params.set('status', status); if (searchParams.get('activity_q')) params.set('search', searchParams.get('activity_q')!); if (cursor) params.set('cursor', cursor); return apiRequest<ActivityResponse>(`${apiEndpoints.activityFeed}${queryString(params)}`); }, staleTime: 10_000 });
  const detail = useQuery({ queryKey: ['settings', 'activity-event', selectedId], queryFn: () => apiRequest<ActivityItem>(apiEndpoints.activityFeedEvent(selectedId)), enabled: Boolean(selectedId), staleTime: 30_000 });
  const items = query.data?.items ?? [];
  const categories = Array.from(new Set(items.map((item) => item.category))).sort();
  const update = (name: string, value: string) => { const params = new URLSearchParams(searchParams.toString()); if (value) params.set(name, value); else params.delete(name); params.delete('activity_cursor'); router.replace(`${pathname}${queryString(params)}`, { scroll: false }); };
  const exportJson = async () => { const params = new URLSearchParams({ format: 'json' }); if (category) params.set('category', category); if (status) params.set('status', status); const data = await apiRequest<{ items: ActivityItem[] }>(`${apiEndpoints.activityFeedExport}?${params}`); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'ldcn-activity.json'; anchor.click(); URL.revokeObjectURL(url); };
  return <Card surface="secondary" className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="ds-overline text-[color:var(--accent)]">{t('settings.activityFeed.eyebrow')}</p><h2 className="mt-1 flex items-center gap-2 text-lg font-semibold text-[color:var(--text)]"><Activity className="h-4 w-4" aria-hidden /> {t('settings.activityFeed.title')}</h2><p className="mt-1 text-sm text-[color:var(--muted)]">{t('settings.activityFeed.description')}</p></div><div className="flex gap-2"><button type="button" onClick={() => void exportJson()} className="focus-ring inline-flex items-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--border)] px-3 py-2 text-xs" aria-label={t('settings.activityFeed.exportAria')}><Download className="h-3.5 w-3.5" aria-hidden /> {t('settings.activityFeed.exportJson')}</button><button type="button" onClick={() => void query.refetch()} className="focus-ring rounded-[var(--radius-md)] p-2 text-[color:var(--muted)]" aria-label={t('settings.activityFeed.refreshAria')}><RefreshCw className={`h-4 w-4 ${query.isFetching ? 'animate-spin' : ''}`} aria-hidden /></button></div></div>
    <form className="mt-5 grid gap-2 sm:grid-cols-[minmax(0,1fr)_10rem_10rem_auto]" onSubmit={(event) => { event.preventDefault(); update('activity_q', search.trim()); }}><label className="sr-only" htmlFor="activity-search">{t('settings.activityFeed.searchLabel')}</label><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-[color:var(--muted)]" aria-hidden /><input id="activity-search" name="activity-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('settings.activityFeed.searchPlaceholder')} className="focus-ring min-h-10 w-full rounded-[var(--radius-md)] border border-[color:var(--border)] bg-[color:var(--surface-3)] pl-9 pr-3 text-sm" /></div><select aria-label={t('settings.activityFeed.categoryAria')} value={category} onChange={(event) => update('activity_category', event.target.value)} className="focus-ring min-h-10 rounded-[var(--radius-md)] border border-[color:var(--border)] bg-[color:var(--surface-3)] px-3 text-sm"><option value="">{t('settings.activityFeed.allCategories')}</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label={t('settings.activityFeed.statusAria')} value={status} onChange={(event) => update('activity_status', event.target.value)} className="focus-ring min-h-10 rounded-[var(--radius-md)] border border-[color:var(--border)] bg-[color:var(--surface-3)] px-3 text-sm"><option value="">{t('settings.activityFeed.allStatuses')}</option><option value="success">{t('settings.activityFeed.status.success')}</option><option value="failure">{t('settings.activityFeed.status.failure')}</option><option value="requested">{t('settings.activityFeed.status.requested')}</option></select><button type="submit" className="focus-ring min-h-10 rounded-[var(--radius-md)] bg-[color:var(--accent)] px-4 text-sm font-semibold text-white">{t('settings.activityFeed.filter')}</button></form>
    <div aria-live="polite" className="mt-4">{query.isPending ? <p className="text-sm text-[color:var(--muted)]">{t('settings.activityFeed.loading')}</p> : query.isError ? <p className="text-sm text-[color:var(--danger)]">{t('settings.activityFeed.error')}</p> : items.length === 0 ? <p className="rounded-[var(--radius-md)] border border-dashed border-[color:var(--border)] p-4 text-sm text-[color:var(--muted)]">{t('settings.activityFeed.empty')}</p> : <div className="divide-y divide-[color:var(--border)]">{items.map((item) => <button type="button" key={item.id} onClick={() => update('activity_event', item.id)} className="focus-ring flex w-full items-center gap-3 py-3 text-left"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[color:var(--text)]">{item.action.replaceAll('_', ' ')}</p><p className="text-xs text-[color:var(--muted)]">{item.category} · {new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(item.occurred_at))}</p></div><Badge tone={item.status === 'success' ? 'success' : item.status === 'failure' ? 'danger' : 'warning'}>{STATUS_LABEL_KEY[item.status] ? t(STATUS_LABEL_KEY[item.status]) : item.status}</Badge></button>)}</div>}</div>
    {query.data?.has_more ? <button type="button" className="focus-ring mt-4 rounded-[var(--radius-md)] border border-[color:var(--border)] px-3 py-2 text-sm" onClick={() => update('activity_cursor', query.data?.next_cursor ?? '')}>{t('settings.activityFeed.loadMore')}</button> : null}
    {selectedId ? <div className="mt-4 rounded-[var(--radius-md)] border border-[color:var(--border)] bg-[color:var(--surface-3)] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{t('settings.activityFeed.eventDetail')}</p><button type="button" className="focus-ring" aria-label={t('settings.activityFeed.closeDetailAria')} onClick={() => update('activity_event', '')}><X className="h-4 w-4" aria-hidden /></button></div>{detail.isPending ? <p className="mt-3 text-sm text-[color:var(--muted)]">{t('settings.activityFeed.loadingDetail')}</p> : detail.isError ? <p className="mt-3 text-sm text-[color:var(--danger)]">{t('settings.activityFeed.detailError')}</p> : <pre className="mt-3 max-h-60 overflow-auto whitespace-pre-wrap break-words text-xs text-[color:var(--muted)]">{JSON.stringify(detail.data, null, 2)}</pre>}</div> : null}
  </Card>;
}
