const features = [
  'Clear static foundation',
  'Offline-first local output',
  'Template-driven assembly',
];

export default function Page() {
  return (
    <main className="page">
      <section className="hero">
        <p className="eyebrow">Next.js Static Landing</p>
        <h1>ldcn-local-landing</h1>
        <p className="lead">ldcn-local-landing generated from deterministic LDCN OS static foundations.</p>
        <a href="#contact" className="button">Start locally</a>
      </section>
      <section className="grid" aria-label="Foundation capabilities">
        {features.map((feature) => (
          <article key={feature}>
            <span />
            <h2>{feature}</h2>
            <p>Generated by LDCN OS with deterministic static templates only.</p>
          </article>
        ))}
      </section>
      <section id="contact" className="band">
        <h2>Scope</h2>
        <p>seo, analytics</p>
      </section>
    </main>
  );
}
