from __future__ import annotations

from typing import Literal

from pydantic import Field

from app.schemas.common import ApiModel


class GitExportRequest(ApiModel):
    provider: Literal["github", "gitlab"]
    repo_name: str = Field(min_length=1)
    namespace: str = Field(min_length=1)
    visibility: Literal["private", "public"] = "private"
    branch: str = Field(default="main", min_length=1)
    commit_message: str = Field(default="Initial commit generated by LDCN OS", min_length=1)
    project_id: str = Field(min_length=1)
    credential_reference: str | None = None
    temporary_token: str | None = Field(default=None, min_length=1)


class GitExportFileEntry(ApiModel):
    relative_path: str
    size_bytes: int
    checksum: str


class GitExportBlocker(ApiModel):
    code: str
    problem: str
    reason: str
    action_label: str
    action_href: str


class GitExportSecurityValidation(ApiModel):
    contractVersion: str
    status: Literal["safe", "filtered", "blocked"]
    message: str
    gatekeeper_decision: Literal["approved", "approved_with_warnings", "blocked"] | None = None
    blocked_files: list[str] = Field(default_factory=list)
    blocked_count: int
    redacted_fields: list[str] = Field(default_factory=list)
    contains_secrets: Literal[False] = False


class GitExportJob(ApiModel):
    contractVersion: str
    export_id: str
    provider: Literal["github", "gitlab"]
    repo_name: str
    namespace: str
    visibility: Literal["private", "public"]
    branch: str
    commit_message: str
    project_id: str
    status: Literal["pending", "validating", "exporting", "success", "failed", "blocked"]
    blockers: list[GitExportBlocker] = Field(default_factory=list)
    security_validation: GitExportSecurityValidation
    files_included: list[GitExportFileEntry] = Field(default_factory=list)
    repo_url: str | None = None
    requested_at: str
    completed_at: str | None = None
    failure_reason: str | None = None


class GitExportStatusResponse(ApiModel):
    contractVersion: str
    export_id: str
    status: Literal["pending", "validating", "exporting", "success", "failed", "blocked"]
    blockers: list[GitExportBlocker] = Field(default_factory=list)
    repo_url: str | None = None
    security_validation: GitExportSecurityValidation
    files_included: list[GitExportFileEntry] = Field(default_factory=list)
    failure_reason: str | None = None
