from __future__ import annotations

from collections.abc import Sequence

ARCHITECTURES: list[dict] = [
    {
        "id": "monolith",
        "name": "Monolith",
        "description": "Single deployable application with centralized execution flow.",
        "complexity_level": "low",
        "supported_frameworks": ["spring_boot", "nestjs", "nextjs", "react", "angular", "fastapi", "django", "flask", "aspnet_core", "blazor", "laravel", "fiber", "gin"],
        "required_capabilities": [],
        "recommended_capabilities": ["api_docs"],
        "scalability_profile": "team",
        "deployment_complexity": "low",
    },
    {
        "id": "modular_monolith",
        "name": "Modular Monolith",
        "description": "Single deployable with clear module boundaries and domain separation.",
        "complexity_level": "medium",
        "supported_frameworks": ["spring_boot", "quarkus", "micronaut", "nestjs", "nextjs", "angular", "react", "fastapi", "django", "aspnet_core", "blazor", "laravel", "fiber", "gin"],
        "required_capabilities": [],
        "recommended_capabilities": ["authentication", "api_docs", "observability"],
        "scalability_profile": "enterprise",
        "deployment_complexity": "medium",
    },
    {
        "id": "microservices",
        "name": "Microservices",
        "description": "Service-bounded architecture with isolated deployables and inter-service communication.",
        "complexity_level": "high",
        "supported_frameworks": ["spring_boot", "quarkus", "micronaut", "nestjs", "fastapi", "aspnet_core", "fiber", "gin"],
        "required_capabilities": ["docker"],
        "recommended_capabilities": ["observability", "queue", "ci_cd"],
        "scalability_profile": "hyperscale",
        "deployment_complexity": "very_high",
    },
    {
        "id": "event_driven",
        "name": "Event Driven",
        "description": "Asynchronous architecture built around events, streams and eventual consistency.",
        "complexity_level": "high",
        "supported_frameworks": ["spring_boot", "nestjs", "fastapi", "aspnet_core", "fiber", "gin"],
        "required_capabilities": ["queue"],
        "recommended_capabilities": ["observability", "cache"],
        "scalability_profile": "hyperscale",
        "deployment_complexity": "high",
    },
    {
        "id": "cqrs",
        "name": "CQRS",
        "description": "Command-query responsibility separation for high-governance business flows.",
        "complexity_level": "high",
        "supported_frameworks": ["spring_boot", "nestjs"],
        "required_capabilities": ["observability"],
        "recommended_capabilities": ["queue", "cache", "audit_logs"],
        "scalability_profile": "enterprise",
        "deployment_complexity": "high",
    },
    {
        "id": "serverless",
        "name": "Serverless",
        "description": "Function and event-oriented deployment model with platform-managed infrastructure.",
        "complexity_level": "medium",
        "supported_frameworks": ["nextjs", "express", "fastify", "fastapi", "flask", "laravel"],
        "required_capabilities": [],
        "recommended_capabilities": ["observability", "ci_cd"],
        "scalability_profile": "enterprise",
        "deployment_complexity": "medium",
    },
    {
        "id": "distributed_system",
        "name": "Distributed System",
        "description": "Multi-service or multi-runtime architecture with strong operational coordination needs.",
        "complexity_level": "very_high",
        "supported_frameworks": ["spring_boot", "nestjs", "fastapi", "aspnet_core", "fiber", "gin"],
        "required_capabilities": ["docker", "observability"],
        "recommended_capabilities": ["queue", "cache", "ci_cd"],
        "scalability_profile": "hyperscale",
        "deployment_complexity": "very_high",
    },
    {
        "id": "hexagonal",
        "name": "Hexagonal",
        "description": "Ports-and-adapters architecture emphasizing isolation from infrastructure concerns.",
        "complexity_level": "high",
        "supported_frameworks": ["spring_boot", "nestjs", "fastapi"],
        "required_capabilities": [],
        "recommended_capabilities": ["api_docs", "observability"],
        "scalability_profile": "enterprise",
        "deployment_complexity": "high",
    },
    {
        "id": "clean_architecture",
        "name": "Clean Architecture",
        "description": "Layered dependency-inverted architecture for long-lived maintainable systems.",
        "complexity_level": "high",
        "supported_frameworks": ["spring_boot", "nestjs", "nextjs", "react", "angular", "fastapi", "django", "aspnet_core", "laravel", "fiber", "gin"],
        "required_capabilities": [],
        "recommended_capabilities": ["api_docs", "observability", "authentication"],
        "scalability_profile": "enterprise",
        "deployment_complexity": "high",
    },
]


def get_architectures_registry() -> Sequence[dict]:
    return ARCHITECTURES
