from __future__ import annotations

from collections.abc import Sequence

ARCHETYPES: list[dict] = [
    {
        "id": "landing_page",
        "name": "Landing Page",
        "description": "Single-conversion marketing page focused on acquisition.",
        "category": "frontend",
        "supported_stacks": ["static_site", "nextjs", "react", "angular"],
        "recommended_stacks": ["static_site", "nextjs"],
        "default_capabilities": ["seo", "i18n"],
        "recommended_business_modules": ["notifications"],
        "default_endpoints": [],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US", "es-ES", "fr-FR"],
        "complexity_range": {"minimum": 1, "maximum": 2},
        "preview_type": "site",
    },
    {
        "id": "institutional_site",
        "name": "Institutional Site",
        "description": "Structured company website with credibility and content surfaces.",
        "category": "frontend",
        "supported_stacks": ["static_site", "nextjs", "react", "angular"],
        "recommended_stacks": ["nextjs", "static_site"],
        "default_capabilities": ["seo", "i18n"],
        "recommended_business_modules": ["notifications", "settings"],
        "default_endpoints": [],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US", "es-ES", "fr-FR"],
        "complexity_range": {"minimum": 1, "maximum": 2},
        "preview_type": "site",
    },
    {
        "id": "portfolio",
        "name": "Portfolio",
        "description": "Personal or agency showcase with project and contact emphasis.",
        "category": "frontend",
        "supported_stacks": ["static_site", "nextjs", "react", "angular"],
        "recommended_stacks": ["static_site", "nextjs"],
        "default_capabilities": ["seo"],
        "recommended_business_modules": ["notifications"],
        "default_endpoints": [],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 1, "maximum": 2},
        "preview_type": "site",
    },
    {
        "id": "blog",
        "name": "Blog",
        "description": "Editorial publishing surface with search and SEO expectations.",
        "category": "frontend",
        "supported_stacks": ["static_site", "nextjs", "react", "angular"],
        "recommended_stacks": ["nextjs", "static_site"],
        "default_capabilities": ["seo", "search", "i18n"],
        "recommended_business_modules": ["notifications"],
        "default_endpoints": [],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 1, "maximum": 3},
        "preview_type": "site",
    },
    {
        "id": "sales_page",
        "name": "Sales Page",
        "description": "High-conversion product or offer page with persuasion-oriented structure.",
        "category": "frontend",
        "supported_stacks": ["static_site", "nextjs", "react"],
        "recommended_stacks": ["static_site", "nextjs"],
        "default_capabilities": ["seo", "analytics"],
        "recommended_business_modules": ["notifications"],
        "default_endpoints": [],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 1, "maximum": 2},
        "preview_type": "site",
    },
    {
        "id": "catalog_site",
        "name": "Catalog Site",
        "description": "Product or content catalog with structured listing and search.",
        "category": "frontend",
        "supported_stacks": ["nextjs", "react", "angular"],
        "recommended_stacks": ["nextjs"],
        "default_capabilities": ["seo", "search", "analytics"],
        "recommended_business_modules": ["products"],
        "default_endpoints": ["products.list", "products.detail"],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 2, "maximum": 3},
        "preview_type": "site",
    },
    {
        "id": "documentation_site",
        "name": "Documentation Site",
        "description": "Knowledge and product documentation surface.",
        "category": "frontend",
        "supported_stacks": ["static_site", "nextjs", "react"],
        "recommended_stacks": ["nextjs", "static_site"],
        "default_capabilities": ["seo", "search", "i18n"],
        "recommended_business_modules": ["notifications"],
        "default_endpoints": [],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 1, "maximum": 2},
        "preview_type": "site",
    },
    {
        "id": "saas_dashboard",
        "name": "SaaS Dashboard",
        "description": "Authenticated product workspace for a software business.",
        "category": "application",
        "supported_stacks": ["nextjs", "react", "angular", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "nestjs", "fastapi"],
        "default_capabilities": ["authentication", "rbac", "analytics"],
        "recommended_business_modules": ["users", "subscriptions", "reports", "settings"],
        "default_endpoints": ["auth.login", "auth.register", "auth.me", "analytics.overview"],
        "supported_architecture_levels": [
            "level_2_professional",
            "level_3_enterprise",
            "level_4_distributed",
        ],
        "supported_locales": ["pt-BR", "en-US", "es-ES", "fr-FR"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "dashboard",
    },
    {
        "id": "admin_panel",
        "name": "Admin Panel",
        "description": "Operational interface for privileged internal management.",
        "category": "application",
        "supported_stacks": ["nextjs", "react", "angular", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "nestjs"],
        "default_capabilities": ["authentication", "rbac", "audit_logs"],
        "recommended_business_modules": ["users", "settings", "audit", "reports"],
        "default_endpoints": ["auth.login", "users.list", "admin.settings", "admin.audit_logs"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "dashboard",
    },
    {
        "id": "crm",
        "name": "CRM",
        "description": "Customer relationship and lifecycle management system.",
        "category": "application",
        "supported_stacks": ["nextjs", "react", "angular", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "fastapi", "nestjs"],
        "default_capabilities": ["authentication", "rbac", "search", "analytics"],
        "recommended_business_modules": ["users", "customers", "notifications", "reports"],
        "default_endpoints": ["auth.login", "users.list"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "dashboard",
    },
    {
        "id": "erp",
        "name": "ERP",
        "description": "Integrated operations system spanning finance, inventory and workflows.",
        "category": "application",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["spring_boot", "nestjs", "fastapi"],
        "default_capabilities": ["authentication", "rbac", "audit_logs", "analytics"],
        "recommended_business_modules": ["users", "inventory", "invoices", "reports", "settings"],
        "default_endpoints": ["auth.login", "orders.list", "products.list"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "system",
    },
    {
        "id": "marketplace",
        "name": "Marketplace",
        "description": "Multi-party commerce system with catalog, orders and payments.",
        "category": "application",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "nestjs"],
        "default_capabilities": ["authentication", "payments", "search", "analytics"],
        "recommended_business_modules": ["users", "products", "orders", "payments", "notifications"],
        "default_endpoints": ["products.list", "orders.create", "payments.create"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "platform",
    },
    {
        "id": "ecommerce",
        "name": "E-commerce",
        "description": "Direct commerce experience with checkout, products and order management.",
        "category": "application",
        "supported_stacks": ["nextjs", "react", "angular", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "fastapi", "nestjs"],
        "default_capabilities": ["payments", "search", "analytics", "email_notifications"],
        "recommended_business_modules": ["users", "products", "orders", "payments", "inventory"],
        "default_endpoints": ["products.list", "orders.create", "payments.create"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "platform",
    },
    {
        "id": "booking_system",
        "name": "Booking System",
        "description": "Scheduling and reservation platform with availability and appointment management.",
        "category": "application",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "fastapi"],
        "default_capabilities": ["authentication", "email_notifications"],
        "recommended_business_modules": ["users", "appointments", "notifications"],
        "default_endpoints": ["auth.login", "users.list"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "platform",
    },
    {
        "id": "elearning_platform",
        "name": "E-learning Platform",
        "description": "Course delivery and learner management platform.",
        "category": "application",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "nestjs"],
        "default_capabilities": ["authentication", "search", "analytics"],
        "recommended_business_modules": ["users", "courses", "students", "reports"],
        "default_endpoints": ["auth.login", "users.list"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "platform",
    },
    {
        "id": "rest_api",
        "name": "REST API",
        "description": "Classic resource-oriented API service.",
        "category": "backend",
        "supported_stacks": ["fastapi", "spring_boot", "nestjs", "express", "fastify"],
        "recommended_stacks": ["fastapi", "nestjs"],
        "default_capabilities": ["api_docs", "rate_limiting"],
        "recommended_business_modules": ["users", "settings"],
        "default_endpoints": ["auth.login", "users.list"],
        "supported_architecture_levels": ["level_1_mvp", "level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US", "es-ES", "fr-FR"],
        "complexity_range": {"minimum": 1, "maximum": 3},
        "preview_type": "api",
    },
    {
        "id": "async_api",
        "name": "Async API",
        "description": "Asynchronous API service with background processing expectations.",
        "category": "backend",
        "supported_stacks": ["fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["fastapi", "nestjs"],
        "default_capabilities": ["queue", "api_docs", "observability"],
        "recommended_business_modules": ["notifications", "reports"],
        "default_endpoints": ["auth.login", "analytics.activity"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "api",
    },
    {
        "id": "microservice_api",
        "name": "Microservice API",
        "description": "Service-bounded API designed for distributed environments.",
        "category": "backend",
        "supported_stacks": ["fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nestjs", "spring_boot"],
        "default_capabilities": ["docker", "observability", "ci_cd"],
        "recommended_business_modules": ["users", "notifications"],
        "default_endpoints": ["users.list"],
        "supported_architecture_levels": ["level_4_distributed", "level_5_hyperscale"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 4, "maximum": 5},
        "preview_type": "api",
    },
    {
        "id": "banking_api",
        "name": "Banking API",
        "description": "Highly controlled financial transaction API.",
        "category": "backend",
        "supported_stacks": ["fastapi", "spring_boot", "nestjs"],
        "recommended_stacks": ["spring_boot", "fastapi"],
        "default_capabilities": ["authentication", "rbac", "audit_logs", "observability", "rate_limiting"],
        "recommended_business_modules": ["users", "payments", "wallets", "transactions", "audit"],
        "default_endpoints": ["auth.login", "payments.create"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "api",
    },
    {
        "id": "healthcare_api",
        "name": "Healthcare API",
        "description": "Compliance-oriented healthcare data and workflow API.",
        "category": "backend",
        "supported_stacks": ["fastapi", "spring_boot", "nestjs"],
        "recommended_stacks": ["spring_boot", "fastapi"],
        "default_capabilities": ["authentication", "rbac", "audit_logs", "observability"],
        "recommended_business_modules": ["users", "appointments", "notifications", "reports"],
        "default_endpoints": ["auth.login", "users.list"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "api",
    },
    {
        "id": "integration_api",
        "name": "Integration API",
        "description": "System integration layer for external and internal connectors.",
        "category": "backend",
        "supported_stacks": ["fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["fastapi", "nestjs"],
        "default_capabilities": ["queue", "rate_limiting", "observability"],
        "recommended_business_modules": ["notifications", "settings"],
        "default_endpoints": ["auth.login"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "api",
    },
    {
        "id": "realtime_api",
        "name": "Realtime API",
        "description": "API foundation for live updates and websocket-oriented delivery.",
        "category": "backend",
        "supported_stacks": ["fastapi", "nestjs"],
        "recommended_stacks": ["nestjs", "fastapi"],
        "default_capabilities": ["websocket", "realtime", "observability"],
        "recommended_business_modules": ["notifications", "reports"],
        "default_endpoints": ["analytics.activity"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "api",
    },
    {
        "id": "ai_saas",
        "name": "AI SaaS",
        "description": "Software product with AI-assisted user-facing experiences.",
        "category": "ai",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nextjs", "fastapi", "nestjs"],
        "default_capabilities": ["authentication", "ai_chat", "analytics"],
        "recommended_business_modules": ["users", "subscriptions", "notifications"],
        "default_endpoints": ["auth.login", "ai.chat", "analytics.overview"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "platform",
    },
    {
        "id": "ai_agent_platform",
        "name": "AI Agent Platform",
        "description": "Architecture-oriented platform for future agent orchestration surfaces.",
        "category": "ai",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nestjs", "fastapi"],
        "default_capabilities": ["ai_chat", "queue", "observability"],
        "recommended_business_modules": ["users", "notifications", "audit"],
        "default_endpoints": ["ai.chat", "auth.login"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed", "level_5_hyperscale"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 4, "maximum": 5},
        "preview_type": "platform",
    },
    {
        "id": "rag_system",
        "name": "RAG System",
        "description": "Retrieval-augmented answer and knowledge experience foundation.",
        "category": "ai",
        "supported_stacks": ["nextjs", "fastapi", "nestjs"],
        "recommended_stacks": ["fastapi", "nextjs"],
        "default_capabilities": ["rag", "search", "ai_chat"],
        "recommended_business_modules": ["users", "notifications"],
        "default_endpoints": ["ai.chat", "ai.embeddings"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "system",
    },
    {
        "id": "chatbot_platform",
        "name": "Chatbot Platform",
        "description": "Conversational interaction platform for support or product use cases.",
        "category": "ai",
        "supported_stacks": ["nextjs", "fastapi", "nestjs"],
        "recommended_stacks": ["nextjs", "fastapi"],
        "default_capabilities": ["ai_chat", "email_notifications"],
        "recommended_business_modules": ["users", "notifications"],
        "default_endpoints": ["ai.chat", "auth.login"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US", "es-ES"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "platform",
    },
    {
        "id": "automation_agent",
        "name": "Automation Agent",
        "description": "Process automation foundation with future execution-oriented extension points.",
        "category": "ai",
        "supported_stacks": ["fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["fastapi", "nestjs"],
        "default_capabilities": ["queue", "observability", "ci_cd"],
        "recommended_business_modules": ["notifications", "audit"],
        "default_endpoints": ["auth.login"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "system",
    },
    {
        "id": "modular_monolith",
        "name": "Modular Monolith",
        "description": "Architecture-first project emphasizing internal module boundaries.",
        "category": "architecture",
        "supported_stacks": ["nextjs", "fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["fastapi", "nestjs", "spring_boot"],
        "default_capabilities": ["api_docs"],
        "recommended_business_modules": ["users", "settings"],
        "default_endpoints": ["auth.login"],
        "supported_architecture_levels": ["level_2_professional", "level_3_enterprise"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 2, "maximum": 4},
        "preview_type": "system",
    },
    {
        "id": "microservices_platform",
        "name": "Microservices Platform",
        "description": "Service-bounded architecture with distributed constraints.",
        "category": "architecture",
        "supported_stacks": ["fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nestjs", "spring_boot"],
        "default_capabilities": ["docker", "observability", "ci_cd"],
        "recommended_business_modules": ["users", "notifications", "audit"],
        "default_endpoints": ["users.list"],
        "supported_architecture_levels": ["level_4_distributed", "level_5_hyperscale"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 4, "maximum": 5},
        "preview_type": "system",
    },
    {
        "id": "event_driven_system",
        "name": "Event Driven System",
        "description": "Architecture centered on events, queues and asynchronous boundaries.",
        "category": "architecture",
        "supported_stacks": ["fastapi", "nestjs", "spring_boot"],
        "recommended_stacks": ["nestjs", "fastapi"],
        "default_capabilities": ["queue", "observability", "cache"],
        "recommended_business_modules": ["notifications", "audit", "reports"],
        "default_endpoints": ["analytics.activity"],
        "supported_architecture_levels": ["level_3_enterprise", "level_4_distributed", "level_5_hyperscale"],
        "supported_locales": ["pt-BR", "en-US"],
        "complexity_range": {"minimum": 3, "maximum": 5},
        "preview_type": "system",
    },
]


def get_archetypes_registry() -> Sequence[dict]:
    return ARCHETYPES
