from __future__ import annotations

from collections.abc import Sequence

BUSINESS_MODULES: list[dict] = [
    {"id": "users", "name": "Users", "description": "Identity and account management.", "category": "core", "recommended_capabilities": ["authentication"], "default_endpoints": ["users.list", "users.create", "users.detail", "users.update", "users.delete"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs"]},
    {"id": "customers", "name": "Customers", "description": "Customer registry and relationship data.", "category": "core", "recommended_capabilities": ["authentication", "search"], "default_endpoints": [], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
    {"id": "products", "name": "Products", "description": "Catalog and product management.", "category": "commerce", "recommended_capabilities": ["search"], "default_endpoints": ["products.list", "products.create", "products.detail", "products.update", "products.delete"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs"]},
    {"id": "orders", "name": "Orders", "description": "Order lifecycle and fulfillment.", "category": "commerce", "recommended_capabilities": ["payments"], "default_endpoints": ["orders.list", "orders.create", "orders.detail", "orders.update_status"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
    {"id": "inventory", "name": "Inventory", "description": "Stock and availability management.", "category": "operations", "recommended_capabilities": ["analytics"], "default_endpoints": [], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
    {"id": "invoices", "name": "Invoices", "description": "Billing and invoicing records.", "category": "finance", "recommended_capabilities": ["payments"], "default_endpoints": [], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["fastapi", "spring_boot", "nestjs", "nextjs"]},
    {"id": "payments", "name": "Payments", "description": "Payment execution and reconciliation.", "category": "finance", "recommended_capabilities": ["payments"], "default_endpoints": ["payments.create", "payments.webhook", "payments.list"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["fastapi", "spring_boot", "nestjs", "nextjs"]},
    {"id": "appointments", "name": "Appointments", "description": "Booking and appointment scheduling.", "category": "operations", "recommended_capabilities": ["email_notifications"], "default_endpoints": [], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
    {"id": "reports", "name": "Reports", "description": "Operational and business reporting.", "category": "operations", "recommended_capabilities": ["analytics"], "default_endpoints": ["analytics.overview", "analytics.revenue", "analytics.activity"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
    {"id": "subscriptions", "name": "Subscriptions", "description": "Subscription lifecycle management.", "category": "finance", "recommended_capabilities": ["subscriptions", "payments"], "default_endpoints": [], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
    {"id": "notifications", "name": "Notifications", "description": "User and system notifications.", "category": "communication", "recommended_capabilities": ["email_notifications"], "default_endpoints": [], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"]},
    {"id": "audit", "name": "Audit", "description": "Governance and audit review.", "category": "governance", "recommended_capabilities": ["audit_logs"], "default_endpoints": ["admin.audit_logs"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["fastapi", "spring_boot", "nestjs", "nextjs"]},
    {"id": "settings", "name": "Settings", "description": "Administrative configuration and preferences.", "category": "governance", "recommended_capabilities": ["rbac"], "default_endpoints": ["admin.settings"], "required_fields": ["project_name"], "optional_fields": ["locale"], "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"]},
]


def get_business_modules_registry() -> Sequence[dict]:
    return BUSINESS_MODULES
