from __future__ import annotations

from collections.abc import Sequence

CAPABILITIES: list[dict] = [
    {"id": "authentication", "name": "Authentication", "description": "Identity and login flows.", "category": "security", "supported_stacks": ["nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["auth.login", "auth.register", "auth.refresh", "auth.logout", "auth.me"], "architecture_level_minimum": "level_1_mvp", "security_impact": "high", "generation_impact": "medium"},
    {"id": "rbac", "name": "RBAC", "description": "Role-based access control.", "category": "security", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": ["authentication"], "conflicts_with": [], "recommended_endpoints": ["admin.settings", "admin.audit_logs"], "architecture_level_minimum": "level_2_professional", "security_impact": "critical", "generation_impact": "medium"},
    {"id": "multi_tenancy", "name": "Multi Tenancy", "description": "Tenant-aware isolation.", "category": "platform", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": ["authentication"], "conflicts_with": [], "recommended_endpoints": ["users.list"], "architecture_level_minimum": "level_3_enterprise", "security_impact": "critical", "generation_impact": "high"},
    {"id": "payments", "name": "Payments", "description": "Payment and webhook support.", "category": "commerce", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["payments.create", "payments.webhook", "payments.list"], "architecture_level_minimum": "level_2_professional", "security_impact": "high", "generation_impact": "high"},
    {"id": "subscriptions", "name": "Subscriptions", "description": "Recurring billing support.", "category": "commerce", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": ["payments"], "conflicts_with": [], "recommended_endpoints": ["payments.create"], "architecture_level_minimum": "level_2_professional", "security_impact": "medium", "generation_impact": "medium"},
    {"id": "email_notifications", "name": "Email Notifications", "description": "Email-based outbound communication.", "category": "communication", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_1_mvp", "security_impact": "low", "generation_impact": "low"},
    {"id": "websocket", "name": "WebSocket", "description": "Bidirectional websocket transport.", "category": "platform", "supported_stacks": ["nextjs", "fastapi", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["analytics.activity"], "architecture_level_minimum": "level_2_professional", "security_impact": "medium", "generation_impact": "medium"},
    {"id": "realtime", "name": "Realtime", "description": "Low-latency live interaction capability.", "category": "platform", "supported_stacks": ["nextjs", "fastapi", "nestjs"], "requires": ["websocket"], "conflicts_with": [], "recommended_endpoints": ["analytics.activity"], "architecture_level_minimum": "level_2_professional", "security_impact": "medium", "generation_impact": "medium"},
    {"id": "file_upload", "name": "File Upload", "description": "Document and file upload support.", "category": "experience", "supported_stacks": ["nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_1_mvp", "security_impact": "medium", "generation_impact": "low"},
    {"id": "search", "name": "Search", "description": "Search and retrieval capability.", "category": "data", "supported_stacks": ["static_site", "nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["products.list"], "architecture_level_minimum": "level_1_mvp", "security_impact": "low", "generation_impact": "medium"},
    {"id": "analytics", "name": "Analytics", "description": "Metrics and analytics capability.", "category": "data", "supported_stacks": ["static_site", "nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs", "express", "fastify"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["analytics.overview", "analytics.revenue", "analytics.activity"], "architecture_level_minimum": "level_1_mvp", "security_impact": "low", "generation_impact": "medium"},
    {"id": "audit_logs", "name": "Audit Logs", "description": "Administrative audit trail.", "category": "security", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["admin.audit_logs"], "architecture_level_minimum": "level_2_professional", "security_impact": "high", "generation_impact": "low"},
    {"id": "ai_chat", "name": "AI Chat", "description": "Conversational AI interaction surface.", "category": "ai", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["ai.chat"], "architecture_level_minimum": "level_2_professional", "security_impact": "medium", "generation_impact": "high"},
    {"id": "rag", "name": "RAG", "description": "Retrieval augmented generation support.", "category": "ai", "supported_stacks": ["nextjs", "fastapi", "nestjs"], "requires": ["ai_chat", "search"], "conflicts_with": [], "recommended_endpoints": ["ai.embeddings", "ai.chat"], "architecture_level_minimum": "level_3_enterprise", "security_impact": "high", "generation_impact": "high"},
    {"id": "queue", "name": "Queue", "description": "Background job and queue processing.", "category": "platform", "supported_stacks": ["fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["analytics.activity"], "architecture_level_minimum": "level_2_professional", "security_impact": "medium", "generation_impact": "medium"},
    {"id": "cache", "name": "Cache", "description": "Response or data caching.", "category": "platform", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["analytics.overview"], "architecture_level_minimum": "level_2_professional", "security_impact": "low", "generation_impact": "low"},
    {"id": "seo", "name": "SEO", "description": "Search optimization readiness.", "category": "experience", "supported_stacks": ["static_site", "nextjs", "react", "angular"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_1_mvp", "security_impact": "low", "generation_impact": "low"},
    {"id": "i18n", "name": "I18N", "description": "Internationalization support.", "category": "experience", "supported_stacks": ["static_site", "nextjs", "react", "angular", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_1_mvp", "security_impact": "low", "generation_impact": "low"},
    {"id": "pwa", "name": "PWA", "description": "Progressive web app capability.", "category": "experience", "supported_stacks": ["nextjs", "react", "angular"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_2_professional", "security_impact": "low", "generation_impact": "medium"},
    {"id": "docker", "name": "Docker", "description": "Containerized deployment readiness.", "category": "quality", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_2_professional", "security_impact": "low", "generation_impact": "low"},
    {"id": "observability", "name": "Observability", "description": "Logs, metrics and tracing readiness.", "category": "quality", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["analytics.activity", "admin.audit_logs"], "architecture_level_minimum": "level_2_professional", "security_impact": "medium", "generation_impact": "medium"},
    {"id": "ci_cd", "name": "CI/CD", "description": "Delivery automation readiness.", "category": "quality", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "requires": [], "conflicts_with": [], "recommended_endpoints": [], "architecture_level_minimum": "level_3_enterprise", "security_impact": "low", "generation_impact": "low"},
    {"id": "api_docs", "name": "API Docs", "description": "API documentation readiness.", "category": "quality", "supported_stacks": ["fastapi", "spring_boot", "nestjs", "express", "dotnet"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["auth.login", "users.list"], "architecture_level_minimum": "level_1_mvp", "security_impact": "low", "generation_impact": "low"},
    {"id": "rate_limiting", "name": "Rate Limiting", "description": "Request throttling and abuse protection.", "category": "security", "supported_stacks": ["fastapi", "spring_boot", "nestjs"], "requires": [], "conflicts_with": [], "recommended_endpoints": ["auth.login", "ai.chat"], "architecture_level_minimum": "level_2_professional", "security_impact": "high", "generation_impact": "low"},
]


def get_capabilities_registry() -> Sequence[dict]:
    return CAPABILITIES
