from __future__ import annotations

from collections.abc import Sequence

ENDPOINTS: list[dict] = [
    {"id": "auth.login", "method": "POST", "path": "/auth/login", "group": "auth", "description": "Authenticate a user.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "credentials", "response_schema_hint": "access_token_bundle", "security_level": "public", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "auth.register", "method": "POST", "path": "/auth/register", "group": "auth", "description": "Register a new user.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "registration_payload", "response_schema_hint": "user_profile", "security_level": "public", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "auth.refresh", "method": "POST", "path": "/auth/refresh", "group": "auth", "description": "Refresh auth token.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "refresh_token", "response_schema_hint": "access_token_bundle", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "auth.logout", "method": "POST", "path": "/auth/logout", "group": "auth", "description": "Logout current session.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "logout_payload", "response_schema_hint": "operation_status", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "auth.me", "method": "GET", "path": "/auth/me", "group": "auth", "description": "Get current user profile.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "none", "response_schema_hint": "user_profile", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "users.list", "method": "GET", "path": "/users", "group": "users", "description": "List users.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "query_filters", "response_schema_hint": "user_list", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "users.create", "method": "POST", "path": "/users", "group": "users", "description": "Create user.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "user_create_payload", "response_schema_hint": "user_profile", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "users.detail", "method": "GET", "path": "/users/{id}", "group": "users", "description": "Get user detail.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "path_id", "response_schema_hint": "user_profile", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "users.update", "method": "PUT", "path": "/users/{id}", "group": "users", "description": "Update user.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "user_update_payload", "response_schema_hint": "user_profile", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "users.delete", "method": "DELETE", "path": "/users/{id}", "group": "users", "description": "Delete user.", "business_module_id": "users", "required_capabilities": ["authentication"], "request_schema_hint": "path_id", "response_schema_hint": "operation_status", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "products.list", "method": "GET", "path": "/products", "group": "products", "description": "List products.", "business_module_id": "products", "required_capabilities": [], "request_schema_hint": "query_filters", "response_schema_hint": "product_list", "security_level": "public", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "products.create", "method": "POST", "path": "/products", "group": "products", "description": "Create product.", "business_module_id": "products", "required_capabilities": ["authentication"], "request_schema_hint": "product_create_payload", "response_schema_hint": "product_detail", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "products.detail", "method": "GET", "path": "/products/{id}", "group": "products", "description": "Get product detail.", "business_module_id": "products", "required_capabilities": [], "request_schema_hint": "path_id", "response_schema_hint": "product_detail", "security_level": "public", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "react", "angular"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "products.update", "method": "PUT", "path": "/products/{id}", "group": "products", "description": "Update product.", "business_module_id": "products", "required_capabilities": ["authentication"], "request_schema_hint": "product_update_payload", "response_schema_hint": "product_detail", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "products.delete", "method": "DELETE", "path": "/products/{id}", "group": "products", "description": "Delete product.", "business_module_id": "products", "required_capabilities": ["authentication"], "request_schema_hint": "path_id", "response_schema_hint": "operation_status", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "orders.list", "method": "GET", "path": "/orders", "group": "orders", "description": "List orders.", "business_module_id": "orders", "required_capabilities": ["authentication"], "request_schema_hint": "query_filters", "response_schema_hint": "order_list", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "orders.create", "method": "POST", "path": "/orders", "group": "orders", "description": "Create order.", "business_module_id": "orders", "required_capabilities": ["authentication"], "request_schema_hint": "order_create_payload", "response_schema_hint": "order_detail", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "orders.detail", "method": "GET", "path": "/orders/{id}", "group": "orders", "description": "Get order detail.", "business_module_id": "orders", "required_capabilities": ["authentication"], "request_schema_hint": "path_id", "response_schema_hint": "order_detail", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "orders.update_status", "method": "PATCH", "path": "/orders/{id}/status", "group": "orders", "description": "Update order status.", "business_module_id": "orders", "required_capabilities": ["authentication"], "request_schema_hint": "order_status_payload", "response_schema_hint": "order_detail", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "payments.create", "method": "POST", "path": "/payments", "group": "payments", "description": "Create payment.", "business_module_id": "payments", "required_capabilities": ["payments"], "request_schema_hint": "payment_create_payload", "response_schema_hint": "payment_detail", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "payments.webhook", "method": "POST", "path": "/payments/webhook", "group": "payments", "description": "Receive payment webhook.", "business_module_id": "payments", "required_capabilities": ["payments"], "request_schema_hint": "webhook_payload", "response_schema_hint": "operation_status", "security_level": "internal", "supported_stacks": ["fastapi", "spring_boot", "nestjs", "nextjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "payments.list", "method": "GET", "path": "/payments", "group": "payments", "description": "List payments.", "business_module_id": "payments", "required_capabilities": ["payments"], "request_schema_hint": "query_filters", "response_schema_hint": "payment_list", "security_level": "privileged", "supported_stacks": ["fastapi", "spring_boot", "nestjs", "nextjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "ai.chat", "method": "POST", "path": "/ai/chat", "group": "ai", "description": "Conversational AI chat.", "business_module_id": "notifications", "required_capabilities": ["ai_chat"], "request_schema_hint": "chat_prompt", "response_schema_hint": "chat_response", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "ai.generate", "method": "POST", "path": "/ai/generate", "group": "ai", "description": "Content generation endpoint placeholder.", "business_module_id": "notifications", "required_capabilities": ["ai_chat"], "request_schema_hint": "generation_request", "response_schema_hint": "generation_response", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_3_enterprise"},
    {"id": "ai.embeddings", "method": "POST", "path": "/ai/embeddings", "group": "ai", "description": "Embeddings endpoint placeholder.", "business_module_id": "notifications", "required_capabilities": ["rag"], "request_schema_hint": "embedding_request", "response_schema_hint": "embedding_response", "security_level": "authenticated", "supported_stacks": ["fastapi", "nestjs"], "architecture_level_minimum": "level_3_enterprise"},
    {"id": "analytics.overview", "method": "GET", "path": "/analytics/overview", "group": "analytics", "description": "Analytics overview.", "business_module_id": "reports", "required_capabilities": ["analytics"], "request_schema_hint": "none", "response_schema_hint": "analytics_summary", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs", "express", "fastify"], "architecture_level_minimum": "level_1_mvp"},
    {"id": "analytics.revenue", "method": "GET", "path": "/analytics/revenue", "group": "analytics", "description": "Revenue analytics.", "business_module_id": "reports", "required_capabilities": ["analytics"], "request_schema_hint": "date_range", "response_schema_hint": "revenue_summary", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "analytics.activity", "method": "GET", "path": "/analytics/activity", "group": "analytics", "description": "Activity analytics stream.", "business_module_id": "reports", "required_capabilities": ["analytics"], "request_schema_hint": "date_range", "response_schema_hint": "activity_summary", "security_level": "authenticated", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "admin.audit_logs", "method": "GET", "path": "/admin/audit-logs", "group": "admin", "description": "Administrative audit log view.", "business_module_id": "audit", "required_capabilities": ["audit_logs"], "request_schema_hint": "query_filters", "response_schema_hint": "audit_log_list", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
    {"id": "admin.settings", "method": "GET", "path": "/admin/settings", "group": "admin", "description": "Administrative settings view.", "business_module_id": "settings", "required_capabilities": ["authentication"], "request_schema_hint": "none", "response_schema_hint": "settings_payload", "security_level": "privileged", "supported_stacks": ["nextjs", "fastapi", "spring_boot", "nestjs"], "architecture_level_minimum": "level_2_professional"},
]


def get_endpoints_registry() -> Sequence[dict]:
    return ENDPOINTS
