from __future__ import annotations

from collections.abc import Sequence

FRAMEWORKS: list[dict] = [
    {
        "id": "spring_boot",
        "name": "Spring Boot",
        "language_id": "java",
        "runtime_id": "jvm",
        "framework_type": "backend_framework",
        "description": "Enterprise-grade Java framework for APIs, domains and distributed systems.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "event_driven", "hexagonal", "clean_architecture"],
        "archetype_support": ["rest_api", "async_api", "microservice_api", "banking_api", "healthcare_api", "integration_api", "erp", "marketplace", "ai_saas"],
        "capability_support": ["authentication", "rbac", "payments", "queue", "observability", "audit_logs", "rate_limiting", "api_docs", "ci_cd", "docker"],
        "enterprise_score": 10,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["enterprise backend", "regulated systems", "modular services"],
    },
    {
        "id": "quarkus",
        "name": "Quarkus",
        "language_id": "java",
        "runtime_id": "jvm",
        "framework_type": "backend_framework",
        "description": "Cloud-native Java framework optimized for containers and fast startup.",
        "architecture_support": ["modular_monolith", "microservices", "event_driven", "clean_architecture"],
        "archetype_support": ["rest_api", "microservice_api", "integration_api"],
        "capability_support": ["authentication", "observability", "queue", "docker", "ci_cd", "rate_limiting"],
        "enterprise_score": 8,
        "maturity_level": "mature",
        "recommended_use_cases": ["microservices", "container-first java services"],
    },
    {
        "id": "micronaut",
        "name": "Micronaut",
        "language_id": "java",
        "runtime_id": "jvm",
        "framework_type": "backend_framework",
        "description": "Ahead-of-time-friendly JVM framework for services and APIs.",
        "architecture_support": ["modular_monolith", "microservices", "clean_architecture"],
        "archetype_support": ["rest_api", "microservice_api", "integration_api"],
        "capability_support": ["authentication", "observability", "docker", "ci_cd", "api_docs"],
        "enterprise_score": 7,
        "maturity_level": "mature",
        "recommended_use_cases": ["service APIs", "lightweight enterprise backends"],
    },
    {
        "id": "nestjs",
        "name": "NestJS",
        "language_id": "typescript",
        "runtime_id": "nodejs",
        "framework_type": "backend_framework",
        "description": "Structured TypeScript backend framework for modular services and APIs.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "event_driven", "cqrs", "distributed_system", "hexagonal", "clean_architecture"],
        "archetype_support": ["rest_api", "async_api", "microservice_api", "realtime_api", "integration_api", "ai_saas", "ai_agent_platform", "rag_system", "automation_agent", "saas_dashboard", "marketplace"],
        "capability_support": ["authentication", "rbac", "websocket", "realtime", "queue", "cache", "observability", "ci_cd", "api_docs", "rate_limiting", "ai_chat", "rag", "docker"],
        "enterprise_score": 9,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["modular api", "event-driven backends", "enterprise node services"],
    },
    {
        "id": "nextjs",
        "name": "Next.js",
        "language_id": "typescript",
        "runtime_id": "nodejs",
        "framework_type": "meta_framework",
        "description": "Meta framework for product sites, SaaS frontends and full-stack web experiences.",
        "architecture_support": ["monolith", "modular_monolith", "serverless", "clean_architecture"],
        "archetype_support": ["landing_page", "institutional_site", "portfolio", "blog", "sales_page", "catalog_site", "documentation_site", "saas_dashboard", "admin_panel", "crm", "ecommerce", "marketplace", "booking_system", "elearning_platform", "ai_saas", "chatbot_platform"],
        "capability_support": ["authentication", "payments", "email_notifications", "file_upload", "search", "analytics", "ai_chat", "seo", "i18n", "pwa", "docker", "observability"],
        "enterprise_score": 8,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["product sites", "full-stack apps", "saas frontends"],
    },
    {
        "id": "express",
        "name": "Express",
        "language_id": "javascript",
        "runtime_id": "nodejs",
        "framework_type": "api_framework",
        "description": "Minimal Node.js HTTP framework for flexible service composition.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "serverless"],
        "archetype_support": ["rest_api", "integration_api"],
        "capability_support": ["authentication", "payments", "api_docs", "rate_limiting", "docker"],
        "enterprise_score": 6,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["simple apis", "integration layers", "custom node services"],
    },
    {
        "id": "fastify",
        "name": "Fastify",
        "language_id": "typescript",
        "runtime_id": "nodejs",
        "framework_type": "api_framework",
        "description": "High-performance Node framework for APIs and services.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "serverless"],
        "archetype_support": ["rest_api", "async_api", "integration_api", "microservice_api"],
        "capability_support": ["authentication", "api_docs", "rate_limiting", "observability", "docker"],
        "enterprise_score": 7,
        "maturity_level": "mature",
        "recommended_use_cases": ["fast apis", "node microservices"],
    },
    {
        "id": "angular",
        "name": "Angular",
        "language_id": "typescript",
        "runtime_id": "nodejs",
        "framework_type": "frontend_framework",
        "description": "Structured frontend framework for large enterprise web applications.",
        "architecture_support": ["monolith", "modular_monolith", "clean_architecture"],
        "archetype_support": ["landing_page", "institutional_site", "blog", "saas_dashboard", "admin_panel", "crm", "catalog_site", "ecommerce"],
        "capability_support": ["authentication", "search", "analytics", "seo", "i18n", "pwa", "file_upload"],
        "enterprise_score": 9,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["admin panels", "enterprise frontends", "internal tools"],
    },
    {
        "id": "react",
        "name": "React",
        "language_id": "typescript",
        "runtime_id": "nodejs",
        "framework_type": "ui_framework",
        "description": "Component-first UI framework for flexible frontend application surfaces.",
        "architecture_support": ["monolith", "modular_monolith", "serverless", "clean_architecture"],
        "archetype_support": ["landing_page", "institutional_site", "portfolio", "blog", "sales_page", "catalog_site", "saas_dashboard", "admin_panel", "crm", "ecommerce"],
        "capability_support": ["authentication", "search", "analytics", "seo", "i18n", "pwa", "file_upload"],
        "enterprise_score": 8,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["frontend products", "dashboards", "design systems"],
    },
    {
        "id": "fastapi",
        "name": "FastAPI",
        "language_id": "python",
        "runtime_id": "python_runtime",
        "framework_type": "api_framework",
        "description": "Python API framework optimized for typed services and local-first development.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "event_driven", "hexagonal", "clean_architecture"],
        "archetype_support": ["rest_api", "async_api", "microservice_api", "integration_api", "realtime_api", "banking_api", "healthcare_api", "ai_saas", "rag_system", "chatbot_platform", "automation_agent"],
        "capability_support": ["authentication", "rbac", "payments", "websocket", "realtime", "queue", "cache", "observability", "ci_cd", "api_docs", "rate_limiting", "ai_chat", "rag", "docker"],
        "enterprise_score": 8,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["typed apis", "local-first backends", "ai-adjacent services"],
    },
    {
        "id": "django",
        "name": "Django",
        "language_id": "python",
        "runtime_id": "python_runtime",
        "framework_type": "fullstack_framework",
        "description": "Batteries-included Python web framework for monolithic product systems.",
        "architecture_support": ["monolith", "modular_monolith", "clean_architecture"],
        "archetype_support": ["saas_dashboard", "admin_panel", "crm", "rest_api"],
        "capability_support": ["authentication", "rbac", "payments", "search", "analytics", "audit_logs", "i18n"],
        "enterprise_score": 8,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["full-stack internal systems", "admin-heavy products"],
    },
    {
        "id": "flask",
        "name": "Flask",
        "language_id": "python",
        "runtime_id": "python_runtime",
        "framework_type": "api_framework",
        "description": "Minimal Python web framework for simple APIs and service foundations.",
        "architecture_support": ["monolith", "modular_monolith", "serverless"],
        "archetype_support": ["rest_api", "integration_api"],
        "capability_support": ["authentication", "api_docs", "rate_limiting", "docker"],
        "enterprise_score": 6,
        "maturity_level": "mature",
        "recommended_use_cases": ["small apis", "lightweight services"],
    },
    {
        "id": "aspnet_core",
        "name": "ASP.NET Core",
        "language_id": "csharp",
        "runtime_id": "dotnet_runtime",
        "framework_type": "backend_framework",
        "description": ".NET application framework for robust APIs and enterprise web systems.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "event_driven", "clean_architecture"],
        "archetype_support": ["rest_api", "integration_api", "microservice_api", "crm", "erp"],
        "capability_support": ["authentication", "rbac", "payments", "observability", "ci_cd", "api_docs", "rate_limiting", "docker"],
        "enterprise_score": 9,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["enterprise apis", "internal platforms", "governed services"],
    },
    {
        "id": "blazor",
        "name": "Blazor",
        "language_id": "csharp",
        "runtime_id": "dotnet_runtime",
        "framework_type": "fullstack_framework",
        "description": ".NET UI framework for business applications and internal portals.",
        "architecture_support": ["monolith", "modular_monolith", "clean_architecture"],
        "archetype_support": ["admin_panel", "crm", "saas_dashboard"],
        "capability_support": ["authentication", "rbac", "analytics", "i18n", "file_upload"],
        "enterprise_score": 8,
        "maturity_level": "mature",
        "recommended_use_cases": ["internal enterprise apps", ".net product surfaces"],
    },
    {
        "id": "laravel",
        "name": "Laravel",
        "language_id": "php",
        "runtime_id": "php_runtime",
        "framework_type": "fullstack_framework",
        "description": "Productive PHP framework for monolithic apps, APIs and admin-heavy systems.",
        "architecture_support": ["monolith", "modular_monolith", "serverless", "clean_architecture"],
        "archetype_support": ["ecommerce", "crm", "admin_panel", "rest_api"],
        "capability_support": ["authentication", "payments", "email_notifications", "search", "analytics", "queue", "api_docs"],
        "enterprise_score": 7,
        "maturity_level": "enterprise",
        "recommended_use_cases": ["crud-heavy apps", "commerce systems", "admin platforms"],
    },
    {
        "id": "fiber",
        "name": "Fiber",
        "language_id": "go",
        "runtime_id": "go_runtime",
        "framework_type": "api_framework",
        "description": "Go web framework focused on speed and low-overhead API delivery.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "distributed_system"],
        "archetype_support": ["rest_api", "integration_api", "microservice_api"],
        "capability_support": ["authentication", "observability", "rate_limiting", "docker", "ci_cd"],
        "enterprise_score": 7,
        "maturity_level": "mature",
        "recommended_use_cases": ["high-throughput apis", "lightweight services"],
    },
    {
        "id": "gin",
        "name": "Gin",
        "language_id": "go",
        "runtime_id": "go_runtime",
        "framework_type": "api_framework",
        "description": "Popular Go web framework for APIs and service backends.",
        "architecture_support": ["monolith", "modular_monolith", "microservices", "distributed_system"],
        "archetype_support": ["rest_api", "integration_api", "microservice_api"],
        "capability_support": ["authentication", "observability", "rate_limiting", "docker"],
        "enterprise_score": 7,
        "maturity_level": "mature",
        "recommended_use_cases": ["go apis", "service-oriented backends"],
    },
]


def get_frameworks_registry() -> Sequence[dict]:
    return FRAMEWORKS
