from __future__ import annotations

from collections.abc import Sequence

LANGUAGES: list[dict] = [
    {
        "id": "java",
        "name": "Java",
        "description": "Enterprise JVM language focused on stability, governance and large-scale systems.",
        "ecosystem": "jvm",
        "supported_runtimes": ["jvm"],
        "supported_frameworks": ["spring_boot", "quarkus", "micronaut"],
        "supported_architectures": [
            "monolith",
            "modular_monolith",
            "microservices",
            "event_driven",
            "cqrs",
            "distributed_system",
            "hexagonal",
            "clean_architecture",
        ],
        "enterprise_score": 10,
        "learning_curve": "high",
        "performance_profile": "high",
        "scalability_profile": "hyperscale",
    },
    {
        "id": "typescript",
        "name": "TypeScript",
        "description": "Typed JavaScript superset for maintainable frontend, backend and full-stack platforms.",
        "ecosystem": "javascript",
        "supported_runtimes": ["nodejs", "bun", "deno"],
        "supported_frameworks": ["nestjs", "nextjs", "express", "fastify", "angular", "react"],
        "supported_architectures": [
            "monolith",
            "modular_monolith",
            "microservices",
            "event_driven",
            "serverless",
            "distributed_system",
            "hexagonal",
            "clean_architecture",
        ],
        "enterprise_score": 9,
        "learning_curve": "medium",
        "performance_profile": "high",
        "scalability_profile": "enterprise",
    },
    {
        "id": "javascript",
        "name": "JavaScript",
        "description": "Flexible web-native language for rapid iteration across product surfaces.",
        "ecosystem": "javascript",
        "supported_runtimes": ["nodejs", "bun", "deno"],
        "supported_frameworks": ["nextjs", "express", "fastify", "react"],
        "supported_architectures": [
            "monolith",
            "modular_monolith",
            "serverless",
            "distributed_system",
        ],
        "enterprise_score": 7,
        "learning_curve": "low",
        "performance_profile": "moderate",
        "scalability_profile": "enterprise",
    },
    {
        "id": "python",
        "name": "Python",
        "description": "Productive backend and data language with strong API and AI-adjacent ecosystem support.",
        "ecosystem": "python",
        "supported_runtimes": ["python_runtime"],
        "supported_frameworks": ["fastapi", "django", "flask"],
        "supported_architectures": [
            "monolith",
            "modular_monolith",
            "microservices",
            "event_driven",
            "serverless",
            "hexagonal",
            "clean_architecture",
        ],
        "enterprise_score": 8,
        "learning_curve": "low",
        "performance_profile": "moderate",
        "scalability_profile": "enterprise",
    },
    {
        "id": "csharp",
        "name": "C#",
        "description": "Mature .NET language for enterprise APIs, internal platforms and product systems.",
        "ecosystem": "dotnet",
        "supported_runtimes": ["dotnet_runtime"],
        "supported_frameworks": ["aspnet_core", "blazor"],
        "supported_architectures": [
            "monolith",
            "modular_monolith",
            "microservices",
            "event_driven",
            "distributed_system",
            "clean_architecture",
        ],
        "enterprise_score": 9,
        "learning_curve": "medium",
        "performance_profile": "high",
        "scalability_profile": "enterprise",
    },
    {
        "id": "php",
        "name": "PHP",
        "description": "Web-oriented server language with strong CRUD and product-delivery ecosystem maturity.",
        "ecosystem": "php",
        "supported_runtimes": ["php_runtime"],
        "supported_frameworks": ["laravel"],
        "supported_architectures": ["monolith", "modular_monolith", "serverless", "clean_architecture"],
        "enterprise_score": 7,
        "learning_curve": "low",
        "performance_profile": "moderate",
        "scalability_profile": "enterprise",
    },
    {
        "id": "go",
        "name": "Go",
        "description": "Compiled backend language focused on performance, simplicity and service-oriented delivery.",
        "ecosystem": "go",
        "supported_runtimes": ["go_runtime"],
        "supported_frameworks": ["fiber", "gin"],
        "supported_architectures": [
            "monolith",
            "modular_monolith",
            "microservices",
            "event_driven",
            "distributed_system",
            "clean_architecture",
        ],
        "enterprise_score": 8,
        "learning_curve": "medium",
        "performance_profile": "very_high",
        "scalability_profile": "hyperscale",
    },
]


def get_languages_registry() -> Sequence[dict]:
    return LANGUAGES
