// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/analytics" | "/architect" | "/architecture" | "/auth/callback" | "/auto-fix" | "/change-requests" | "/dashboard" | "/documentation" | "/engineering-laboratory" | "/engineering-review" | "/jobs" | "/login" | "/marketplace" | "/meta-factory" | "/modernize" | "/platform" | "/pricing" | "/project-rooms" | "/project-rooms/[roomId]" | "/project-rooms/import" | "/project-rooms/new" | "/projects" | "/projects/[projectId]" | "/roadmap" | "/settings" | "/skills" | "/system-status" | "/templates" | "/wizard" | "/wizard/[missionId]" | "/wizard/new"
type PageRoutes = never
type LayoutRoutes = "/" | "/pricing"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/analytics": {}
  "/architect": {}
  "/architecture": {}
  "/auth/callback": {}
  "/auto-fix": {}
  "/change-requests": {}
  "/dashboard": {}
  "/documentation": {}
  "/engineering-laboratory": {}
  "/engineering-review": {}
  "/jobs": {}
  "/login": {}
  "/marketplace": {}
  "/meta-factory": {}
  "/modernize": {}
  "/platform": {}
  "/pricing": {}
  "/project-rooms": {}
  "/project-rooms/[roomId]": { "roomId": string; }
  "/project-rooms/import": {}
  "/project-rooms/new": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/roadmap": {}
  "/settings": {}
  "/skills": {}
  "/system-status": {}
  "/templates": {}
  "/wizard": {}
  "/wizard/[missionId]": { "missionId": string; }
  "/wizard/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/pricing": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
