// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(app)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/(app)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/architect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/architect">> = Specific
  const handler = {} as typeof import("../../app/(app)/architect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/architecture">> = Specific
  const handler = {} as typeof import("../../app/(app)/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/auto-fix/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auto-fix">> = Specific
  const handler = {} as typeof import("../../app/(app)/auto-fix/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/change-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/change-requests">> = Specific
  const handler = {} as typeof import("../../app/(app)/change-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/documentation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentation">> = Specific
  const handler = {} as typeof import("../../app/(app)/documentation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/engineering-laboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engineering-laboratory">> = Specific
  const handler = {} as typeof import("../../app/(app)/engineering-laboratory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/engineering-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engineering-review">> = Specific
  const handler = {} as typeof import("../../app/(app)/engineering-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs">> = Specific
  const handler = {} as typeof import("../../app/(app)/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../app/(app)/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/meta-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meta-factory">> = Specific
  const handler = {} as typeof import("../../app/(app)/meta-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/modernize/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/modernize">> = Specific
  const handler = {} as typeof import("../../app/(app)/modernize/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform">> = Specific
  const handler = {} as typeof import("../../app/(app)/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/project-rooms/[roomId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-rooms/[roomId]">> = Specific
  const handler = {} as typeof import("../../app/(app)/project-rooms/[roomId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/project-rooms/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-rooms/import">> = Specific
  const handler = {} as typeof import("../../app/(app)/project-rooms/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/project-rooms/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-rooms/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/project-rooms/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/project-rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-rooms">> = Specific
  const handler = {} as typeof import("../../app/(app)/project-rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/(app)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../app/(app)/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/skills">> = Specific
  const handler = {} as typeof import("../../app/(app)/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/system-status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system-status">> = Specific
  const handler = {} as typeof import("../../app/(app)/system-status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../app/(app)/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/wizard/[missionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/[missionId]">> = Specific
  const handler = {} as typeof import("../../app/(app)/wizard/[missionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/wizard/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard/new">> = Specific
  const handler = {} as typeof import("../../app/(app)/wizard/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(app)/wizard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wizard">> = Specific
  const handler = {} as typeof import("../../app/(app)/wizard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
