from __future__ import annotations

from pathlib import Path
from uuid import uuid4

from fastapi import HTTPException, UploadFile, status

from app.core.config import DATA_DIR, get_settings

# Private storage for the enrollment document behind the Plano Estudante
# discount (vault 56 - Monetização e Consumo/Planos, assinaturas e controle de
# acesso.md). Never served statically -- only reachable through
# get_student_verification_document's owner-only route.
STORAGE_ROOT = DATA_DIR / "student-documents"

_ALLOWED_CONTENT_TYPES: dict[str, str] = {
    "application/pdf": ".pdf",
    "image/jpeg": ".jpg",
    "image/png": ".png",
}


def _extension_for(content_type: str | None) -> str:
    if content_type not in _ALLOWED_CONTENT_TYPES:
        allowed = ", ".join(sorted(set(_ALLOWED_CONTENT_TYPES))).replace("image/jpeg", "image/jpeg (JPG/JPEG)")
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={
                "code": "STUDENT_DOCUMENT_UNSUPPORTED_TYPE",
                "message": f"Unsupported file type. Allowed: {allowed}.",
            },
        )
    return _ALLOWED_CONTENT_TYPES[content_type]


async def save_student_document(user_id: str, file: UploadFile) -> str:
    """Streams the upload to private, per-user storage WITHOUT buffering it
    fully in memory (same streaming-with-cap pattern as modernize.py's
    _spool_upload). Returns an opaque storage key (never a client-supplied
    value -- vault: "Nunca enviar apenas uma URL informada pelo usuário")."""
    extension = _extension_for(file.content_type)
    max_bytes = get_settings().student_document_max_upload_bytes
    user_dir = STORAGE_ROOT / user_id
    user_dir.mkdir(parents=True, exist_ok=True)
    storage_key = f"{user_id}/{uuid4().hex}{extension}"
    destination = STORAGE_ROOT / storage_key
    written = 0
    try:
        with open(destination, "wb") as out:
            while True:
                chunk = await file.read(1 << 20)  # 1 MiB
                if not chunk:
                    break
                written += len(chunk)
                if written > max_bytes:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail={
                            "code": "STUDENT_DOCUMENT_TOO_LARGE",
                            "message": f"File exceeds the {max_bytes // (1024 * 1024)} MB limit.",
                        },
                    )
                out.write(chunk)
    except BaseException:
        destination.unlink(missing_ok=True)
        raise
    if written == 0:
        destination.unlink(missing_ok=True)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"code": "STUDENT_DOCUMENT_EMPTY", "message": "Empty upload."},
        )
    return storage_key


def delete_student_document(storage_key: str) -> None:
    """Best-effort cleanup for a storage key that was just written but whose
    submission was then rejected (e.g. StudentAlreadySubmittedError) -- never
    leave an orphaned file with no matching StudentVerification row."""
    resolve_student_document_path(storage_key, missing_ok=True).unlink(missing_ok=True)


def resolve_student_document_path(storage_key: str, *, missing_ok: bool = False) -> Path:
    """Resolves a storage key to an absolute path, rejecting anything that
    would escape STORAGE_ROOT (defense in depth -- the key format is always
    server-generated by save_student_document, never client input, but a
    future bug or data-migration slip should not become a path traversal)."""
    resolved_root = STORAGE_ROOT.resolve()
    candidate = (STORAGE_ROOT / storage_key).resolve()
    if resolved_root not in candidate.parents and candidate != resolved_root:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found.")
    if not missing_ok and not candidate.is_file():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Document not found.")
    return candidate


_CONTENT_TYPE_BY_EXTENSION = {".pdf": "application/pdf", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png"}


def content_type_for(path: Path) -> str:
    return _CONTENT_TYPE_BY_EXTENSION.get(path.suffix.lower(), "application/octet-stream")
