"""initial schema

Revision ID: 68b1ef9a3a1c
Revises: 
Create Date: 2026-06-30 22:00:54.762405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b1ef9a3a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_event_code', ['event_code'], unique=False)
        batch_op.create_index('idx_audit_logs_user_id', ['user_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=False),
    sa.Column('blueprint_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_generation_jobs_owner', ['owner_user_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_project_id'), ['project_id'], unique=False)

    op.create_table('git_provider_connections',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('profile_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.create_table('git_provider_repositories',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('repo_key', sa.String(), nullable=False),
    sa.Column('repository_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'repo_key')
    )
    op.create_table('modernize_jobs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('modernize_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_modernize_jobs_owner', ['owner_user_id'], unique=False)

    op.create_table('project_rooms',
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_intent', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('spec_json', sa.Text(), nullable=True),
    sa.Column('messages_json', sa.Text(), nullable=False),
    sa.Column('prompt_master_md', sa.Text(), nullable=True),
    sa.Column('prompt_master_versions_json', sa.Text(), nullable=False),
    sa.Column('architecture_blueprint_json', sa.Text(), nullable=True),
    sa.Column('blueprint_versions_json', sa.Text(), nullable=False),
    sa.Column('active_blueprint_version', sa.Integer(), nullable=True),
    sa.Column('generation_handoff_json', sa.Text(), nullable=True),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('operational_log_json', sa.Text(), nullable=False),
    sa.Column('last_failure_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    with op.batch_alter_table('project_rooms', schema=None) as batch_op:
        batch_op.create_index('idx_project_rooms_owner', ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_rooms_status'), ['status'], unique=False)

    op.create_table('projects',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('stack_id', sa.String(), nullable=True),
    sa.Column('project_locale', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('generation_mode', sa.String(), nullable=False),
    sa.Column('technology_graph_json', sa.Text(), nullable=False),
    sa.Column('architecture_id', sa.String(), nullable=False),
    sa.Column('archetype_id', sa.String(), nullable=False),
    sa.Column('selected_capabilities_json', sa.Text(), nullable=False),
    sa.Column('selected_business_modules_json', sa.Text(), nullable=False),
    sa.Column('selected_endpoints_json', sa.Text(), nullable=False),
    sa.Column('blueprint_snapshot_json', sa.Text(), nullable=False),
    sa.Column('architectural_graph_snapshot_json', sa.Text(), nullable=True),
    sa.Column('prompt_master_snapshot_json', sa.Text(), nullable=False),
    sa.Column('gatekeeper_snapshot_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('readiness_status', sa.String(), nullable=False),
    sa.Column('contract_version', sa.String(), nullable=False),
    sa.Column('generated_project_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_key'), ['project_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_refresh_tokens_user_id', ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('consent_accepted_at', sa.String(), nullable=True),
    sa.Column('consent_policy_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_tokens_user_id')
        batch_op.drop_index('idx_refresh_tokens_expires_at')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_project_key'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('project_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_rooms_status'))
        batch_op.drop_index('idx_project_rooms_owner')

    op.drop_table('project_rooms')
    with op.batch_alter_table('modernize_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_modernize_jobs_owner')

    op.drop_table('modernize_jobs')
    op.drop_table('git_provider_repositories')
    op.drop_table('git_provider_connections')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_project_id'))
        batch_op.drop_index('idx_generation_jobs_owner')

    op.drop_table('generation_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user_id')
        batch_op.drop_index('idx_audit_logs_event_code')
        batch_op.drop_index('idx_audit_logs_created_at')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
